### PR TITLE
CurlHack

### PR DESCRIPTION
**Pull request by shawngong**
This allows curl output to be shown when the user clicks "try it now" in swagger UI. 

Set it up in the "dist" folder to provide an easy demo of how it works. 

Should be helpful for issue 1073.

### CODE REVIEW

**Comment by earth2marsh** [comment]
Should this leverage the `asCurl` function in client.js? See: https://github.com/swagger-api/swagger-js/blob/3e498a5d0b0d7fc493f01eed2371c4fed8019813/lib/types/operation.js#L780

**Comment by shawngong** [comment]
I will look into that! Was not aware of it until now.

**Comment by webron** [comment]
@shawngong - can you please rebase? We're running through the open PRs in the next couple of days.

**Comment by shawngong** [comment]
@webron Done rebasing, there were no conflicts.

**Comment by webron** [comment]
Well, there are conflicts unfortunately. Can't be merged automatically. We'll have to look into it.

**Comment by shawngong** [comment]
@webron Thank you.

**Comment by Smolations** [comment]
I just noticed that bootstrap was included in the libs in `develop_2.0` so I went looking for the PR that added it, and here it is.  Unfortunately, I cannot see where bootstrap is being used. There is no script tag loading it in index.html and the gulpfile doesn't seem to indicate that it gets bundled with anything.  Can someone clarify? 

cc/  @shawngong @webron

**Comment by shawngong** [comment]
@Smolations Thanks for the catch! Yes that is entirely my fault, I accidentally added bootstrap when it was not being used. If someone with write access could remove it that would be much appreciated.

**Comment by webron** [comment]
@shawngong - just submit a quick PR

**Comment by shawngong** [comment]
@webron Okay done

**Pull request merged**
