### PR TITLE
Show readOnly values in responses

### PR DESCRIPTION
**Pull request by furkanayhan**
Hi there,

I am not sure that this is the right way to achieve this behaviour, but before this, it was not rendering my nested readOnly attributes.

Here is my resources:
```yaml
  ResourceIdentifier:
    type: object
    required:
      - id
    properties:
      id:
        type: string
        maxLength: 255
      type:
        type: string
        readOnly: true
  ResourceMeta:
    type: object
    properties:
      created-at:
        type: string
        format: date-time
        readOnly: true
      updated-at:
        type: string
        format: date-time
        readOnly: true

  Product:
    type: object
    allOf:
      - $ref: '#/definitions/ResourceIdentifier'
      - type: object
        properties:
          meta:
            $ref: '#/definitions/ResourceMeta'
      - type: object
        properties:
          attributes:
            type: object
            properties:
              stock_count:
                type: number
                readOnly: true
              name:
                type: string
                readOnly: false
              unit:
                type: string
                readOnly: false
```

Before:

screen shot 2017-04-13 at 16 04 39

After:
screen shot 2017-04-13 at 16 04 55

### CODE REVIEW

**Comment by webron** [comment]
Thanks for the PR. I'll wait for @shockey to review the code itself, but a couple of issues:
1. `readOnly`, if rendered in the sample, should only be rendered in the responses. It seems like your code change would affect body parameter rendering too.
2. Build is failing 😕

**Comment by furkanayhan** [comment]
Thanks for the quick response @webron .

1. We don't send `{ includeReadOnly: true }` to  `getSampleSchema` in anywhere but in `response.jsx`. So I don't think it will affect. (Still not sure about it)
2. I don't know If I should this, but I added react-test-renderer as a dev dependency, and it worked. Any idea?

**Comment by shockey** [comment]
LGTM

**Comment by shockey** [comment]
thanks @furkanayhan!

**Pull request merged**
