### PR TITLE
Allows "enter" pressed to change the text box to a text area.

### PR DESCRIPTION
**Pull request by taoyuan**

### CODE REVIEW

**Comment by fehguy** [comment]
@bodnia does this look OK from your POV?

**Comment by bodnia** [comment]
@fehguy is it an expected behaviour of pressing enter key on parameters inputs?
The [issue](https://github.com/swagger-api/swagger-ui/pull/1841) with inconsistent enter key behaviour used to be fixed: there is a form with inputs (and/or text areas) and when a user presses enter on any of input - the form is sent, which is default form behaviour.
As far as rendering a textarea instead of input in case of formData in not an option (as per [comment](https://github.com/swagger-api/swagger-ui/issues/1795#issuecomment-163703168)) so I can move this logic (with small refactoring if you don't mind) into parameter view. @fehguy does this make sense?

**Comment by fehguy** [comment]
In this example, the idea was to make the enter key convert the text-entry box so it can be used for multi-line items.  If it doesn't make sense we can close it out

**Comment by bodnia** [comment]
@fehguy it seems to me that this behaviour may be really confusing: instead of default behaviour - sending form, the user gets the input converted into textarea.

**Comment by fehguy** [comment]
Sounds good.  @taoyuan thanks for the contribution but we're going to pass on merging it.

**Comment by taoyuan** [comment]
I am glad to make some contribution. Maybe using `ctrl + enter` is more appropriate?

**Comment by bodnia** [comment]
[this](https://github.com/swagger-api/swagger-ui/pull/1986#issuecomment-191091129) looks good to me, then we could add a note above the field 'press ctrl + enter to make multiline'. @fehguy does this make sense?

**Comment by fehguy** [comment]
@taoyuan please send a new PR if you'd like to pursue that.

**Comment by taoyuan** [comment]
@fehguy @bodnia I have sent a new PR #2015 to allow `ctrl + enter` pressed to make multiline.

**Pull request closed without merging**
