### PR TITLE
Use password input type for password fields

### PR DESCRIPTION
**Pull request by lifeBCE**

### CODE REVIEW

**Comment by mohsen1** [comment]
@lifeBCE This looks like a very good feature. Couple of thought:

* You should make changes in the source code not the files in the `dist` folder. To start developing, run `gulp serve`, make your changes and let gulp produces a new build in `dist` folder.
* To change the HTML templates change the HTML files not the produced JS file.
* I believe there are multiple places this `input` tag is being rendered (based on required, not require). Please add `{{type}}` to all of them.

**Comment by lifeBCE** [comment]
Yeah I spent some time trying to find the actual source but was unsuccessful. I'll take another look when I have some more time.

**Comment by fehguy** [comment]
added logic in https://github.com/swagger-api/swagger-ui/commit/b1efe883db9c44ce119631665fe4efe680d6db86

**Comment by to-kra** [comment]
Is this also working for @FormData ? in our API using swagger+ui we have formData on login API and password field on swagger-UI has visible characters. can we somehow show *** instead of plain text on formData which are password?

**Comment by fehguy** [comment]
It should be supported, yes.  Just use the following:

```json
{
  "type": "string",
  "format": "password"
}
```

**Comment by to-kra** [comment]
I would like to use it in Java code. Do you have some annotation for it ? thx

**Comment by to-kra** [comment]
@fehguy Can you please answer my question ? How do i define that some String expected on API method is password, for swagger UI - as Backend we have swagger with JAX-RS. Is there any annotation so swagger will produce something for swagger-ui ? thank you in advance

**Comment by fehguy** [comment]
Sorry @to-kra this repo is for swagger-ui.  Please open an issue on swagger-core for this--to be honest I don't think it exists, but that's the right place to ask.

**Comment by to-kra** [comment]
@fehguy I mean this is not just a backend part, I am talking about swagger-ui, to support password fields.

**Pull request closed without merging**
