### PR TITLE
Add translation plugin

### LINKED ISSUE #2488: [improvement] Translation: automatic and manual language selection
**Problem description:**

https://github.com/swagger-api/swagger-ui/blob/1f2a5d7dd74131f0e9886b0f137ac20165aa90d2/dist/lang/translator.js#L6-L8
>     * To enable translation you should include one of language-files in your index.html
>     * after <script src='lang/translator.js' type='text/javascript'></script>.
>     * For example - <script src='lang/ru.js' type='text/javascript'></script>

This is unacceptable in today's internet. Every end user should see his language.
So:

1. `swagger-ui` should determine user's language automatically using the following variables (all of them in the specified order) and apply corresponding translation:
	
	1. [`navigator.languages`](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages)
	2. [`navigator.language`](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language)
	3. [`navigator.userLanguage`](https://msdn.microsoft.com/library/ms534713.aspx)
	
2. End user should be able to change the language using `swagger-ui`.

**Additional information:**
swagger-ui version affected: commit [1f2a5d7](https://github.com/swagger-api/swagger-ui/commit/1f2a5d7dd74131f0e9886b0f137ac20165aa90d2)
swagger file: not required

### PR DESCRIPTION
**Pull request by AlexMayants**
### Description
Inject `translate` function into all components that require localization.

Built-in support for English (default) and Russian.

Support for custom localization via `translations` config option.

Add lint rule to avoid naked (untranslated) strings in react components.

Added configuration options: `translations`, `translationLanguage`, `defaultTranslationLanguage`.

### Motivation and Context

Fixes #2488

### How Has This Been Tested?

All existing tests are in the green.

### My PR contains... 
- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [x] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [x] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [ ] are not breaking changes.

### Documentation
- [ ] My changes do not require a change to the project documentation.
- [x] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by LariscusObscurus** [comment]
This seems to be exactly what I need for my application. In an globalized age we can not expect every user to understand english. Would it be possible to get this merged soon?

**Comment by martinszy** [comment]
Hello, any chance to see this merged?

**Comment by mmodolo** [comment]
Hi, when can we expect to see this merge?

**Comment by tim-lai** [comment]
@AlexMayants Thanks for the PR! It is very comprehensive. However, such a translation plugin should be an independent and separately maintained project from the SwaggerUI.

**Comment by AlexMayants** [comment]
@tim-lai I see your point. However, I'm not sure how to implement such a plugin without recreating a large percentage of SwaggerUI components. It seems to me that SwaggerUI should provide at least some way to alter localizable values: via config, maybe. Could you suggest a way to approach this?

**Comment by LariscusObscurus** [comment]
Really disappointing to see this getting closed. Not everyone speaks english.

**Comment by fenomeno83** [comment]
Hi.
I've created a system to "translate" swagger ui 3.x react based.

It is not more elegant, but I think is fastest way to do this.

The concept is:
1-when sections where there is a label in English, we want replace dom html

To do this, we need to include:
1-jquery 3.3.1
2-jquery initialize https://github.com/pie6k/jquery.initialize
3-a translation json (example https://drive.google.com/file/d/1YEtbSEDwlnDwrcjewS-tEKr6bPJ0SRb2/view?usp=sharing )
In this italian example we try to localize some "name" and "description" labels:
     
    var resource_globalization = {
    "Name": "Nome",
    "Description": "Descrizione"
    };
4-translate.js that makes translation (example where add others translations https://drive.google.com/file/d/1FkpAXV1oOpA4-VxrrHBABHBxkZTveTkI/view?usp=sharing )
Jquery initialize keeps listening when a specific element is load
So we need to found all elements/sections to translate and replace html

Here my actual code of translate.js like in downloaded file

    
    $(document).ready(function () {

		$.initialize('.opblock-title', function() {		
			$(this).find('span').html(resource_globalization["Description"]);
         });
		 
		 $.initialize('table.parameters', function() {		
		 
			 $(this).find('th.parameters-col_name').html(resource_globalization["Name"]);
			 $(this).find('th.parameters-col_description').html(resource_globalization["Description"]);
         });
		 		
    });

In this case we listen for example when .opblock-title is loaded and find span to replace text using json file.

**I need help to find all section to translate (based on old swagger-ui 2.x traslation?) and than I can use the same method used in the translate.js example to complete this file**


PS: if you use last swashbucke .net core, you need to:
1-create a wwwroot folder (if doesn't exists) with the 4 files
2-add static filesupport in startup.cs
            
     app.UseStaticFiles();

3-inject js files in swaggerui configuration in startup.cs
       
    app.UseSwaggerUI(c =>
            {
                
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "Public API");

                c.HeadContent = "<script src='./jquery-3.3.1.min.js'></script><script src='./jquery.initialize.min.js'></script><script src='./it.js'></script><script src='./translate.js'></script>";

                c.RoutePrefix = string.Empty;
            });

**Pull request closed without merging**
