### PR TITLE
Remove `node_modules` package from  build

### PR DESCRIPTION
**Pull request by NPi2Loup**

### CODE REVIEW

**Comment by ponelat** [comment]
We kinda need that file :) It's the engine of swagger-ui and it even has it's own repo... http://github.com/swagger-api/swagger-js

**Comment by NPi2Loup** [comment]
Ok, but why swagger-ui weight 100Ko before and 2.3Mo now ?

**Comment by ponelat** [comment]
That is the minification error... see: https://github.com/swagger-api/swagger-js/pull/477

**Comment by NPi2Loup** [comment]
Ok, thanks for explaining

**Pull request closed without merging**
