### PR TITLE
Show deprecated operations strikethrough

### PR DESCRIPTION
**Pull request by jkoepcke**

### CODE REVIEW

**Comment by callenx** [comment]
Interesting.  I added this in 20c555306f5ad6eddd99ffe4fb40e0f1d5e9fd74, but it was removed in b0301d6ee3fa28497487127a850fdf99fdf3f9f3.

**Comment by nickcmaynard** [comment]
Despite being merged, this change is missing in master and tag v2.1.4.

**Comment by fehguy** [comment]
Looks like it works to me:

image

```json
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "This is a demo api",
    "description": "Hope you enjoy it!"
  },
  "paths": {
    "/hello": {
      "get": {
        "deprecated": true,
        "description": "it's a simple test",
        "parameters": [
          {
            "in": "query",
            "name": "username",
            "type": "string",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "it worked",
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "SuccessResponse": {
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        }
      }
    }
  }
}
```

**Comment by nickcmaynard** [comment]
This patch added strikethrough styling to the operation name.  That doesn't happen.  Indeed, the CSS alterations present in this patch are not present in either `screen.css` or `print.css`.

**Comment by fehguy** [comment]
ok i'm happy to reapply a PR if you can send it.

**Comment by nickcmaynard** [comment]
See #1924.

**Comment by ningyougang** [comment]
Support `deparecated` just on a filed?

**Pull request merged**
