### PR TITLE
Show file upload for schema binary format

### LINKED ISSUE #5636: Request bodies with content types such as application/zip do not have a file upload input
### Q&A (please complete the following information)
 - Swagger-UI version: 3.23.11
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

```json
"requestBody": {
          "content": {
            "application/zip": {
              "schema": {
                "type": "string",
                "format": "binary"
              }
            }
          }
```

### Describe the bug you're encountering

When a request body has `application/zip` as the content type, the input box on swagger-ui is a textbox with "string" as the default value. It should be a file input box.

### Additional context or thoughts

Changing the content type to `application/octet-stream` results in a file upload box, but I'd rather have the more specific content type in my openapi description. I think it would be better to look at the schema's type and format rather than the mime type to decide whether or not to use a file upload.

### PR DESCRIPTION
**Pull request by neiser**
When the spec has `format: binary` as the schema for a request body, the UI should show a file upload as it already does for some specific content types. This enables support for basically any type of content, see also discussion in #5636.

### Description
* Checks for "format: binary" and then takes that `if` in `request-body.jsx`
* Also fixes a little display bug actually showing the selected content type

### Motivation and Context
Fixes #5636

### How Has This Been Tested?
Tested locally with spec from https://github.com/swagger-api/swagger-ui/issues/5636#issuecomment-850134081

### Screenshots (if appropriate):

File upload for application/zip:
image

Correct content type display (instead of hardcoded value):
image

### My PR contains... 
- [x] Bug fixes (non-breaking change which fixes an issue)
- [x] Features (non-breaking change which adds functionality)

### My changes...
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.

### Automated tests
- [x] My changes can and should be tested by unit and/or integration tests.

Can you maybe add a little test case? I'm not really familiar with the code base. Feel free to add commits to that PR!

### CODE REVIEW

**Comment by tim-lai** [comment]
@neiser Thanks for the PR! I think this solution is acceptable. I think we should also include a check for `format: base64` as well.  In addition, this PR should include tests, where Cypress is probably the easiest to implement.

**Comment by neiser** [comment]
@tim-lai Thanks for your response. If we want to support `format: base64` as well, shouldn't Swagger UI also convert the payload which is uploaded accordingly? Or is this already happening in some other part of the code base?

I'm quite unexperienced in Swagger UI code base, but I'll see if I can manage to also write tests for it. I can't promise any timeline, so feel free to add it yourself if you find time.

**Comment by tim-lai** [comment]
@neiser I believe SwaggerUI generally expects/handles files as `format: base64`. I think this was due to original implementation support of `application/octet-stream`. So adding `format:base64` makes it an explicit check that SwaggerUI should already support. 🤞 😄

**Comment by neiser** [comment]
@tim-lai I've added `format: base64` support. I can't promise if I'll find time to write a cypress test case.

**Comment by neiser** [comment]
@tim-lai I've just added a cypress test verifying an upload button is displayed for the various options (either certain content types or schema formats). I didn't quite get your comment on `base64` handling and I've also not a good clue how to test this properly (again, I'm quite unexperienced with e2e frontend testing). 

Feel free to "edit" this PR and make corrections before merging. From my point of view, it should be done now.

**Comment by tim-lai** [comment]
@neiser The Cypress tests captured what I was looking for... that the file upload button is displayed. Thanks for feature, test, and follow-up. PR is merged!

**Pull request merged**
