### PR TITLE
Apply css only on first child label and span for section header

### PR DESCRIPTION
**Pull request by Soullivaneuh**
### Description
To ensure it does not modify other span and label design

### Motivation and Context
This bugfix is needed because it breaks other application that may be used inside swagger.

In my case, the select2 rendering was broken because of the using of multiple span elements.

### How Has This Been Tested?
I just changed the two lines and tested on my browser.

### Screenshots (if appropriate):

Before (with select2):

image

After:

image

### My PR contains... 
- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by shockey** [comment]
jenkins, please build

**Comment by shockey** [comment]
please build

**Comment by Soullivaneuh** [comment]
@shockey What do you mean? I just did a quick edit from the GitHub editor.

**Comment by shockey** [comment]
oh, apologies @Soullivaneuh - `please build` is a trigger phrase that tells the automated tests to run again! sorry for the confusion 😄

**Comment by Soullivaneuh** [comment]
@shockey Build is passing. Could you please merge it and release a bug fix? :-)

**Comment by Soullivaneuh** [comment]
@shockey Anything else to do to get this merged?

**Comment by shockey** [comment]
all good @Soullivaneuh! thanks for the contribution 👍

**Comment by Soullivaneuh** [comment]
Glad to see this merged, thanks! :+1:

**Pull request merged**
