### PR TITLE
feat: add copy path to clipboard button

### LINKED ISSUE #5799: I need a copy-to-clipboard icon next to each swagger route
### Is your feature request related to a problem?
I’d love to be able to select the route and copy it, or a little copy-to-clipboard button would work too. Unfortunately, right now if I try to select the text I end up dragging it all the way through.

### Describe the solution you'd like
I want a copy-to-clipboard icon next to each route.

### Additional context
image

### PR DESCRIPTION
**Pull request by iamandrewluca**
### Screenshots
<details>
<summary>Collapsed Screenshots</summary>

image

image

image

</details>

### My PR contains... 

- [x] Improvements (misc. changes to existing features)
- [x] Features (non-breaking change which adds functionality)

### My changes...
- [x] are not breaking changes.

### Documentation
- [ ] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

Closes #5799

### CODE REVIEW

**Comment by tim-lai** [comment]
@iamandrewluca Taking a look at this draft PR... I think this is a good feature to have. I like that you pulled "Copy" into its own component. I think a more descriptive name for the component would be "CopyToClipboard", as it expresses UX intent. Otherwise, just needs some tests alongside this PR. Thanks!

**Comment by tim-lai** [comment]
@iamandrewluca following up on this draft PR, UX is okay with this change.

**Comment by ylesaout** [comment]
Just to notify that, in my point of view, it would be a great feature. Currently it's a headhache to just copy/paste a path.

**Comment by iamandrewluca** [comment]
I will take some time next weekend, to rebase/review the PR.

**Comment by rjouhann** [comment]
How do we turn on this feature?

**Pull request closed without merging**
