### PR TITLE
Adding enum values for Enum Type in Swagger ReadOnly documentation

### PR DESCRIPTION
**Pull request by dedece35**
### Description
SwaggerUI documentation in ReadOnly mode doesn't give : 
- the available values of an "Enum" type
- default value
- example value

These values are given when "Try it out" button is clicked.

Now, these available values are also displayed on readonly mode of swaggerUI.

### Motivation and Context
I want know available values for an Enum type, default value and example value without clicking on "Try it out" button.

### How Has This Been Tested?
To develop this feature, I followed CONTRIBUTING.md file such as :
- I launched "npm run dev" to have the test page ("Pets" API)
- I developed and verified results in page http://localhost:3200 and see the rendered result
- I launched "npm test" and verified that all is OK

### Screenshots (if appropriate):
the red square zone is the result of my feature.
addenumvalues

### Types of changes

- [ ] No code changes (changes to documentation, CI, metadata, etc)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shockey** [comment]
Setting this aside pending @webron's feedback about the larger UX changes we want to make 👍

**Comment by dedece35** [comment]
ok thank you a lot @shockey

**Comment by dedece35** [comment]
hello, have you some news about feedback ?

**Comment by dedece35** [comment]
thanks a lot to you @shockey

**Pull request merged**
