### PR TITLE
Improve enum values for Enum Type in Swagger ReadOnly documentation

### PR DESCRIPTION
**Pull request by dedece35**
SwaggerUI documentation in ReadOnly mode gives :
- the available values of an "Enum" type
- default value
- example value
From improvement https://github.com/swagger-api/swagger-ui/pull/3977

One enum items representation wasn't considered in swagger.json
Currently considered in swagger.json :
`...
"parameters": [
            {
              "name": "status",
              "in": "query",
              "description": "Status values that need to be considered for filter",
              "required": true,
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "available",
                  "pending",
                  "sold"
                ],
                "default": "available",
                "example": "pending"
              },
              "collectionFormat": "multi"
            }
          ],
...` 

Not considered in swagger.json (example swagger.json generated from swagger annotations in Java code) - there is no "items" structure for "enum" values : 
`...
"parameters": [
            {
                "name": "stockstatus",
                "in": "query",
                "description": "stock status values that need to be considered for filter",
                "required": false,
                "type": "string",
                "default": "full",
                "x-example": "empty",
                "enum": [
                  "empty",
                  "halfempty",
                  "full"
                ]
            }
          ],
...` 

### Description

- rename variables for enum managment
- add managment for new structure ("enum", "x-example", "default")
- add example json swagger ("swagger-petstore-enum.json") for developers (we can now add "http://localhost:3200/swagger-petstore-enum.json" to test new path added for this feature ("/store/findByStock") ) 

### Motivation and Context

As I described in my old PR https://github.com/swagger-api/swagger-ui/pull/3977 , I think it's good idea to have access to default value, example value et availables values in readonly mode (not in TryItOut mode).
This PR is able to solve a new situation in swagger.json (enum values can be out of "items" structure)

~There is NO issue for this feature~

Fixes https://github.com/swagger-api/swagger-ui/issues/2873.

### How Has This Been Tested?

I tested in the same way as my old PR https://github.com/swagger-api/swagger-ui/pull/3977

"npm test" results : 
`236 passing (744ms)
  11 pending`

### Screenshots (if appropriate):
the red square zone is the result with new path added ("/store/findByStock") and new Enum values managment
swagger-ui-bis

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by dedece35** [comment]
do you have some news about this pull request ?

**Comment by dedece35** [comment]
@shockey ? :)

**Comment by webron** [comment]
@dedece35 we've slated time next week to address open PRs, check their functionality, give feedback, and merge if appropriate. Thanks for submitting the PR, and thanks for waiting. We appreciate the community contributions, just a bit overwhelmed with work :)

**Comment by dedece35** [comment]
@webron OK ... thanks for your answer :)

**Comment by dedece35** [comment]
@webron I let myself to revive you about my pull-request :)
I'm really expecting a lot of this PR to integrate it in dev in many REST APIs in my french society.

thanks again :)

**Comment by webron** [comment]
@dedece35 - I'm willing to go ahead and merge it (pending code review) for the functionality - but keep in mind that we may change it completely in the future. The need is understandable, which is why I think we should move forward with it, but design wise it may not be the best solution (no offense).

**Comment by shockey** [comment]
thanks @dedece35! 😄

**Comment by dedece35** [comment]
thanks to you :)

**Pull request merged**
