### PR TITLE
Add support for multiple API URLs in Docker image

### PR DESCRIPTION
**Pull request by phss**
### Description

The API_URLS environment variable can be used to run the Docker image with multiple URLs.

Example:
`docker run -p 80:8080 -e API_URLS=[{name:"First API", url:"http://firstapiurl"},{name:"Second API", url:"http://secondapiurl"}] swaggerapi/swagger-ui`

### Motivation and Context
Currently, there's no way to run the Docker container using multiple URLs, as specified in https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md

This follows the same pattern of variable substitution to replace `url` by `urls` with the value of $API_URLS

### How Has This Been Tested?
Started up Docker locally with and without the API_URLS environment variable, to check it still works as expected.

### Types of changes
- [ ] No code changes (changes to documentation, CI, metadata, etc)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by willejs** [comment]
@shockey any thoughts on this?

**Comment by shockey** [comment]
CC: https://github.com/swagger-api/swagger-ui/issues/3902

This seems alright to me. I'm not super excited by passing raw JSON through env vars, but it is the most direct way to do it.

**Comment by shockey** [comment]
thanks, @phss! this will go live tonight 😄

**Comment by shockey** [comment]
Working example in zsh: `docker run -p 80:8080 -e "API_URLS=[{name:\"Petstore\", url:\"http://petstore.swagger.io/v2/swagger.json\"},{name:\"USPTO\", url:\"https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/uspto.yaml\"}]" swaggerapi/swagger-ui`

**Comment by yscialom** [comment]
As of v3.24.2, this feature is not present anymore.

**Pull request merged**
