### PR TITLE
Correctly handle encoding of body parameter that is enum when api consumes application/json

### PR DESCRIPTION
**Pull request by saadmufti**
Correctly handle encoding of body parameter that is enum when api consumes application/json

Currently the UI sends just the bare string with no quotes around it when an API has an enum body parameter and consumes application/json, and the bare string without quotes is not valid json. Now there is some argument as to whether even a quoted string by itself is valid json, but a lot of json parsers accept it and allow the API to be invoked. In its current form the API cannot be invoked from the UI no matter what json parser you're using. I tested this on a 2.x version of Jersey.

### CODE REVIEW

**Comment by fehguy** [comment]
thank you @saadmufti I'd like to get a test around this.  Can you provide a swagger-spec that exhibits the behavior?

**Comment by saadmufti** [comment]
@fehguy sorry I don't really know how to write an automated test for this but I am willing to do one if you can show me an example of the kind of tests you guys write. Here is a swagger-spec from our app where I eliminated the api's and models that don't have anytrhing to do with the issue. The POST API in here is the one that has the issue.

{
    "apiVersion": "1.0",
    "swaggerVersion": "1.2",
    "basePath": "https://dmp-dev-taxonomy.advertising.aol.com/taxonomy",
    "resourcePath": "/segment",
    "produces": [
        "application/json"
    ],
    "consumes": [
        "application/json"
    ],
    "apis": [
        {
            "path": "/v1/segment/{segmentId:[0-9]+}/status",
            "operations": [
                {
                    "method": "GET",
                    "summary": "Get segment status",
                    "notes": "",
                    "type": "string",
                    "nickname": "getStatus",
                    "parameters": [
                        {
                            "name": "segmentId",
                            "description": "id of segment",
                            "required": true,
                            "type": "integer",
                            "format": "int32",
                            "paramType": "path",
                            "allowMultiple": false
                        }
                    ],
                    "responseMessages": [
                        {
                            "code": 404,
                            "message": "Segment not found"
                        },
                        {
                            "code": 403,
                            "message": "No permission to access this segment"
                        }
                    ]
                },
                {
                    "method": "PUT",
                    "summary": "Set segment status",
                    "notes": "",
                    "type": "integer",
                    "format": "int32",
                    "nickname": "setStatus",
                    "parameters": [
                        {
                            "name": "segmentId",
                            "description": "id of segment",
                            "required": true,
                            "type": "integer",
                            "format": "int32",
                            "paramType": "path",
                            "allowMultiple": false
                        },
                        {
                            "name": "body",
                            "description": "new status of segment",
                            "required": true,
                            "type": "string",
                            "paramType": "body",
                            "allowMultiple": false,
                            "enum": [
                                "ENABLED",
                                "DISABLED",
                                "DELETED",
                                "ONE_TIME_USE"
                            ]
                        },
                        {
                            "name": "cascade",
                            "description": "whether or not to cascade status to descendants. DELETED and DISABLED must cascade",
                            "required": true,
                            "type": "boolean",
                            "paramType": "query",
                            "allowMultiple": false
                        }
                    ],
                    "responseMessages": [
                        {
                            "code": 404,
                            "message": "Segment not found"
                        },
                        {
                            "code": 403,
                            "message": "No permission to update this segment"
                        }
                    ]
                }
            ]
        }
    ],
    "models": {}
}

**Comment by saadmufti** [comment]
@fehguy great, thx

**Comment by fehguy** [comment]
https://github.com/swagger-api/swagger-js/issues/326

**Comment by saadmufti** [comment]
@fehguy hi just curious why this was closed but I don't see that the issue was addressed. Has it been handled in some different way? Thanks.

**Pull request closed without merging**
