### PR TITLE
Set default oauth scope separator to whitespace

### LINKED ISSUE #1598: Default scope separator
The default scope separator should be " " instead of "," in index.html

### PR DESCRIPTION
**Pull request by cbornet**
Fix #1598

### CODE REVIEW

**Comment by fehguy** [comment]
I don't think this is a general fix though, comma is quite "common".  Can we support both?  or is there documentation that it's a formal delimiter?

**Comment by cbornet** [comment]
See https://tools.ietf.org/html/rfc6749#section-3.3 : space is the only acceptable delimiter if you want to be compliant with the spec.

**Comment by cbornet** [comment]
A reason to be compliant to the oauth2 spec is that some frameworks only accept space delimiter and they are hard to configure to something else.
See for instance [spring-security-oauth's code](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/common/util/OAuth2Utils.java#L84) for parsing the scopes.

**Comment by cbornet** [comment]
Also note that ```scope-token = 1( %x21 / %x23-5B / %x5D-7E )``` allows to use comma in a scope name.

**Comment by fehguy** [comment]
@bodnia can you please look at this, and see if it will cause any troubles?

**Comment by bodnia** [comment]
@fehguy tested, it doesn't cause any issues.
But @cbornet could you please set separator in source file https://github.com/swagger-api/swagger-ui/blob/master/src/main/html/index.html#L62 rather than in 'dist' folder as it'll be replaced after build.

**Comment by fehguy** [comment]
@bodnia I've made the change

**Pull request merged**
