### PR TITLE
Add docker support for 3.0.x

### PR DESCRIPTION
**Pull request by fehguy**

### CODE REVIEW

**Comment by fehguy** [comment]
Will be adding new environment variables in an upcoming PR so you can configure the URL, etc.

**Comment by hermansje** [comment]
Configurability with environment variables would be really useful!

**Comment by hermansje** [comment]
In the meantime: Swagger-ui was updated a few hours ago on the Docker hub, but it looks like the most recent version doesn't match the most recent Dockerfile.

**Comment by hermansje** [comment]
The `latest` tag was updated to match the current Dockerfile. Thank you!

**Comment by LandonSchropp** [comment]
@fehguy Do you by chance know when you might be able to add that URL environment variable? I'm adding `swagger` to my team's `docker-compose` file, and it would be really nice if we didn't have to type out the URL of the swagger file every time we use it.

**Comment by fehguy** [comment]
I'm working on that now, based on [feedback](https://github.com/schickling/dockerfiles/issues/55#issuecomment-270072701) from the author of this excellent docker file:  https://github.com/schickling/dockerfiles/tree/master/swagger-ui

**Comment by fehguy** [comment]
@LandonSchropp please see here:

https://github.com/swagger-api/swagger-ui/pull/2901/commits/3ce9baee304dba8d6e05470878543ab0e78d1994

Updated the [docker hub image instructions](https://hub.docker.com/r/swaggerapi/swagger-ui/) for swagger-ui

**Comment by LandonSchropp** [comment]
That worked perfectly! Thanks Tony.

**Comment by fehguy** [comment]
Awesome, thanks for the follow up.

**Pull request merged**
