### PR TITLE
fix(info): font for title, li and table

### PR DESCRIPTION
**Pull request by gierschv**

### CODE REVIEW

**Comment by Minasokoni** [comment]
@gierschv Just need to get rid of that merge conflict and this is gtg

**Comment by tomsaleeba** [comment]
What's the github ettiquette here to get this merged?

1. poke @gierschv to get them to fix their PR
1. fork the gierschv fork and fix it, then PR to gierschv so they can update this PR
1. replicate the changes in my own fork and PR it. (I don't want to steal credit, just want the changes in to get into the main repo)

Cheers

**Comment by webron** [comment]
Oh wow, this flew under my radar, sorry. @gierschv, if you can resolve the conflicts again, I'll merge. Just make note to add a comment that they are resolved, otherwise I may not have a good indication of it.

Sorry for the delay, and thanks for the effort.

**Comment by gierschv** [comment]
@webron Done, and I removed the bundle from the commit, this will avoid getting new conflicts for this PR.

**Comment by webron** [comment]
Thanks again!

**Pull request merged**
