### PR TITLE
remove inline-code

### PR DESCRIPTION
**Pull request by danielleontiev**
This is the follow-up for https://github.com/swagger-api/swagger-ui/pull/7295

I've rebased it on `master` and fix conflicts. Author of the changes in `git` is still `@AndreKoepke`, I am only mentioned as commiter.

I've tested it in IDE-driven server, built docker image and run it, and run `npm run test` - everything looks good.

@tim-lai, please check this one

### CODE REVIEW

**Comment by danielleontiev** [comment]
Are any steps required from me, @tim-lai?

**Review by tim-lai — CHANGES_REQUESTED** [review]
Hi @danielleontiev, thanks for the followup PR. I am encountering two issues with this PR when used with Docker. 

Case 1: provide a different url
```
docker build -t pr/7905 .

docker run --rm -p 80:8080 -e SWAGGER_JSON_URL="https://petstore3.swagger.io/api/v3/openapi.json" -v `pwd`:/app pr/7905
```

Case 2: provide a local file

```
docker build -t pr/7905 .

docker run --rm -p 80:8080 -e SWAGGER_JSON=/foo/sample-multipart-oas3.json -v $(pwd)/dev-helpers/examples:/foo pr/7905
```

I've confirmed both cases work me locally (Mac) with current master branch. Also fyi, I've included the Docker build step in both cases, but one only needs to build the image once if only switching between the two Docker run commands.

**Comment by danielleontiev** [comment]
Thank you for attentive testing! Could you please describe some more details about what issues do you encounter using docker? Because I've tried on MacOS (using podman) and on Linux with native docker installation and have not faced any issues. My steps:

```bash
git clone git@github.com:danielleontiev/swagger-ui.git
cd swagger-ui
docker build -t swagger-ui-master --no-cache .
docker run --rm -d -p 8080:8080 -e SWAGGER_JSON_URL="https://petstore3.swagger.io/api/v3/openapi.json" swagger-ui-master # run master image on 8080
git checkout remove-inline-code
docker build -t swagger-ui-branch --no-cache .
docker run --rm -d -p 8081:8080 -e SWAGGER_JSON_URL="https://petstore3.swagger.io/api/v3/openapi.json" swagger-ui-branch # run branch image on 8081
```

Master image:

image

Branch image:

image


Besides successful page load all buttons seems to work - I can send requests to petstore and recieve responses

**Comment by OrangeMemes** [comment]
@tim-lai I've checked it additionally with Docker Desktop on macOS, and my results are similar to @danielleontiev. Container starts without any issues, page loads, requests work and no errors are in the browser console. I've used your exact commands both on `master` and `remove-inline-code` branches.

**Comment by tim-lai** [comment]
@danielleontiev @OrangeMemes What I am observing is that Docker is always loading the remote OAS3 json file. It's not observing the `-e` parameter.

So for the remote URL case, these two scripts load the same page and definition:  

_expect match with OAS2 screenshot:_
```
docker run --rm -p 80:8080 -e SWAGGER_JSON_URL="https://petstore.swagger.io/v2/swagger.json" pr/7905
```
Petstore-OAS2



_expect match with OAS3 screenshot(currently always getting this):_
```
docker run --rm -p 80:8080 -e SWAGGER_JSON_URL="https://petstore3.swagger.io/api/v3/openapi.json" pr/7905
```

Petstore-OAS3


For local file, it's the same... still loading the remote OAS3 definition. Fyi, my script in earlier comment uses a file located in `<project>/dev-helpers/examples/<sample_definition>.json`.

**Review by tim-lai — COMMENTED** [review]
resolve merge conflicts from [a24860c](https://github.com/swagger-api/swagger-ui/pull/7905/commits/a24860cc32a2ae96555c54aebf39d5e2b59bc192)

**Comment by danielleontiev** [comment]
@tim-lai is it possible that you are facing some obscure browser caching behavior? It works for me with both remote url and with local file mounted inside docker container.

**Review by tim-lai — APPROVED** [review]

**Comment by tim-lai** [comment]
@danielleontiev 

> is it possible that you are facing some obscure browser caching behavior? It works for me with both remote url and with local file mounted inside docker container.

Hmm, interestingly, working off a fresh Firefox update instead of Chrome, the two cases I cited are both working. Not sure on the Chrome status. I'll merge this PR for now, and monitor for any aftereffects.

**Comment by danielleontiev** [comment]
Thank you!

**Pull request merged**
