### PR TITLE
Change location of copy to clipboard button

### LINKED ISSUE #8153: Bad UI behaviour after added "cpoy to clipboard" button
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Firefox
 - Version: 103.0.1
 - Method of installation: npm]
 - Swagger-UI version: 4.13.2
 - Swagger/OpenAPI version: Swagger 2.0

### To reproduce...

1. Move mouse pointer to click expand button
2. "Copy to clipboard" button displayed and shift expand button to the left
3. Real click go to authorization button
 
swagger

### PR DESCRIPTION
**Pull request by filiprejmus**
Change the location of the copy to clipboard button

### Description
This PR moves the copy to clipboard button to a location where it doesn't cause other elements to move in the operation summary bar. It addresses [this issue](https://github.com/swagger-api/swagger-ui/issues/8153) and is providing the exact same change as [this PR](https://github.com/swagger-api/swagger-ui/pull/8267) which unfortunately seems to be abandoned.
Credit to @almirus

### Motivation and Context
Fixes #8153 and #8131 

### How Has This Been Tested?
I built and ran the changed code locally and confirmed that the button now has improved behaviour.

### My PR contains... 
- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ponelat** [comment]
Thanks for the PR. @filiprejmus would you mind taking a screenshot of the new location, so we can expedite the review? I know we've had several requests to move it around, and honestly not sure which is best.

**Comment by filiprejmus** [comment]
image
The button still shows up on hover

**Comment by romanblanco** [comment]
> image
> The button still shows up on hover

I think the important is that the icon to expand the detail stays on it's place.

**Comment by char0n** [comment]
@romanblanco if you agree with the suggestion, please redo the PR according to Material Design spec.

If you do not agree, let's discuss further.

**Comment by filiprejmus** [comment]
@char0n so you suggest to switch chevron and lock?

**Comment by romanblanco** [comment]
```diff
diff --git a/src/core/components/operation-summary.jsx b/src/core/components/operation-summary.jsx
index fd61c0d2..702ceb04 100644
--- a/src/core/components/operation-summary.jsx
+++ b/src/core/components/operation-summary.jsx
@@ -80,8 +80,8 @@ export default class OperationSummary extends PureComponent {
             </div>
           }

-          {displayOperationId && (originalOperationId || operationId) ? <span className="opblock-summary-operation-id">{originalOperationId || operationId}</span> : null}
           <CopyToClipboardBtn textToCopy={`${specPath.get(1)}`} />
+          {displayOperationId && (originalOperationId || operationId) ? <span className="opblock-summary-operation-id">{originalOperationId || operationId}</span> : null}
           <svg className="arrow" width="20" height="20" aria-hidden="true" focusable="false">
             <use href={isShown ? "#large-arrow-up" : "#large-arrow-down"} xlinkHref={isShown ? "#large-arrow-up" : "#large-arrow-down"} />
           </svg>
```

**Comment by char0n** [comment]
Hi @filiprejmus,

Yes I would suggest that, given it's a Material Design recommendation and will allow us to extend the `Action bar` in consistent way in future. What do you think?

PS: Sorry I confused the ownership of this PR and asked @romanblanco to redo the PR, but you're the author obviously.

**Comment by filiprejmus** [comment]
@char0n Sounds good, seems way more natural now that I think about it. I will push it sometime next week!

**Comment by char0n** [comment]
> @char0n Sounds good, seems way more natural now that I think about it. I will push it sometime next week!

Yeah I agree, Material Design was created by learning from natural human interaction patterns. They did a great job in Google on it.

**Comment by filiprejmus** [comment]
image
Here my new suggestion with the last commit! Unfortunately I had to remove the black outline that appears on focus for the moment as the shifting around made it complicated to keep.  Thoughts on this look?

**Comment by filiprejmus** [comment]
@char0n ping since there was no follow up in a minute

**Comment by filiprejmus** [comment]
@char0n ping :) don't want this to die

**Comment by dinbtechit** [comment]
Someone, please approve this PR!!!!

**Comment by char0n** [comment]
@filiprejmus sorry for delays. Looking at this now again.

**Comment by char0n** [comment]
@filiprejmus I would agree with the visual representation. But what we lost is a keyboard navigation indicator. The "black outline that appears on focus" was very important as it focused the entire operation row and it was clear we could press enter to expand it, when focused.

**Before**

https://github.com/swagger-api/swagger-ui/assets/193286/8dbf39a7-a2bf-4d19-954e-58be541d8b52

**After**

https://github.com/swagger-api/swagger-ui/assets/193286/f3ba4736-66ad-413b-9f08-d016dd1fb94c

---

In the `After` video, when I navigate with keyboard (Tab key), I've expanded one operation by pressing Enter. But we're missing indicator what's currently focused. We have to think now, how to solve this.

**Comment by char0n** [comment]
@filiprejmus I've issued https://github.com/swagger-api/swagger-ui/pull/9111 which supersedes this PR. PR contains explanation and video how the keyboard navigation and elements now behave.

**Comment by char0n** [comment]
Closing in favor of https://github.com/swagger-api/swagger-ui/pull/9111. Thank you very much @filiprejmus for pushing this forward.

**Pull request closed without merging**
