### PR TITLE
Adding a Modal Panel to set global API_KEY

### PR DESCRIPTION
**Pull request by jayquest**
I did some changes on the templates to add a modal to set the global API_KEY,
and create the styles to do that so.

print

### CODE REVIEW

**Comment by rngtng** [comment]
cool thanks! :+1: 

relates #1593

**Comment by rngtng** [comment]
hm any ideas why the travis tests fail? It says 
```js
undefined:1178
    vlog(2, () => this + ' scheduling notifications', this);
             ^
SyntaxError: Unexpected token )
```

**Comment by fehguy** [comment]
This has been added in the updated auth dialogs.

**Comment by shatestest** [comment]
@jayquest , i have still have same problem with 3.0.x version can you help me how to fix?
I have added this 
  "security": [
		{
		"api_key": []
		}
		],

  "components": {
		"securitySchemes": {
		  "api_key": {
			"type": "apiKey",
			"in": "query",
			"name": "apiKey"
		  }
		}
	  }

**Pull request closed without merging**
