### PR TITLE
Fixes an undefined error when type is defined in the schema

### PR DESCRIPTION
**Pull request by brentonmcs**
If a param type is in the body the type is in the schema.

{"name":"verified","in":"body","required":true,"schema":{"type":"boolean"}}]

### CODE REVIEW

**Comment by tedvanderveen** [comment]
We are suffering from the same issue. Can someone please pick this up as this PR is now over 1 month old?

**Comment by ponelat** [comment]
@brentonmcs could you build and commit those files too? looks simple enough, and I'm sure we can get this in soon.

**Comment by brentonmcs** [comment]
@ponelat  which files am I missing?

**Comment by ponelat** [comment]
@brentonmcs the files under `dist`...
So run `npm run gulp` and commit all files (should just be two, I think)

**Comment by brentonmcs** [comment]
Those files have been added in - @ponelat.

**Comment by ponelat** [comment]
@brentonmcs thanks... it looks like its clashing with the master branch. Probably because they drifted a little. I feel guilty asking you to rebase on master (just the source) and build/commit on top of that :hamster: 
PS: If you feel like this is dragging on too long, just let me know - and I can quickly get this in myself. We appreciate the work.

**Comment by Pjanssen** [comment]
What's the status of this issue?
We've run in to the same issue when using swagger-ui with Swashbuckle. It causes the complete documentation to fail to load. So it would be great if a fix could be integrated!

**Comment by fehguy** [comment]
@Pjanssen I believe the `undefined` error that this PR was trying to address has been fixed.  Please give it a shot from 2.1.5, released yesterday.

**Comment by webron** [comment]
2.1.4

**Pull request closed without merging**
