### PR TITLE
Fixes #3511 - Query & formData parameters together

### LINKED ISSUE #3511: Same parameter as a query and a formData parameter doesn't appear as a formData parameter
swagger-ui version v3.1.2 (and earlier)

File reproducing this issue:
[yaml_test.txt](https://github.com/swagger-api/swagger-ui/files/1193546/yaml_test.txt)

In the attached yaml, authorised is a patch parameter in query and separately in formData.
In the v2 swagger editor, authorised is available as a query parameter and also as a formData parameter - as I would expect.
However with the same yaml, in the swagger v3 editor, authorised is only available as a query parameter.

### PR DESCRIPTION
**Pull request by owenconti**
Fixes #3511

Update changeParameter calls to accept `in` value to identify parameters based on `name` plus `in` value.

Also dependent on a `swagger-js` PR (link to come).

Would love if there was extra hands-on testing with this one. I tested with the spec provided in the issue and with the petstore spec as much as I could.

Here's a shot of both rendering in the UI:

screen shot 2017-08-02 at 6 23 49 pm

### CODE REVIEW

**Comment by owenconti** [comment]
The `swagger-js` PR will need some more time. Broke ~32 tests :man_facepalming:

**Comment by owenconti** [comment]
@webron Is it feasible to enforce that every parameter must have an `in` value? Example:

```
paths: {
            "/one": {
              get: {
                parameters: [
                  { name: "one", in: "query", value: 1},
                  { name: "two", in: "query", value: "duos"}
                ]
              }
            }
          }
```

Second question: Where's the proper place I should be looking (spec rules) to answer my above question?

**Comment by webron** [comment]
The `in` property is required by the spec, so if it doesn't exist, the API definition is invalid.

You can find all the information in the spec.
For 2.0 - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterIn
For 3.0.0 - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#parameterIn

**Comment by owenconti** [comment]
Hi @webron @shockey - Are either of you waiting on me for anything on this PR or the corresponding `swagger-js` PR https://github.com/swagger-api/swagger-js/pull/1115 ?

**Comment by shockey** [comment]
@owenconti, AFAIK this is in my court 😄 I'll get on this today.

**Pull request merged**
