### PR TITLE
Set discriminated properties to mapped value

### PR DESCRIPTION
**Pull request by ahmedalnuaimi**
Set discriminator field value to the one listed in the discriminator mapping if exists

### How Has This Been Tested?
On the sample mentioned in the issue 8209

### My PR contains... 
- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [x] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tim-lai** [comment]
@ahmedalnuaimi Thanks for the PR. Can you provide a before & after screenshot and the expected result? I tried pasting the definition provided in #8209 into editor.swagger.io, but am not observing the difference between it and a local dev version with the changes in this PR.

**Comment by ahmedalnuaimi** [comment]
Before (picking up the first enum always):
```json
[
    {
        "type":"TYPE1"
    }, {
        "type":"TYPE1"
    }
]
```

After (picking up the discriminator enum):
```json
[
    {
        "type":"TYPE1"
    }, {
        "type":"TYPE2"
    }
]
```

**Comment by tim-lai** [comment]
@ahmedalnuaimi Ok, looks like some lint fixes are needed, notably `Error:   349:17  error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins`. Otherwise in principal looks good to me.

**Comment by ahmedalnuaimi** [comment]
> @ahmedalnuaimi Ok, looks like some lint fixes are needed, notably `Error: 349:17 error Do not access Object.prototype method 'hasOwnProperty' from target object no-prototype-builtins`. Refer the the CI check for more details. Otherwise in principal looks good to me.

Should be ready for a final check.

**Comment by tim-lai** [comment]
> Should be ready for a final check.

Looks like the new test is failing on CI? Also a small typo: `exptected` -> `expected`

**Comment by ahmedyarub** [comment]
It looks like I broke the tests after refactoring. Everything should be working now.

**Comment by tim-lai** [comment]
@ahmedalnuaimi PR merged! Thanks for the iteration and contribution!

**Pull request merged**
