### PR TITLE
New feature fix for array of objects in the definitions properties section

### PR DESCRIPTION
**Pull request by akhileshkasibatla**
Currently swagger model definitions cannot accept an array of objects in the properties section of the swagger definitions. So I have added a fix for array of objects in the properties section which can be a new feature for swagger-ui . This feature makes it way easier for someone to document their rest api who is using array of objects in their model definitions.  With this fix instead of giving type as an array we can give type as an object and have properties take array of objects which provides the option of having headless objects(Objects without key) in the properties section.

Issue #3066 has the screenshots associated with the problem in swagger-ui if we try to give properties as array of objects which is actually a valid JSON.

### CODE REVIEW

**Comment by akhileshkasibatla** [comment]
Hello @webron / @shockey 

Any thoughts on whether my pull request will be merged or not??

**Comment by shockey** [comment]
@akhileshkasibatla, thank you for the contribution! I'll do a code review for this but first @webron will be making the call on whether we'll accept the feature.

Please be patient, we have quite a few things in the air at the moment. Rest assured we'll get an answer for you 😄

**Comment by akhileshkasibatla** [comment]
@shockey sure thanks. Was bit curious :smile:

**Comment by webron** [comment]
Thank you for your time and effort, but we cannot accept changes that break away from what the spec actually allows.

**Pull request closed without merging**
