### PR TITLE
Feature: add responseHooks option for callbacks on responses

### PR DESCRIPTION
**Pull request by dolmen**
Add a `responseHooks` option that allows the user to process the response of an API call.
The `responseHooks` option is an object where key is an `operationId` (`nickname`) and value is a function that receives the XHR response object and the `OperationView` object.

Use case: process authentication requests done with the "Try out!" button to inject apiKey in the AuthView and the router on success. I've been able to successfully implement this.

### CODE REVIEW

**Comment by dolmen** [comment]
Thanks! :clap: :clap: :fireworks:

**Comment by dolmen** [comment]
For those interested in how to use this feature, look for the `loginHook` function in the source of http://developers.ijenko.com/api-reference/

**Comment by 1Map** [comment]
@dolmen Can I have an example of how to use this as your link is broken.

**Comment by 1Map** [comment]
Can someone please answer the above question?

**Comment by dolmen** [comment]
@1Map My company collapsed, so the servers are now down. I'll try to find an archive somewhere...

**Comment by dolmen** [comment]
@1Map Bad news: the page has not been archived recently enough by archive.org

**Comment by 1Map** [comment]
@dolmen Thanks for getting back.  I managed somehow to make it work.

**Pull request merged**
