### PR TITLE
Fixed OAuth2 Password flow to match the RFC requirements

### PR DESCRIPTION
**Pull request by frol**
RFC 6749 says that the `scope` parameter should be named as `scope` (rather than `scopes`) and there is no need to encode the string as it is passed via form parameters, which are encoded automatically.

### CODE REVIEW

**Comment by frol** [comment]
While this PR is valid, I discovered another inconsistency with RFC, so I will report the issue shortly and then update the PR to fix it.

**Comment by frol** [comment]
Well, I think this PR can be merged as is because it can be considered as a typo (other OAuth2 Flows use `scope` parameter name just fine).

Here is my thorough summary of the state of OAuth2 Password Flow implementation in Swagger-UI: #3227.

**Comment by zyro23** [comment]
please merge. hit this just now. issue confirmed - parameter needs to be named `scope`.

**Comment by MugeSo** [comment]
@frol 
I send duplicated PR #3404 and it merged, and now I found this.
Please closed this.

**Comment by shockey** [comment]
Thanks @frol, as @MugeSo mentioned, there was another PR that was merged for this.

Sorry this didn't get onto our radar first - thanks for the contribution!

Closing.

**Pull request closed without merging**
