### PR TITLE
Include description of oauth endpoints when parsing openapi

### LINKED ISSUE #5230: OAS 3: oauth2 securityScheme -> description does not appear
### Q&A 
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
When i set an oauth2 securityScheme the description is not displayed.
An info text is displayed about the scopes (i don't want it to appear)

Example Swagger/OpenAPI definition:
```yaml
components:
  securitySchemes:
    oAuthSample:
      type: oauth2
      description: I WANT THAT TO BE DISPLAYED !!
      flows:
        implicit: 
          authorizationUrl: https://api.example.com/oauth2/authorize
          scopes:
            read_pets: read your pets
            write_pets: modify pets in your account
```

### Describe the bug you're encountering
Description doesn't appear and some infos about scopes are displayed

### To reproduce...

1. Set a securityScheme like in the standard example
2. Click on Authorize
3. The description is not visible and this text is always displayed:
Scopes are used to grant an application different levels of access to data on behalf of the end user. Each API may declare one or more scopes.

API requires the following scopes. Select which ones you want to grant to Swagger UI.

Same behavior if you don't set any scopes.

### Expected behavior
Description should appear
Scopes infos should not appear if i don't want to.

### Screenshots
bug_oauth_oas3

### PR DESCRIPTION
**Pull request by michaelzangl**
Fixes #5230 

### Description

This will display the description of oauth endpoints in the authorize dialog.

### Motivation and Context
It was just missing, probably a bug / never tested.

### How Has This Been Tested?
Tested against an OpenAPI definition created by spring + modified unit test to cover it.

### Screenshot

Screenshot

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mathis-m** [comment]
@michaelzangl you add a Screenshot?

**Comment by michaelzangl** [comment]
> @michaelzangl you add a Screenshot?

I added one

**Review by mathis-m — APPROVED** [review]
looks good

**Comment by tim-lai** [comment]
@michaelzangl Thanks for the PR! It looks good to me. However, I am unable to update with the base branch, so could you rebase this PR?

**Comment by michaelzangl** [comment]
@tim-lai done

**Comment by tim-lai** [comment]
@michaelzangl PR merged! Thanks for the contribution!

**Pull request merged**
