### PR TITLE
fixes accessCode POST request to be  an ajax

### PR DESCRIPTION
**Pull request by bodnia**
Removed `POST` request with a form, added as an ajax

### CODE REVIEW

**Comment by ponelat** [comment]
Need to find out why this doesn't work against our test oAuth server... if there is a missing header or something else

**Comment by bodnia** [comment]
@ponelat it doesn't work because the response is redirect, when must be a json

**Comment by AvoH** [comment]
I am getting an issue with redirecting while using oauth2RedirectUrl: "..../oauth2-redirect.html"

Cannot read property 'schema' of undefined
    at :8090/myapp/dist/swagger-ui-bundle.js:73
    at :8090/myapp/dist/swagger-ui-bundle.js:36
    at Object.callback (:8090/myapp/dist/swagger-ui-bundle.js:29)
    at run (oauth2-redirect.html?code=<SOME CODE>state=<SOME STATE>…:36)
    at onload (oauth2-redirect.html?code=<SOME CODE>&state=<SOME STATE>…:3)

As a result, the browser does not redirect back initially, but stays on the redirect html. An additional request to that url ends up redirecting to swagger ui, but the Auth header looks like this:
"authorization: Bearer undefined"

I'm using a java project, my app runs on tomcat/tcserver on 8090

**Comment by bodnia** [comment]
Closing this, as created new https://github.com/swagger-api/swagger-ui/pull/2992

**Pull request closed without merging**
