### PR TITLE
Add zenscroll instead of scroll-to

### PR DESCRIPTION
**Pull request by ponelat**
The main feature of the PR is to allow scrolling with deeplinking, _if swagger-ui is within a container_.

Some real minor enhancements..
Attach the Model opened/closed to a props/state using layoutActions/Selectors
Enhance layout .isShown/show to have data on branch nodes

### CODE REVIEW

**Comment by ponelat** [comment]
will update branch soon-soon

**Comment by ponelat** [comment]
@lshaw-sb when you get a chance. Fix the failing test ( its just missing a prop ).
And don't forget to re-build and commit that as `build`. Thanks!

**Comment by ponelat** [comment]
bump @shockey 
PS: I removed the `build` commits, let me know if that's correct.

**Comment by shockey** [comment]
This PR contains a breaking change (`ModelComponent` became `ModelWrapper`) to an internal API, so we should bump the minor version and make a note in the release notes.

**Pull request merged**
