### PR TITLE
add name tag to bearer input field

### PR DESCRIPTION
**Pull request by RayBB**
### Description

* Adds the [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-name) tag to the html element

### Motivation and Context

By default, swagger-ui does not save authorization bearer - see [docs](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/#authorization). fastapi does not [yet](https://github.com/tiangolo/fastapi/pull/2568) enable users to change the swagger-ui configuration. 

In the mean time I'd like to be able to use bitwarden, my password manager, to autofill this as a [custom field](https://bitwarden.com/help/article/custom-fields/#more-about-custom-field-names). To do so, it needs to have some kind of selector `id`, `name`, `aria-label`, or `placeholder`. 

Since the username and password input fields in swagger-ui already have the `name` tag I followed that pattern.

I understand this isn't the _best_ place to add a fix but it is the easiest. 

There are two additional benefits to adding this:
* make using the website easier for users with assistive technology.
* using a password manager to autofill lets you easily store/cycle through multiple tokens

### How Has This Been Tested?

I ran `npm run test`.
Seeing as this is an extremely small change I wasn't sure if anything more would be appropriate. 

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tim-lai** [comment]
@char0n I'm ok with this change, what do you think?

**Review by char0n — APPROVED** [review]
Looks legit!

**Comment by char0n** [comment]
@tim-lai looks legit, it gives name to input which is specific to `bearer` auth workflow.

**Comment by tim-lai** [comment]
@RayBB fyi, followup PR #7930 changes this to use `aria-label` instead of `name`.

**Pull request merged**
