### PR TITLE
Reapply changes in PR 1740, but fix properly in .less files

### PR DESCRIPTION
**Pull request by nickcmaynard**
As discussed in #1740

### CODE REVIEW

**Comment by fehguy** [comment]
this is probably why it's gone now--the less compilation step will blow over any changes done in the .css files.

**Comment by callenx** [comment]
Thanks for fixing, @nickcmaynard.

**Comment by fehguy** [comment]
@nickcmaynard merging this won't do any good--it needs to be moved to the .less file

**Comment by nickcmaynard** [comment]
It is - changes in `specs.less`.

**Pull request merged**
