### PR TITLE
Fix(styling): Make the Swagger UI Operation page more responsive on smaller screen

### LINKED ISSUE #8940: Compensate Operation content in lower resolution sizes
This can be reproduced both in [SwaggerEditor](https://editor-next.swagger.io/) (v4) and [Swagger Editor](https://editor.swagger.io/) (v5). The preview that is located in the right-hand side (where SwaggerUI displays) is fully collapsible without any limits.  The components tries to compensate, but after some threshold they will stop making visual sense. 

This is not really specific to SwaggerUI. If we take for example [React Material Design](https://editor.swagger.io/) components,  these reference components will too collapse until they stop making sense.

What we can do is to use [Material Design Specification](https://m1.material.io/layout/responsive-ui.html#responsive-ui-breakpoints) and say that our minimal supported break-point is 360dp/px. We will make CSS changes and make sure that Operations and other visual components renders properly on that break-point. Second remediation can be setting the minimum width of the preview pane in the editors (but not sure this is warranted).

Under threshold of 360dp/px what is displayed is no longer guaranteed.  

Work on this can be done progressively, layering changes on top of previous changes:

- Amend CSS of expand level 0
- Amend CSS of expand level 1
….. repeat to level n ….

Currently SwaggerUI has some notion of minimal supported break-point and some components tries to compensate.

image

### PR DESCRIPTION
**Pull request by pedoch**
Make the Swagger UI page more responsive on smaller screens.

### Description
This PR does the following:
- Allows the Search input in the TopBar wrap under the logo at a breakpoint of `550px`, when the screen is too small to contain both on the same line. **_[Screenshot section 1]_**
- Stops the icon in the Authorize Button from moving under the text when space becomes too tight. **_[Screenshot section 2]_**
  - Instead, the Authorize Button itself moves to the next line to create more space for the icon to stay in place.
- Lastly, it allows the operation path to be viewed more easily on smaller screens by moving the operation description below the path and reducing the font-size of the operation method. **_[Screenshot section 3]_**

### Motivation and Context
These changes will improve the responsiveness of Swagger UI on smaller screens. It started off as a fix for this issue - #8940 but grew to a general responsiveness improvement.

Resolves #8940

### How Has This Been Tested?
I tested these style changes using multiple devices on multiple platforms with different screen sizes. 
Also, because these are just styling changes no new tests are needed and all existing tests pass.

##### [1] TopBar Screenshot
Before:
image
After:
Screenshot from 2023-10-19 23-27-29

##### [2] Authorize Button Screenshot
Before:
image
After:
Screenshot from 2023-10-19 23-27-46

##### [3] Operation Summary Screenshots
Before:
image
After:
image

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by char0n** [comment]
Hi @pedoch, thank you for the PR. I've tested locally and it works well. The only noticeable negative effect is that the `Copy button` that appears onhover shifts the size of the texts, but that not something that your canges have caused.

image

**Review by char0n — APPROVED** [review]
LGTM

**Comment by AlexanderKhudoev** [comment]
Now the **Authorize** button moved to Left side..
You need remove `display: flex` from `.schemes` style to make alighn authorize button to the Right side..
sw
photo_2023-11-15_18-06-47

**Comment by char0n** [comment]
@AlexanderKhudoev would you mind issuing a PR?

**Comment by AlexanderKhudoev** [comment]
> @AlexanderKhudoev would you mind issuing a PR?

I unfortunately don't have time to do that yet.
Even if I release the fixes, the very "idea" of optimizing the UI on "mobile devices" after the fix will go back to the state it was 5 days ago, before @pedoch commit

I don't know anyone who uses Swagger on mobile devices. In my practice for 10 years, everyone has only used Swagger through the Desktop browser.

And now, having moved the **Authorize** button to the left, it's become awkward to use Swagger on Desktops.

**Comment by pedoch** [comment]
Apologies, I didn't notice this when testing. @char0n I can push a fix for it if given a couple of hours.

cc: @AlexanderKhudoev

**Comment by pedoch** [comment]
@AlexanderKhudoev it turns out the reason the button was on the left in your screenshot was because the Schemes selector was not present. I failed to take that into account as they were always present while I was working on the issue.

@char0n I have now raised this PR: #9387 which takes this into account and ensures the Authorize button is always on the right on larger screens. Please feel free to take a look at it and approve/merge if you think the proposed solution makes sense.

**Comment by char0n** [comment]
Thank you both @AlexanderKhudoev and @pedoch  for early regression report and fix.

**Comment by bshain-vtinfo** [comment]
Hey there @pedoch , while this is a few months after this has gone in, I believe the changes in this PR introduced a regression around setting `displayOperationId: true`. It pushes the last few characters of the operation id onto a second line & makes the text much harder to read.

E.x. on version 5.9.4 (after this change went in):

image

And on version 5.9.3 (before this change went in):

image

I haven't seen a fix go up yet for this anywhere, so just wanted to call it out at least.

**Comment by char0n** [comment]
Hi @bshain-vtinfo,

Thanks a lot for the report. Would you try to investigate and issue a fixing PR? We would really appreciate it.

**Pull request merged**
