### PR TITLE
xml gen should follow json gen behavior

### LINKED ISSUE #4943: XML example not rendered correctly with oneOf
- OS: Windows 10 Pro (64 bit)
 - Browser: Chrome
 - Version: 69.0.3497.100 (Official Build) (64-bit)
 - Method of installation: dist assets
 - Swagger-UI version: 3.19.3
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  description: Test API
  version: v1
  title: Test API
tags:
  - name: Test
    description: Test API
servers:
  - url: /v1
paths:
  /test:
    post:
      tags:
        - Test
      summary: Test endpoint
      description: Test
      operationId: postTest
      responses:
        '200':
          description: Returns response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/test'
            application/xml:
              schema:
                $ref: '#/components/schemas/test'
components:
  schemas:
    test:
      type: object
      properties:
        a: 
          type: string
        b:
          type: integer
        c:
          oneOf: 
            - type: object
            - type: array
            - type: boolean
            - type: integer
            - type: number
```

Swagger-UI configuration options:
```js
SwaggerUI({
    url: 'v1.yaml',
    dom_id: '#swagger-ui-container',
    deepLinking: false,
    presets: [
      SwaggerUIBundle.presets.apis
    ],
    plugins: [],
    docExpansion: "none",
    validatorUrl: null
})
```

### Describe the bug you're encountering
XML schema is not rendered correctly when I use oneOf for one of the model properties. It just display the first element in the generated example and skips the other two. With reference to my example, it skips properties 'b' and 'c'. It displays the example like below:
```
<?xml version="1.0" encoding="UTF-8"?>
<test>
	<a>string</a>
</test>
```
### To reproduce...

1. Go to https://editor.swagger.io/
2. Copy paste the provided spec
3. Click on POST /test endpoint
4. Under Responses, change the Response Content Type/Accept to "application/xml"

### Expected behavior
It must display atleast the first two attributes which has a valid type.
```
<?xml version="1.0" encoding="UTF-8"?>
<test>
	<a>string</a>
        <b>0</b>
</test>
```

### Additional context or thoughts
Unrelated Question:
Is there a way to display property 'c' as well in the response example? I understand that the type can be one of the specified types and cannot be displayed like property 'a' & 'b'. However, I just wanted to make sure that I have not missed anything.

### LINKED ISSUE #6540: XML example not rendered with oneOf, anyOf
- OS: Windows 10 Pro (64 bit)
 - Browser: Chrome
 - Version: 85.0.4183.121
 - Method of installation: online swagger editor
 - Swagger-UI version: online swagger editor
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```
openapi: 3.0.0
info:
  description: Test API
  version: v1
  title: Test API
tags:
  - name: Test
    description: Test API
servers:
  - url: /v1
paths:
  /test:
    post:
      tags:
        - Test
      summary: Test endpoint
      description: Test
      operationId: postTest
      responses:
        '200':
          description: Returns response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/test'
            application/xml:
              schema:
                $ref: '#/components/schemas/test'
components:
  schemas:
    test:
      type: object
      properties:
        a: 
          type: string
        b:
          type: integer
        c:
          type: array
          items:
            $ref: '#/components/schemas/Things'
        d:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/TextObject'
              - $ref: '#/components/schemas/ImageObject'
            
            
    Things:
      type: object
      oneOf:
      - $ref: '#/components/schemas/TextObject'
      - $ref: '#/components/schemas/ImageObject'
            
    TextObject:
      required:
      - data
      type: object
      properties:
        objectType:
          type: string
          example: Text
          xml:
            name: ObjectType
        data:
          type: string
          example: This is a text
          xml:
            name: Data
      description: Contains a text      
      
    ImageObject:
      required:
      - data
      type: object
      properties:
        objectType:
          type: string
          example: image
          xml:
            name: ObjectType
        data:
          type: string
          example: This is a image
          xml:
            name: Data
      description: Contains a image
``` 

### Describe the bug you're encountering
There is an issue with XML rendering when the open api schema contains oneOf, anyOf. 

### To reproduce...

1. Go to 'https://editor.swagger.io/'
2. Paste the Example Swagger/OpenAPI definition.
3. Go to response 200, select media type XML.
4. See that the schemas with oneOf and anyOf are not rendered.

### Expected behavior
Rendering the equivalent XML.  The XML shall be rendered as JSON does, containing every schema from oneOf, anyOf.

### Additional context or thoughts
The issue is described differently in https://github.com/swagger-api/swagger-ui/issues/4943
There is marked as enhancement. I think this is a bug.

### PR DESCRIPTION
**Pull request by mathis-m**
### Description

Merged the JSON and XML gen fns to be generic. And so the logic used is the same. This makes sense since generation does not differ to much.
Introduced exampleOverride so components do not need to care about overriding the `schema.example`.
Move plain js convert to fn.

### Motivation and Context

This is part of #6470 
Fixes #4943 
Fixes #6540

### How Has This Been Tested?

Unit tests have been modified.
Possibility to add unit tests for new override behavior.

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [x] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tim-lai** [comment]
These might be related:
https://github.com/swagger-api/swagger-ui/issues/6540
https://github.com/swagger-api/swagger-ui/issues/4943

**Comment by mathis-m** [comment]
Thanks for the information, will trace this down.

**Comment by mathis-m** [comment]
Fixes #6540 and #4943.

**Comment by tim-lai** [comment]
Thanks for looking at #6540 and #4943. Can you update this PR with tests referencing those two issues?

**Comment by mathis-m** [comment]
Yes, I can add the tests accordingly!
In addition I will write detailed unit tests to test the sample generation function.

**Comment by mathis-m** [comment]
Have added test for #4943 and #6540. Test for the fn.js should be covered with the original [`test/unit/core/plugins/samples/fn.js`](https://github.com/swagger-api/swagger-ui/blob/master/test/unit/core/plugins/samples/fn.js).
Shall the new `overrideExample ` parameter be tested too?

**Comment by mathis-m** [comment]
@tim-lai I think this is ready for a review!

**Comment by tim-lai** [comment]
@mathis-m Merged! Thanks for all the effort to this PR!

**Pull request merged**
