### PR TITLE
fix(ux): ensure that optional security schema is rendered without padlock.

### LINKED ISSUE #6767: Operation should be considered anonymous if its security has one empty object
The [OpenAPI Specification V3](https://swagger.io/specification/#fixed-fields-8) states that for an operation object's `security` field, "To make security optional, an empty security requirement ({}) can be included in the array.".  It is thus reasonable to assume that if the array *only* contains one entry, which is the empty security requirement, the operation should be considered an anonymous/unsecured operation as no security requirements have been specified.  This allows a global security requirement to be specified, but then removed for an operation using a security array containing a single empty object.  This is backed up by the maintainer of Microsoft's OpenAPI.NET: https://github.com/microsoft/OpenAPI.NET/issues/521#issuecomment-748502027

Unfortunately, at the moment, swagger-ui doesn't take this into account.  From https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/operation-summary.jsx :
```
          (!security || !security.count()) ? null :
            <AuthorizeOperationBtn
              isAuthorized={isAuthorized}
              onClick={() => {
                const applicableDefinitions = authSelectors.definitionsForRequirements(security)
                authActions.showDefinitions(applicableDefinitions)
              }}
            />
        }
```
The above code needs an additional check to allow `security.count()` to be 1, and `security[0]` to be the empty JS object `{ }`, which should also result in the operation being marked as anonymous.

### PR DESCRIPTION
**Pull request by mathis-m**
### Description

In case there is a empty security definition included the padlock will not be rendered.

### Motivation and Context

Fixes #6767 

### How Has This Been Tested?

new cypress test

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [x] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by hkosova** [comment]
@mathis-m thanks for the PR!

I would suggest reducing the scope of this PR to just the fix for this specific use case:

```yaml
security:
  - {}
```


The other use case where security is _optional_

```yaml
security:
  - {}
  - apikeyScheme: []
```
probably needs UX/design input before going forward. The reason being, if an endpoint supports security even if it's optional, consumers still need to know that this endpoint is secured. Maybe optional security needs a different lock icon or custom wording or something like that.

cc @tim-lai

**Comment by mathis-m** [comment]
@hkosova for my understanding if a operation contains anonymous access I would not consider this operation as secure.
E.g.:
If you are doing a login and the login does not require any username or password would you consider this as secure?

**Review by tim-lai — CHANGES_REQUESTED** [review]
Let's create a new `/tests/security/anonymous.js` instead of the `tests/bugs/6767.js`. We can still include the ticket number in the description. 

Reasoning: we are going to start deprecating the use of the `/tests/bugs` directory in favor of a more descriptive test filename/structure, so that related test bugs reside close to the test feature(s) itself.

**Comment by mathis-m** [comment]
@tim-lai 
> Let's create a new `/tests/security/anonymous.js` instead of the `tests/bugs/6767.js`. We can still include the ticket number in the description.

done in f353fb6
> Reasoning: we are going to start deprecating the use of the `/tests/bugs` directory in favor of a more descriptive test filename/structure, so that related test bugs reside close to the test feature(s) itself.

good! I think it would be good if this may be stated in [`CONTRIBUTING.md`](https://github.com/swagger-api/.github/blob/master/CONTRIBUTING.md)

**Comment by tim-lai** [comment]
After further consideration, I concur with @hkosova. Let's reduce scope for this PR, to only include a single empty object case. However, we should note in the Cypress test that this is a specific implementation choice, and that it is possible to extend/change in the future.

**Comment by mathis-m** [comment]
> After further consideration, I concur with @hkosova. Let's reduce scope for this PR, to only include a single empty object case. However, we should note in the Cypress test that this is a specific implementation choice, and that it is possible to extend/change in the future.

@tim-lai done

**Review by tim-lai — APPROVED** [review]

**Comment by tim-lai** [comment]
@mathis-m Thanks for the updates! PR is now merged!

**Comment by hkosova** [comment]
@mathis-m I'm a bit late with the answers 😄 but still:

> if a operation contains anonymous access I would not consider this operation as secure.
> E.g.:
> Is a login considered secured if the username and password is optional?

A login operation is probably not a good example for optional security. The most common use case is an operation that returns different amount of data based on anonymous vs authenticated access. Example: GitHub repo listing API, which returns public repos by default vs both public and private when authenticated. Private data is still secured in this case.


> But yes from UX perspective it might make sense to mark it optional.
> I could imagine adding a gray text before the padlock with text "Optional" for that case.

Actually UI already marks optional security differently. Such operations are initially displayed with the black locked icon, which serves as an indicator that "credentials are already provided". There are some more details about this design choice [in this comment](https://github.com/swagger-api/swagger-ui/issues/4402#issuecomment-378269773).

image

**Pull request merged**
