### PR TITLE
feat(auth): Add OpenID Connect Discovery support (#3517)

### LINKED ISSUE #3517: nonce query parameter not sent in case of oidc implicit flow
- swagger-ui version 3.0.17 and 3.1.2

Hello, we are testing swagger ui with authentication on keycloak. When using implicit flow, keycloak returns error because it expects nonce parameter in the query.

As described here: 
http://openid.net/specs/openid-connect-core-1_0.html#ImplicitFlowSteps

nonce is REQUIRED.

I think for the swagger ui it may be any random nonce (no pass our tests we added dummy nonce=1234)

So I think the solution would be to add:

query.push("nonce=" + <anything that matches>)

in

oauth2-authorize.js

in case of implicit flow.

Regards,

Szymon Klimuk

### PR DESCRIPTION
**Pull request by lipnitsk**
### Description
spec/actions.js: Add OIDC metadata fetching

components/auth/oauth2: Add OIDC URL to the Authorization popup

This implementation requires OIDC metadata field `grant_types_supported` to convert to existing oauth2 flows.

Current implementation does not look at OIDC metadata fields other than `grant_types_supported`, `scopes_supported`, `authorization_endpoint`, and `token_endpoint`. `response_type` is still hard-coded in oauth2-authorize.js.

There is currently no support for flows other than the existing oauth2 flows.

Note: CORS must be enabled at the well-known OIDC endpoint for the OIDC metadata to be fetched. A workaround is to download the OIDC metadata via other means and reference it in swagger-ui with a local file relative URL.

### Motivation and Context
Fixes #3517, or at least the OIDC URL processing, not the nonce part (which can be solved with `additionalQueryStringParams`)

### How Has This Been Tested?
Tested with Google OIDC and proprietary OIDC discovery servers.

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [x] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [x] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by lipnitsk** [comment]
@tim-lai is this something you guys are willing to merge? Feedback is welcome. Thanks!

**Comment by julienlavigne** [comment]
Thank you @lipnitsk for your work. This is a great feature, requested for a couple of years. It would be great if a codeowner could pick this up and review indeed! Hopefully that can land in the next release

**Comment by tim-lai** [comment]
@lipnitsk I just wanted to let you know that this PR is under review. There is discussion about OICD. Unfortunately, I also do not have a timeline to provide. Thanks.

**Comment by lipnitsk** [comment]
@tim-lai any updates on the review process? I would like this change to not go stale.

**Comment by tim-lai** [comment]
@lipnitsk PR merged! Thanks for the contribution!

**Pull request merged**
