### PR TITLE
JSON Body Editor

### PR DESCRIPTION
**Pull request by lepinayl**
# Feature proposal: JSON Body Editor

## Related work
This is a proposal to add a JSON editor for body requests in swagger UI.

This work is based on another open source project called [Json-editor](https://github.com/jdorn/json-editor) by [Jeremy Dorn](https://github.com/jdorn).

You will be able to find a demo of Jeremy's editor [here](http://jeremydorn.com/json-editor/) to give you an idea of the potential of this editor.

## Configuration
The editor can be enabled/disabled using the swagger configuration key ```jsonEditor``` :
```javascript
      window.swaggerUi = new SwaggerUi({
        jsonEditor:true
      });
```

The option is currently enabled by default (just because it is more practical for e2e tests).

## Visual preview

This is how it looks like at the moment in a post request:
capture

## Backward compatibility
According to the way swagger now works, Specs 1.2 are now automaticaly converted to 2.0.

So it should work with 1.2 as well but I haven't not tested it yet.

## Current state of the implementation

Please let me know how I could improve both the internal design (code, unit tests, configuration) and external design (css, user experience).

## External dependencies
The following PR have been created on JSONEditor to implement this feature
https://github.com/jdorn/json-editor/pull/461
https://github.com/jdorn/json-editor/pull/456

### CODE REVIEW

**Comment by webron** [comment]
@lepinayl - First allow me to apologize for the delayed reply.

Thank you for the work you've put into it. It's obvious you've put a lot of thought and effort into it.

As you referenced from #1083, this can very well be a solution here. This is probably one of the more requested features that we'd like to support.

In the last release of swagger-ui, we've introduced some major refactoring which is probably why this PR cannot be automatically merged now.

Before we decide to move on - would you be willing to take the time and make the required changes? We can review the current PR to see it covers what's needed before you make the effort.

If you're willing, I can play with your fork/branch to get a sense of what it does, and we can discuss possible changes if needed. I suspect there are going to be a few edge cases, at least when it comes to composition/inheritance. 

Please let me know how you'd like to proceed.

**Comment by webron** [comment]
Forgot to mention - the way the UI now works, older Swagger versions are converted to 2.0 prior to rendering, so I assume the editor would now work for 1.2 as well.

**Comment by lepinayl** [comment]
@webron PR is fixed now, it was due to JSHint. I like your suggestion about playing around with this PR and letting me know of the possible changes. As you will see I've not done too much effort in term of UI/UX because I thought it would better to discuss about it instead of making arbitrary choices.

**Comment by webron** [comment]
Thanks. I'll try spending some time playing with it and give you feedback. 

Is there anything specific you had in mind regarding the UX that you wanted feedback for? Or generally discuss?

**Comment by lepinayl** [comment]
Yes for UX it was more about general discussion, I don't have anything specific in mind.

**Comment by webron** [comment]
Again, sorry for the delayed reply.

This is a great contribution and would probably please many of our users.

I've played with your branch, and here are the comments I have so far (based on the pet store):
- Whenever there's an object, there's the `object properties` button. Is it possible to remove that entirely? If not, is there a way to not permit adding additional properties?
- I like the `Edit JSON` button, but worried that it also allows adding properties. Not sure if/how that can be disabled (even if not in the JSON content, at least in the display). We may want to keep this option though to allow negative tests, but I'd still like to remove the option to add additional properties as stated in the previous bullet.
- For the `collapse`/`expand`, it would be nice if there was an icon before the property name instead. Something like: 
expand
- There's something inconsistent with the `required` behavior. Looking at the `Pet` model `id, `name` and `status` are all bold which I assume means they're required, even though `status` is not marked as required. For the referenced models, `Tag` and `Category`, even though none are marked as required, they all appear in bold. 
- For `status`, since it is not required and is marked as an enum, the drop down needs to have an empty value so that no value is sent.
- Would it be possible to set customized data entry for additional `format`s? For example, a date picker for `date`, asterisks for `password` and so on?
- Is it possible to apply additional validations for the fields (such is min/max length, min/max value)?
- Is there a way to use it to render simple forms for primitives as well and not JSON only? If the validation options and such are available, and could be applied on primitive fields as well (for non-body parameters), it could help us solve another issue.
- Is there support for `additionalProperties` as well? We need to add support for maps.

We probably need to test it with a few more samples, but I think it's a really good start.

**Comment by lepinay** [comment]
@webron thanks for the useful feedback, I'll post my progress on the items on your list starting next week and see how it goes.

**Comment by webron** [comment]
@lepinay - great! Would love to get it integrated before the final release of 2.1.

**Comment by lepinay** [comment]
A little heads up:

First two points on your list are done, but not merged yet in this PR.

For the Expand/Collapse, it will looks like this:

expand

Using a proper icon image as you suggested would require a bit more customization work (I can't get rid of the button tag in the html, so I will have to re-skin the entire button using css to make it looks like not a button). Otherwise, another thing that could be done to make it prettier would be to use a font icon for the +/- icon instead of text.

Bold text seems to be used regardless of the property being required or not. It's just a styling choice, we could remove the bold style if you think it's misleading.

For status, I'll have to investigate a little more but It seems this case is not handled in JSONEditor so I'll probably raise an issue in JSONEditor project.

JSON Editor uses HTML5 input types, so the following format are supported:
color date datetime datetime-local email month number password range tel
timeurl week...so some of these may render as basic text input in older browsers.

min/max validation are supported out of the box, it's also possible to add custom validators.

Could you point me out to what additionalProperties are ?

**Comment by webron** [comment]
Again, thanks for all the extra work you put into this.

As for the +/-, it's nice to have and we could merge it even if it'd still require some tweaking.

Bold text - do you any idea then how it decides whether it's regular or bold? To users, this may be confusing. We do need some indication on whether the field is required or not.

The status issue (no empty value when a field is not required) is a blocker unfortunately, since we don't want people to input a non-mandatory field.

No problem with HTML5 input types.

Great to hear regarding the validators.

`additionalProperties` (not yet supported, but should be added soon) is a way to allow users to input maps of properties that are not predefined. The type is determined by it.

```js
"additionalProperties" : { "type" : "string" }
```

allows the user to add new keys with a string value:

```js
{
  "hello": "world",
  "foo": "bar"
}
```
even if "hello" and "foo" are not explicitly defined.

If you have a more complex definition such as:
```js
"additionalPropertoes": { "$ref": "#/definitions/Model" }
```
Then the input would allow you to generate additional keys, where the value is the structure of the model.

**Comment by lepinay** [comment]
It has been a while since I've worked on this because I couldn't find enough time and it was trickier than what I thought but I made some good progress:

**This is not yet in the current PR** but here what it looks like now with the requested features

capture

For required field I now generate a new css class on the labels (.required), that way users will be able to customize this. Default css is bold font for required and normal for not required.

For drop downs, we now have an empty choice for non required fields (see the status drop down).

This will need more testing as I had to modify JSONEditor in quite a few places to get it working...but it's getting there.

I'll do a bit more testing before updating the PR.

**Comment by webron** [comment]
Thanks for the update, @lepinay! Just bear in mind that the rebase is going to be tricky as quite a few things have changed. Might want to prepare yourself mentally for it ;)

**Comment by lepinay** [comment]
@webron I think this PR is ready for another round of testing/feedback

**Comment by schickling** [comment]
+1

**Comment by apfrod** [comment]
I've been trying out this branch and have an issue with using refs to definitions of anything but objects:
```yaml
swagger: '2.0'
paths:
  /example:
    post:
      parameters:
        - name: parameters
          in: body
          schema:
            type: object
            properties:
              simple_string:
                type: string
              defined_string:
                $ref: '#/definitions/defined_string'
    responses:
      200:
definitions:
  defined_string:
    type: string
```
The two properties appear as expected in the Model Schema view, but the JSON Editor only shows an empty object. Inspecting the model.schema passed at this point I see definitions.defined_string.type = "object" where it should be "string" but I can't work out how it gets to this state.

**Comment by lepinay** [comment]
@apfrod just noticed I need first to fix the merge conflicts then I'll try investigate.

Meanwhile could you provide the corresponding json schema or make your sample work in http://editor.swagger.io/ ? I'm not used to yaml and there is a syntax error I can't figure out.

**Comment by apfrod** [comment]
@lepinay sorry, yes, editor.swagger.io seems to be less forgiving. I also notice it doesn't show defined_string type either.

```yaml
swagger: '2.0'
info:
  title: example
  version: 0.0.0
paths:
  /example:
    post:
      parameters:
        - name: parameters
          in: body
          schema:
            type: object
            properties:
              simple_string:
                type: string
              defined_string:
                $ref: '#/definitions/defined_string'
      responses:
        default:
          description: OK
definitions:
  defined_string:
    type: string
```

```json
{
  "swagger": "2.0",
  "info": {
    "title": "example",
    "version": "0.0.0"
  },
  "paths": {
    "/example": {
      "post": {
        "parameters": [
          {
            "name": "parameters",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "simple_string": {
                  "type": "string"
                },
                "defined_string": {
                  "$ref": "#/definitions/defined_string"
                }
              }
            }
          }
        ],
        "responses": {
          "default": {
            "description": "OK"
          }
        }
      }
    }
  },
  "definitions": {
    "defined_string": {
      "type": "string"
    }
  }
}
```

**Comment by lepinay** [comment]
this is going to take me longer that I've thought because the PR process has changed, I'll need to create a new one and submit on master instead of develop_2.0.

@webron two quick questions: Are you still considering this feature for merging and could you confirm that submit my PR directly into master (the https://github.com/swagger-api/swagger-ui/blob/master/CONTRIBUTING.md doesn't seem up to date regarding this).

Bonus question: Is there a magical git command to "repurpose" my PR from develop_2.0 to master or will I have to re-apply all my modifications manually on master  ?

**Comment by webron** [comment]
@lepinay - yeah, I'd still love to be able to merge this PR. As you understand, it's a big change so we need to be careful here (btw, did you add a toggle parameter to be able to use the editor or the classic version based on the user preference?).

I don't see anything in https://github.com/swagger-api/swagger-ui/blob/master/CONTRIBUTING.md that's not up to date?

As for git - this is a bit more about github in this case. I don't think you can change the PR itself to be merged with another branch. However, you don't need to re-apply all your modifications manually on master either.

In your local clone of the fork, sync your `JSONEditor` branch with the `master` branch of this repository. Resolve any conflicts that may arise and sync back to your own github fork. From there create a new PR against master, and you're done. The syncing is pretty much the same as you'd rebase from any other branch.

**Comment by lepinay** [comment]
@webron yes there's a feature toggle, it works like that:

```javascript
      window.swaggerUi = new SwaggerUi({
        jsonEditor:true
      });
```

About https://github.com/swagger-api/swagger-ui/blob/master/CONTRIBUTING.md, it's nothing really, I'd have thought it would mention that the PR should be made against the master branch and not the develop_2.0 anymore...so I wasn't real sure about it.

Thanks for the git tip, I'll do that.

**Comment by gbjk** [comment]
@lepinay I have a fix for the @apfrod issue. I'll PR it to you shortly.

**Comment by lepinayl** [comment]
I'm closing this in favor of https://github.com/swagger-api/swagger-ui/pull/1589

**Pull request closed without merging**
