### PR TITLE
Added flexible scope separator

### PR DESCRIPTION
**Pull request by sonicd300**

### CODE REVIEW

**Comment by valiksb** [comment]
changes look fine, can some run gulp create so it generates a new 'dist' and then we can copy the changed libs into https://github.com/zatar-iot/apps-api-console

**Comment by valiksb** [comment]
approve

**Comment by valiksb** [comment]
this PR is not in our fork, please delete

**Comment by webron** [comment]
@sonicd300 - a few things:

1. Does this solve an existing issue? If so, what's the issue #?
2. If not, what does this PR do? The title doesn't really say much.
3. PRs need to be submitted against the develop_2.0 branch, not master, so please resubmit.

**Comment by fehguy** [comment]
This has been merged via https://github.com/swagger-api/swagger-ui/commit/83afb5b2778031c64298d127f3e78e6cc4a686c6 to develop_2.0

**Pull request closed without merging**
