### PR TITLE
#1892 infinite loop when rendering self-references

### PR DESCRIPTION
**Pull request by bodnia**
Fixed

### CODE REVIEW

**Comment by bodnia** [comment]
@Cwallice fixed https://github.com/bodnia/swagger-ui/commit/db328351b9b85eb983f7ffe06c182cd81fb91446

**Comment by fehguy** [comment]
I'm seeing a regression in rendering the responses in XML.  For the spec below, I'm seeing the element names missing in the response section:

image

**Comment by fehguy** [comment]
@bodnia it also seems like the shebang is having troubles still.  Please see image below, clicking the collapse on an operation clears the whole path

shebang

**Comment by fehguy** [comment]
@bodnia I've merged this since the issue above was present before, and this fixes the recursion loop.

**Comment by bodnia** [comment]
@fehguy As per https://github.com/swagger-api/swagger-ui/pull/1902#issuecomment-174090655 it works exactly as on http://petstore.swagger.io/#/
Should this behaviour be changed?

**Comment by fehguy** [comment]
master is behaving now, but I did make a change in the commit: https://github.com/swagger-api/swagger-ui/commit/48ad6793f7c0480212bdde1c3b23ca230c04dd2d

**Pull request merged**
