### PR TITLE
RandExp failure should not cause UI to completely fail

### LINKED ISSUE #7891: Query parameter with case-insensitive RegExp search fails
### Q&A (please complete the following information)
 - OS: Windows 10 x64
 - Browser: Chrome 98.0.4758.102 (Official Build) (64-bit), Edge 98.0.1108.62 (Official build) (64-bit)
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: 3.52.1
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

When having a case-insensitive regular expression for a query parameter, Swagger reports a console error about invalid RegExp group and fails to send the call to the API, but the same code as a route/path parameter works fine without error.

The query parameter I am using is a required query parameter and I have tried toggling the required tag to make it optional, but get the same error.
This was happening with the underlying API was running .NET Core 3.1 (LTS) which has now been updated to .NET 6 (LTS) and the issue has persisted after the update.
The API uses the NuGet package `"Swashbuckle.AspNetCore" Version="6.2.3"`

It appears as if some logic that parses case-insensitive regular expressions is different between the route/path and query parameter types.

*EDIT 2022-03-24* I can create the same console error with a route parameter so it doesn't appear to be specific to query parameters.

### Code setup (from swagger.json)
When the "in" is "query" the call fails/hangs:
```"/protected/something": {
   "put": {
      "tags": [
         "Protected"
      ],
      "summary": "Test Something",
      "description": "A protected endpoint",
      "parameters": [
         {
            "name": "action",
            "in": "query",
            "required": true,
            "schema": {
               "pattern": "(?i)(ADD|REMOVE)",
               "type": "string"
            }
         }
      ]
   }
}
```

When the "in" is "path" the call is successful:
```"/protected/something": {
   "put": {
      "tags": [
         "Protected"
      ],
      "summary": "Test Something",
      "description": "A protected endpoint",
      "parameters": [
         {
            "name": "action",
            "in": "path",
            "required": true,
            "schema": {
               "pattern": "(?i)(ADD|REMOVE)",
               "type": "string"
            }
         }
      ]
   }
}
```

### Expected behavior
Able to have a case-insensitive query parameter and submit a call to the API from Swagger UI.

### Screenshots
image

### PR DESCRIPTION
**Pull request by soundstripe**
Regular expression syntax varies across languages. Currently the Swagger UI breaks out of the box if a regexp validator unknown to JS is used.

### Description
This fix wraps the sample generator in a try/catch and simply returns "string" (the normal default) when an unknown syntax is encountered.

### Motivation and Context
Fixes #7891

### How Has This Been Tested?
I've run this locally against the openapi.json that includes my non-js-compatible regex expressions

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tim-lai** [comment]
@soundstripe Thanks for the PR! It looks good to me. Can you select the option to "Allow edits from  maintainers", so that you don't have to keep rebasing with latest?

**Comment by soundstripe** [comment]
I made this change in a fork owned by my organization and I don't have that option.

**Comment by tim-lai** [comment]
> I made this change in a fork owned by my organization and I don't have that option. Should I merge or rebase?

Rebase please

**Comment by tim-lai** [comment]
@soundstripe PR merged! Thanks for the fix and contribution!

**Pull request merged**
