### PR TITLE
Fix/translator

### PR DESCRIPTION
**Pull request by ponelat**
Translator didn't have any [data-sw-translate] attributes in the templates, nor was it included in the build.

I've put in commented out includes in the index.html file, so that all one needs to do is uncomment and the translations will take place.

### CODE REVIEW

**Comment by franciscocpg** [comment]
@ponelat, I have forked **ponelat:fix/translator** and used **Simple Locale Switcher** addon for firefox to change firefox language to russian.
But still not translating. 
What is the trick to translate?

**Comment by ponelat** [comment]
@franciscocpg 
I'm not sure how Simple Local Switcher works, but to enable translations with this (very simple mind you) translator, just uncomment the lines at the top of `dist/index.html`

**Comment by franciscocpg** [comment]
Hello @ponelat.
I think I might not be clear with my question. 
I have uncomment the mentioned lines.
My point is: What is the trigger to activate localization? Browser locale? Or system locale?

For example, the code below always shows the page translated to russian:
```html
   <script src='lang/translator.js' type='text/javascript'></script> 
   <script src='lang/ru.js' type='text/javascript'></script> 
```
And the code below, always give me in english (Even if I changed the browser locale using Simple Local Switcher for example)
```html
   <script src='lang/translator.js' type='text/javascript'></script> 
   <script src='lang/ru.js' type='text/javascript'></script> 
   <script src='lang/en.js' type='text/javascript'></script> 
```

**Comment by franciscocpg** [comment]
I think I understand now, if I changed the code 
```html
   <script src='lang/translator.js' type='text/javascript'></script> 
   <script src='lang/en.js' type='text/javascript'></script> 
   <script src='lang/ru.js' type='text/javascript'></script> 
```
It's always in russian. 
So it's not a multi language enviroment, am I correct?

**Comment by ponelat** [comment]
@franciscocpg yes, although I imagine it wouldn't be hard to implement a selectbox to change the language... might be a good PR ;)

**Comment by franciscocpg** [comment]
Yes @ponelat.
I'll try this ASAP.

**Comment by skhwang** [comment]
Hi, @ponelat! I see that some headings and table headers are missing [data-sw-translate] attributes in `operation.handlebars` file in **ponelat:fix/translator**. Is this intended?

**Pull request merged**
