### PR TITLE
508 fixes

### PR DESCRIPTION
**Pull request by bdkosher**
Addresses #1021 mostly by adding label tags, generating unique element ids as needed.

In the process, moved the label text that gets set in the ___ContentTypeView.js files to the respective handlebar templates; the text was static as far as I could tell.

There are additional minor 508 improvements that can be made with the tables (scope tags, header attributes)

### CODE REVIEW

**Comment by fehguy** [comment]
@mohsen1 is this good to merge?

**Comment by mohsen1** [comment]
I don't exactly understand why we're doing this but if it's necessary to have unique identifiers it works for me.

**Comment by bdkosher** [comment]
The ids have to be unique per the HTML specification--and the label tags which reference them are there primarily to appease US Federal Government agencies wanting to use Swagger UI.

**Comment by fehguy** [comment]
Hi, it looks like we have some merge issues.  Can you please rebase?

**Comment by bdkosher** [comment]
Merge conflicts are gone, but dist/index.html isn't rendering successfully for me ("Uncaught TypeError: undefined is not a function" JS error). Investigating.

**Comment by bdkosher** [comment]
After acknowledging how terribly I've screwed up my branch through my git naivete and witnessing the reemergence of merge conflicts, I thought I'd start over: reapply the 508 fixes on top of a fresh copy of the develop_2.0 branch HEAD and make a new pull request. 

But before I even apply any changes, I find I'm still getting that JS error on render. Please tell me it's not just me with this problem.

**Comment by bdkosher** [comment]
Please close this one that I've botched. I've submitted a new PR: https://github.com/swagger-api/swagger-ui/pull/1291

**Comment by fehguy** [comment]
sure thing

**Pull request closed without merging**
