### PR TITLE
Add cookie support

### PR DESCRIPTION
**Pull request by mohsen1**
screen shot 2015-03-06 at 4 05 22 pm
AJAX calls will sen document cookies. This is an interface for updating
document cookies.

### CODE REVIEW

**Comment by fehguy** [comment]
@mohsen1 I thought that cookie values would be passed in the parameters section.  Is that not possible?

**Comment by mohsen1** [comment]
That's the limit of XHR. You should set `withCredentials` to `true` but that's all the control you have 

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest

**Comment by fehguy** [comment]
My question isn't about the technical implementation, rather the UI.  I would suggest that the UI _not_ change, and swagger-js handles setting the document.cookies internally.  You should simply render the UI fields for cookie support as normal input boxes.

**Comment by mohsen1** [comment]
Two questions:

* Should we render a cookie input field for every operation?
* What is the api in SwaggerJS for updating the cookie?

**Comment by fehguy** [comment]
1) no, we should use "in": "cookie" to decide if we should render an input box for cookie support (i'm not sure if it's in the spec, but we should support it anyway).  Most people will simply be using swagger.authorizations to set cookies, with the enhancement in https://github.com/swagger-api/swagger-js/issues/282

2) swagger.authorizations will set cookies at the global level, and sending the values like any other operation (query, path, header, etc) should set the cookies.  So no special API.  Treat it like any other input.

**Comment by webron** [comment]
"in": "cookie" is indeed not in the spec. whether we support it or not is up to you.

**Comment by mohsen1** [comment]
If `in: cookie` is not supported in 2.0 specs, shouldn't we move this and related issues to [Future](https://github.com/swagger-api/swagger-ui/labels/Feature)?

**Comment by cemo** [comment]
It would be awesome to support Cookie. We are using cookie for our services and having support in the first place would be great. Please add cookie support. :(

**Comment by hongxingli** [comment]
second cemo, we need cookie support badly since we use session in cookie

**Comment by hongxingli** [comment]
hi Mohsen,
I got the latest code from develop_2.0 branch, but after I launch the UI, I did not see the cookie option, what else do I need to do?
Thanks,
Hongxing

**Comment by earth2marsh** [comment]
Agree that if `in: cookie` is not in the spec, that we should push this to future when it is there. 

Whether that should be in the spec is a different question, and an issue should be opened on the swagger-spec project.

While I appreciate that there may be many services today that use cookies, I see a number of disadvantages to using cookies with APIs. I'll try to avoid hijacking this thread more than I already have, but I'm interested in understanding the use cases for cookie-based APIs (will join spec issue discussion).

**Comment by webron** [comment]
@earth2marsh - for your viewing pleasure (well, and participation of course) :)
https://github.com/swagger-api/swagger-spec/issues/161
https://github.com/swagger-api/swagger-spec/issues/15

**Pull request closed without merging**
