### PR TITLE
Run Handlebars within Gulp instead of NPM

### PR DESCRIPTION
**Pull request by vincent-zurczak**
Hi!

First, thanks for this project. It is very convenient. :+1: 
Trying to tweak it a little bit, I have been a little bit confused by the fact sources written by hand are mixed with generated sources. This applies in particular to the **templates.js** file, which is in fact generated by Handelbars from the templates.

And what a pity to have to run Handlebars by hand or through NPM.
This pull request moves Handlebars generation from NPM into Gulp. The main advantage is that you can now directly edit Handlebars templates and see the application being live updated. We thus benefit from both Gulp watch process and Handlebars generation.

Distribution builds keep on working as previously.
The Handlebars thing just moved from NPM to Gulp.

### CODE REVIEW

**Comment by vincent-zurczak** [comment]
Hello. :)

Is it worth for me to update my PR to ease merging?
Or would it be a waste of time?

**Comment by linxiaowu66** [comment]
if you do this modification, why do you use the gulp-handlebars ?  this plugin maybe more simple to implement your target.

**Comment by vincent-zurczak** [comment]
Hi,

We need Handlebars somewhere. Moving it from NPM (`npm run handlebars`) to the Gulp build (`npm run serve`) allows to hide the generation when editing templates. And we thus do not need to maintain the generated templates in the source code. It is directly generated under another source directory.

**Comment by linxiaowu66** [comment]
Hi, @vincent-zurczak 
Yes, I get your idea. Using the **gulp-handlebars** plugin is also can archive your target, so I think your implementation is just more complex. I has forked this project and using gulp to maintain the generated templates instead of NPM, so our targets is the same but the implementaion process.

If you has interested in my implementation(**I almostly rewrite the gulp file**), I can share the code with you.

Thanks.

**Comment by webron** [comment]
Apologies for the (very) delayed feedback.

Unfortunately, our code base might have deviated from the time this PR was submitted, and we cannot easily merge it (certainly not against `master`), and so, we're going to close this PR.

If you find the change important and would like to resubmit it, please let us know. Be aware that we are focused on the 3.X version at the moment (now `master`), and new changes should be applied to it.

We appreciate the time you've taken into submitting this PR. We're now making extra effort to review PRs within a few days at most, to avoid situations like this.

**Pull request closed without merging**
