### PR TITLE
Feature jsonbodyeditor

### PR DESCRIPTION
**Pull request by HughePaul**
A JSON document editor, as an alternative to the textarea for JSON body text.
This builds drop-downs, text fields, array editors etc based on the supplied body parameter model, and any sub-models they reference.
It converts between the text area and the editable JSON document, which are on two tabs
The document editor view is only triggered for a body parameter that has a swagger model.

### CODE REVIEW

**Comment by romain-dartigues** [comment]
Hi @fehguy,

sorry to bother, but what is the status of this feature?
Since it has been closed, does it mean it is somehow fixed somewhere?
I tried with 6f1b9b6 of 2015-04-28 and it seems the problem (well described in noirbizarre/flask-restplus#11) persist.

Regards.

**Comment by webron** [comment]
@romain-dartigues - we're looking into integrating #1083. Unfortunately, I'm a bit slow :-/

**Comment by romain-dartigues** [comment]
Thank you @webron, it unclear to me if some work was in progress since the pull-request was closed. ;^)

**Comment by mJaiswal** [comment]
Great ! I am going to use this feature. At work we are creating new APIs and we are using swagger !

**Pull request closed without merging**
