### PR TITLE
Add configuration to hide responses container

### PR DESCRIPTION
**Pull request by ctruzzi**
This Feature Pull Request is in regards to #1722 

The code copies the functionality of show/hide for `operations.jsx` and `operation.jsx`. It uses a new config option in the `SwaggerUIBundle` of `responseExpansion: 'none'` 

What this PR is supposed to do:
1. Adds a swagger configuration value for displaying or hiding responses by default.
1. Adds ID's to response divs so that we can use the existing `layoutSelectors` and `layoutActions` to hide and display this area of the swagger UI
1. Stop clickable propagation when clicking inside the `<label>` of ContentType if it exists.

### CODE REVIEW

**Comment by ctruzzi** [comment]
Not certain who to attach to the PR so calling out @webron

**Comment by shockey** [comment]
Note for anyone that wants to review the code, https://github.com/swagger-api/swagger-ui/pull/3604/files?w=1 will let you view the diff without whitespace changes included. Makes it easier to see what's changed.

**Comment by webron** [comment]
Not a big fan of the functionality, but not ready to rule it out yet. A few comments:

- Since there's a new configuration option, it needs to be documented in the README.
- The default value should be to _show_ the responses, not hide.
- There should be a visual indicator that the section is collapsed and can be expanded. Right now it's guesswork.

**Comment by ctruzzi** [comment]
@webron While I can understand that some might not be interested in this feature; one option would be to set the default to `not clickable` so that we have three configuration options
1. `disabled`
2. `none`
3.  `full`

Currently the default is `full` like TagExpansion, I can change this to `disabled` and have the config updated in the README.

Visual indicator would be a good idea, for now I can change the cursor icon like is done for API Paths.

**Comment by ctruzzi** [comment]
@webron The PR has been updated.
1. Default config is equivalent to the current implementation. No expansion is possible and responses are always shown.
1. 'full' and 'none' configuration options exist which result in a clickable header that turns the curser into pointer
1. A new CSS class is added for `opblock-section-header` of `opblock-section-header-clickable` since that CSS class is used for other header blocks.
1. README.md updated to explain how the config can be used.

**Comment by webron** [comment]
@ctruzzi - Given it another run, and:
- The default doesn't seem to be `full`.
- `null` value doesn't seem to do anything.
- The cursor doesn't seem to change to a hand 😕 
- I'm still trying to understand why this functionality is needed. I'd argue if this section should be collapsable, all sections should be collapsable.

**Comment by shockey** [comment]
@ctruzzi, do you expect to have the time to address the concerns @webron mentioned?

**Comment by ctruzzi** [comment]
Sorry have been away for some time. Will try and resolve conflicts and make the changes webron suggested. 

One of the reasons I'd like this is a lot of our API end points have ~7 or so responses (different error codes). Having them all open by default bloats the page a huge amount.

**Comment by shockey** [comment]
Closing due to inactivity - @ctruzzi, if you're still interested in getting this feature across the line, let me know and I'll reopen this!

**Pull request closed without merging**
