### PR TITLE
Add support for requestInterceptor / responseInterceptor.

### LINKED ISSUE #2872: What happened to requestInterceptor?
did `requestInterceptor` get renamed or is it gone completely? I depend on this to handle "try it out" requests for APIs on multiple hosts.

### PR DESCRIPTION
**Pull request by gilbode**
resolves #2872 - adds back support for requestInterceptor / responseInterceptor.

### CODE REVIEW

**Comment by gilbode** [comment]
@shockey - FWIW, I think this was the same behavior in 2.x where the request interceptors mutations were not visible to the UI.  In our case we use requestInterceptor to send requests through a proxy so we rewrite the URL and add some extra headers so we consider them not showing up in the UI a feature and not a bug.  That said, I see your point and will have another look.

**Comment by shockey** [comment]
@gilbode yeah that does go beyond parity, but I do think it best that the UI displays _exactly_ what the browser sent, so the cURL can reproduce the request even with interceptors enabled.

Thanks for the extra effort on this! :smile:

**Comment by shockey** [comment]
If you rely on interceptor transparency as a feature, maybe a switch for this would be good. Something like `showMutatedRequest` - @webron, what do you think?

**Comment by gilbode** [comment]
OK, I've updated the pull request to display the mutated request in the curl output and put it behind the showMutatedRequest flag suggested by @shockey.  Also added tests and documentation in README.  Let me know what you think.

**Comment by webron** [comment]
If you find such a flag to be useful, then sure.

For the sake of documentation - in 2.x the curl generation was done in swagger-js, but in 3.x the generation has moved to swagger-ui (as did some other functionality). That should explain why the functionality should be slightly different as well.

**Comment by shockey** [comment]
Just tested these changes - all the new options appear to work well.

Thanks @gilbode! This feature will be available as part of our release tomorrow evening 🎉

**Pull request merged**
