### PR TITLE
Preset with react lowlight

### PR DESCRIPTION
**Pull request by biggates**
Syntax highlighting (#3189) using react-lowlight

### CODE REVIEW

**Comment by shockey** [comment]
I'm going back and forth on the best way to implement this (core vs coreplugin vs outside plugin).

Before moving forward, I'd like to hear what @webron thinks of the functionality. Specifically, should this replace whats there currently, or be an opt-in change?

It also comes to mind that I and others on the team have been musing about creating an boilerplate plugin that lives in its own npm repository, that can be imported cleanly... This PR has enough meat in it to be a good candidate for that.

**Comment by shockey** [comment]
Thanks for the contribution, @biggates - I appreciate your attention to detail with the documentation, and wiring everything through.

Please bear with us while we look at our side of things 😄

**Comment by ponelat** [comment]
Yeah I agree with @shockey this is a perfect candidate for a standalone plugin ( ie: outside this repo ).
Any thoughts on how to make that possible?

- on npm with`swagger-ui-plugin-lowlight`? 
- What about `<script/>` tags? Would we support those? ( which means plugins would need to follow a building guidelines ).
- you mentioned a boiler plate, should we make a `create-react-app`-like creator? That handles webpack? Too much?

@biggates, thanks again for the contribution!

**Comment by shockey** [comment]
I'm going to go ahead and close this out.

@biggates - thanks a lot for this. I'm not against the change in itself, but since this is structured as a new preset, I think it'd do best as a preset/plugin that lives outside of the core codebase. For an example on how to build such a thing, see https://github.com/shockey/swagger-ui-cornify. Feel free to ping me over there if you have any questions.

That being said... we aren't married to our current code highlighter. If you'd like to take another swing at this, I'd be happy to consider a PR that replaces the current code highlighter with a superior one - the deal with this one is that it lives in a weird space between plugins and core. But that's not your fault, we need to push out more guidance on how to build plugins!

Thanks again 👍

**Comment by flying-sheep** [comment]
so where does this live now?

**Comment by shockey** [comment]
@flying-sheep AFAIK, the code was never repackaged in any of the ways noted above. Feel free to pick it up yourself if you have the time 😄

**Comment by flying-sheep** [comment]
too bad, such a good PR and nothing coming out of it…

maybe I will. where would i start? is there a plugin that does sth. similar (i guess overriding the rendering of some component…?)

**Pull request closed without merging**
