### PR TITLE
swagger_empty_responses_fix

### PR DESCRIPTION
**Pull request by VasylZalizetskiy**
We have a error when responses is not described in json file for some operation. 
So I think we can create an empty OrderedMap to prevent this bug.

### CODE REVIEW

**Comment by webron** [comment]
@VasylZalizetskiy thanks for the contribution. Do you have a sample spec that reproduces the issue? Or if it's not just in the spec but the try it out functionality, can you explain the issue a bit more? I'd like to be able to test the functionality before and after the change.

**Comment by VasylZalizetskiy** [comment]
if we doesn't have a responses from server in the spec for someone operation we have a error when i pressed Execute button.. please check with this spec. [swagger.txt](https://github.com/swagger-api/swagger-ui/files/1087547/swagger.txt) This is your Petstore spec, but i just remove responses for first post operation. In my work project missing responses is usual situation. If you apply my little fix this situation looks normal. 
Screenshots before fix:
image
image
Situation after fix...
image
image

**Comment by webron** [comment]
Thanks for the explanation, @VasylZalizetskiy.

If you look at the spec, you'll see that [`responses`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operationResponses) is a *required* field and that the [Responses Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responsesObject) *requires* you to have at least one response defined.

That means that the description you shared with us, and your own API descriptions, are not valid specs and need to be fixed. I agree that the error that's being thrown by swagger-ui should be nicer, but the fix is not by allowing invalid API definitions.

**Comment by VasylZalizetskiy** [comment]
@webron roger that. Thank you for your response.

**Comment by webron** [comment]
@VasylZalizetskiy I'm sure you understand why we can't accept the PR in this case. We do appreciate the effort you've put into it, and would love to see future PRs from you that improve the product for your needs and the community's.

**Pull request closed without merging**
