### PR TITLE
Restore "Request URL" in live response section

### PR DESCRIPTION
**Pull request by dalbani**
I found the "request URL" section quite useful in Swagger UI v2, for example to replicate the request in a another browser tab or any other tool. (Evidently, that only works for GET requests.)
This is my proposal to restore this functionality in Swagger UI v3.
In terms of implementation, I wasn't sure if an `<a>` or `<pre>` was more appropriate — or even a `<textarea>` with auto copy-paste as for the Curl section.

### CODE REVIEW

**Comment by webron** [comment]
Wouldn't that be equivalent to just copying the request URL from the `curl` sample?

**Comment by dalbani** [comment]
@webron: yes, sure, this additional section is only there to make _easier_ to copy the URL.
In practice, that's the difference between finding the URL within `curl -X GET "http://petstore.swagger.io/v2/pet/22" -H "accept: application/xml"` or simply copy from a section containing `http://petstore.swagger.io/v2/pet/22` only.

**Comment by shockey** [comment]
I made some changes:

- Removed `RequestUrl` component...
  - "Request" URL seemed like a misnomer, since the URL is actually gleaned from the response. But I'm ok with keeping that for backwards compatibility expectations... @webron feel free to override this. The only edge case I can think of where the URL would differ between request and response, is following a `Location` header.
  - A new component seemed like overkill for an h4 + textarea, when we have an even bigger section inlined in the commponent below. Not saying breaking it off was a bad idea.. just that it's good to be consistent with what gets its own component.
- The URL display now triggers based on `url` being available, instead of `curlRequest`.

**Comment by shockey** [comment]
I'm approving the code here, leaving the feature up to @webron. The request vs response naming here should not be overlooked before merging.

**Comment by webron** [comment]
@shockey request url is correct in this case. I'm ok with merging it, even though not a huge fan.

**Pull request merged**
