### PR TITLE
Added support for oauth2 accessCode flow and fixed auth issues with 2.0 spec implementation

### PR DESCRIPTION
**Pull request by bshamblen**
I have verified that everything works with both implicit and accessCode flow methods. I also tested both a 1.2 and 2.0 swagger doc. If you have any existing methods for regression testing the security features please let me know and I'll be happy to fully test everything. 

I also fixed a few minor UI issues with the auth popup dialog.

### CODE REVIEW

**Comment by webron** [comment]
@bshamblen - if Tony merges this, you may get a :cookie:.

**Comment by fehguy** [comment]
i love giving out cookies.  Let me review soon and see if it can be merged.

**Comment by fehguy** [comment]
I should get this reviewed today or this weekend

**Comment by fehguy** [comment]
@bshamblen same as my last comment.  I can copy the code from your PR but I'd like to keep it associated with your commit.  If you can resend, I'll get into it.

**Pull request closed without merging**
