### PR TITLE
Show loading message when we are loading

### PR DESCRIPTION
**Pull request by heldersepu**
### Description
The message `No spec provided` was flashing while remote API definition loads

### Motivation and Context
See Issue #3900

### How Has This Been Tested?
The test is simple in your dev environment change the index.html to match:
https://github.com/swagger-api/swagger-ui/issues/3896#issuecomment-343915933

### Types of changes

- [ ] No code changes (changes to documentation, CI, metadata, etc)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by webron** [comment]
@heldersepu Thanks for the PR. We have a `Loading` throbber that's used when executing API calls. I think it would make more sense to use it here as well, instead of just the text. Thoughts?

**Comment by heldersepu** [comment]
Let there be throbbers!

**Comment by shockey** [comment]
I made a handful of tweaks:
- Updated `StandaloneLayout` to match the `BaseLayout` changes
- Wrapped the `BaseLayout` changes in `.swagger-ui .layout-container` to make sure the relevant CSS is always applied
- Centered the messages, it looks nicer than being on the left edge of the viewport
- Changed "Spec" to "API definition" in a couple of user-facing loading error messages

LGTM!

**Comment by shockey** [comment]
Thanks @heldersepu! As usual 😄

**Pull request merged**
