### PR TITLE
Feature: Advanced Filter (Regex Matching, Case Matching, Full Words Matching, Tag/Route)

### LINKED ISSUE #6648: The filter in SwaggerUIBundle is grouped tags that contain the same word
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Firefox mozilla
 - Version: 82.0.3
 - Method of installation: npm swagger-ui-dist
 - Swagger-UI version: 3.36.2
 - Swagger/OpenAPI version: Swagger 2.9.2

### Content & configuration
Using SwaggerUIBundle with filter, which is using tags. I've noticed if I have a tag that the value contains in other tags (case-sensitive), e.g. tag "street" and tag "streetNumber", when I use `filter: "street"`, it will display all operations for "street" tag as well as "streetNumber" tag. I want to only display operations for "street" tag. 

Currently my workaround is adding an extra space: "street " tag, but this is not ideal because that means everytime we update or add new tags, we need to check all other tags to make sure no tag value contains other tag value.

### To reproduce...

1. Go to Rest Controller, create 2 methods, and add  below `@ApiOperation` with `tags` on method1 and method2: 
```
for method1: @ApiOperation(value = "Display street", tags = "street")
for method2: @ApiOperation(value = "Display street number", tags = "streetNumber")
```
2. Get swagger-ui-dist and add SwaggerUIBundle with `filter: "street"` to a html page
3. Scroll down to where you add to display the operations
4. You will see both method1 ("street" tag) and method2 ("streetNumber") tag are displayed

### Expected behavior
My expectation is only operations for that exact tag value will be displayed, e.g. using the above example, only method1 should be displayed, not both method1 and method2.

### PR DESCRIPTION
**Pull request by mathis-m**
### Description

In order to reflect common filtering, like we all know from IDE's, there is the need for new filter configuration options.
It need to store the 3 Flags: regex-, case-, full words-mode and the search location (tag or route/path).
In order to reflect the old behavior defaults are like the following:
```javascript
filterConfig: {
  isRegexFilter: false,
  matchCase: true,
  matchWords: false,
  searchLocation: "tag" // or "route"
}
```

Have a look at the [preview](https://mathis-m.github.io/swagger-advanced-filter-page/?filter=street&url=https://gist.githubusercontent.com/mathis-m/34a8390bc56473c6e6f80086519cfe38/raw/feab644f7faf29441965c60ef8337a026df49a94/swagger.yaml).

Open for more filter features, let's discuss this in #6753.

### Motivation and Context

Reflect common filtering, like we all know from IDE's.
Fixes #6648 

### How Has This Been Tested?

Fixed suts of tests using the filter logic to provide the `currentFilterConfig`.
Wrote tests for new filter algorithm `src/core/plugins/filter/opsFilter.js`.

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [x] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [ ] My changes do not require a change to the project documentation.
- [x] My changes require a change to the project documentation.
- [x] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [x] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tim-lai** [comment]
Hi @mathis-m, this PR and demo looks very promising. A couple of thoughts:

1. I think "match whole word", "match case exactly", and the combination of the two, is a great place to start.
2. I think user input of regex search expression is a nice to have.
3. The text filter by default should apply to all. 
4. We may want to apply the text filter to tag, operation, as well as future categories, so there should be a separate "category" filter (needs a better descriptor), with its own configuration, that we could chain a call. The idea is that a "category" filter could be extended (as plugin?) by others in the future.
5. The UI component to set/unset the text filter options should be in its own component, and abled to be placed "anywhere". I've seen two filter input sizes to be aware of. The first is "wide", which is current swagger-ui default full width, The second is "narrow", the width of an arbitrary sidebar.
6. We should mostly leave the existing opsFilter as-is, perhaps reference it as the "simple" filter. We can then offer an "advancedFilter" option, with sub-options proposed in this PR, and as separate method(s). This should help existing customized versions of swagger-ui to adopt and migrate when ready, as well as enable for additional and/or extended filters.

Finally, expect that this will need a UX/UI review once we get through the functionality implementation.

**Comment by mathis-m** [comment]
@tim-lai 
> 3. The text filter by default should apply to all.
By text filter you mean to filter operation schemas as plain text and return all matching operations?
Or should I build up a filter text for each operation, basically a concatenation of all searchable values of an operation (to be defined).

**Comment by mathis-m** [comment]
Hi @tim-lai,

thanks for your Feedback and I completely agree on all your points.
I will open another PR with the updated code soon.

**Comment by mathis-m** [comment]
closing in favor of #6851

**Pull request closed without merging**
