### PR TITLE
Refactor styles

### PR DESCRIPTION
**Pull request by alycda**
I implemented swagger-ui into a project, and found it difficult to override the styles due to unnecessarily high specificity. This is not perfect, but I believe is a good start, and contributes a major reduction in code bloat.

### CODE REVIEW

**Comment by fehguy** [comment]
Hi, thanks for sending--this is a pretty big change and from my take, it'll break other customization that other folks have made because of renamed classes?  Maybe @mohsen1 can take a look since his css-skills are a mile above mine.

**Comment by mohsen1** [comment]
I looked at this before. It will break other "themes". I vote for not merging it.

**Comment by alycda** [comment]
Thanks for reviewing my pull request. I agree that it would break customizations, but in my experience those who have already customized this will not continue to pull in updates? Either they have modified the less files directly (so an update would override/conflict with their changes) or their file is separate and would need to be updated as well. But isn't that the nature of any customizations? You can't always assume that future updates won't break your changes.

I'm happy to create another pull request that simply reduces specificity without changing the namespaces, if you think that you might want to merge it.

**Comment by mohsen1** [comment]
Ok, let's do this. Please rebase your changes to `develop_2.0` branch and make a new pull request to develop_2.0.

The diff will be much smaller thanks to recent changes. We will discuss it there. 

Thanks you!

**Comment by alycda** [comment]
Will do, Thanks!

**Comment by fehguy** [comment]
Please reopen when rebased.

**Comment by northborn** [comment]
Is there any update on this? Swagger's current non-name-spaced markup and classes are proving to be very unstable in most environments with established project style frameworks.

**Comment by webron** [comment]
You're welcome to rebase the PR and resubmit it.

**Pull request closed without merging**
