### PR TITLE
Handle cases where SVG content is a Blob

### PR DESCRIPTION
**Pull request by heldersepu**
### Description
There are some rest API's that return the svg as a blob that will cause an error if we try ti render it directly

### Types of changes

- [ ] No code changes (changes to documentation, CI, metadata, etc)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by dirkschneemann** [comment]
When I try this out with my API returning an SVG image as blob, the returned image is not rendered, instead the following error box is shown with a "Plugin not supported" message when hovering over it. Same result in different browsers.

Can anybody else confirm this to be working?
svg

**Comment by shockey** [comment]
Travis appears to be in a bad state for this PR - going to close and reopen.

**Comment by heldersepu** [comment]
@shockey if you can take a look at my code see if there is any way to convert a blob to a string, I could not find any way...

**Comment by shockey** [comment]
@heldersepu, there is a way but it's pretty weird:

```js
//// source: https://medium.com/programmers-developers/convert-blob-to-string-in-javascript-944c15ad7d52
const blb    = new Blob(["Lorem ipsum sit"], {type: "text/plain"});
const reader = new FileReader();

// This fires after the blob has been read/loaded.
reader.addEventListener('loadend', (e) => {
  const text = e.srcElement.result;
  console.log(text);
});

// Start reading the blob as text.
reader.readAsText(blb);
```

---

As for this PR, it looks like the source branch has vanished from your fork, so I can't reopen this - can you restore it and then open a new PR?

**Comment by heldersepu** [comment]
Ye, I looked into that but it is async and I could not get it to work in a sync way...
The problem with my branch is that I deleted my fork and recreate it, this PR can stay close!

**Pull request closed without merging**
