### PR TITLE
Issue 1248

### PR DESCRIPTION
**Pull request by bodnia**
#1248 Moved render model and json example to swagger-ui, implemented xml sample render

### CODE REVIEW

**Comment by fehguy** [comment]
awesome.  this will take a bit of time to review but i should be on it shortly.

**Comment by fehguy** [comment]
When toggling the JSON / XML field, the definitions in the `Response Messages` section disappear on XML:

image

image

**Comment by fehguy** [comment]
Looks like we need to guard against infinite recursion.  When rendering the following spec:

```yaml
swagger: "2.0"
info: 
  description: "This is a sample server Petstore server.  You can find out more about Swagger at <a href=\"http://swagger.io\">http://swagger.io</a> or on irc.freenode.net, #swagger.  For this sample, you can use the api key \"special-key\" to test the authorization filters"
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "apiteam@swagger.io"
  license: 
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
externalDocs: 
  description: "Find more info here"
  url: "https://swagger.io"
host: "localhost:8000"
basePath: "/v2/api"
schemes: 
  - "http"
tags: 
  - 
    name: "pet"
    description: "Pet Operations"
    externalDocs: "http://swagger.io"
  - 
    name: "user"
    description: "All about the Users"
paths: 
  /pet/{petId}: 
    get: 
      tags: 
        - "pet"
      summary: "Find pet by ID"
      description: "Returns a pet when ID < 10.  ID > 10 or nonintegers will simulate API error conditions"
      operationId: "getPetById"
      produces: 
        - "application/xml"
        - "application/json"
      parameters: 
        - 
          name: "petId"
          in: "path"
          description: "ID of pet that needs to be fetched"
          required: true
          type: "integer"
          format: "int64"
      responses: 
        200: 
          description: "successful operation"
          schema: 
            $ref: "#/definitions/Pet"
        404: 
          description: "Pet not found"
definitions: 
  Category: 
    properties: 
      id: 
        type: "array"
        items: 
          $ref: '#/definitions/Pet'
        xml:
          name: foo
      name: 
        type: "string"
    xml: 
      name: "Category"
  Pet: 
    required: 
      - "name"
      - "photoUrls"
    properties: 
      id: 
        type: "integer"
        format: "int64"
      category: 
        $ref: "#/definitions/Category"
      name: 
        type: "string"
        example: "doggie"
      photoUrls: 
        type: "array"
        xml: 
          name: "photoUrl"
          wrapped: true
        items: 
          type: "string"
      tags: 
        type: "array"
        xml: 
          name: "tag"
          wrapped: true
        items: 
          $ref: "#/definitions/Tag"
      status: 
        type: "string"
        description: "pet status in the store"
    xml: 
      name: "Pet"
  Tag: 
    properties: 
      id: 
        type: "integer"
        format: "int64"
      name: 
        type: "string"
    xml: 
      name: "Tag"
```

The rendering of the `Category` (which admittedly has a loop from `Pet`, the UI hangs.

**Comment by fehguy** [comment]
looks like rendering an XML array shows two elements:

```yaml
definitions: 
  Category: 
    properties: 
      id: 
        type: "array"
        items: 
          type: "string"
          format: "date-time"
        xml:
          name: foo
      name: 
        type: "string"
    xml: 
      name: "category"
```

renders as:

```xml
<?xml version="1.0"?>
<Pet>
  <id>1</id>
  <Category>
    <foo>1970-01-01T00:00:00.001Z</foo>
    <foo>1970-01-01T00:00:00.001Z</foo>  <!-- should probably be one -->
    <name>string</name>
  </Category>
  <name>doggie</name>
```

**Comment by fehguy** [comment]
Overall this is great.  I'm going to open up separate issues for comments above.  I think the community will be very happy for this contribution!

**Comment by bodnia** [comment]
@fehguy Fixed render of array with one item instead of two
https://github.com/swagger-api/swagger-ui/pull/1891

**Comment by bodnia** [comment]
@fehguy Fixed When toggling the JSON / XML field, the definitions in the Response Messages section disappear on XML https://github.com/bodnia/swagger-ui/commit/4600a53cd01cdc839b32aaef6e16db13b6fc2781

**Pull request merged**
