### PR TITLE
Add Dockerfile and notes to README

### PR DESCRIPTION
**Pull request by dnephin**
Hello,

This PR adds a `Dockerfile` to support building a distribution without having to manually install all of the dependencies on the host.

### CODE REVIEW

**Comment by dnephin** [comment]
@fehguy Any reason you're closing this without any comment?

Do you need a rebase?

**Comment by dnephin** [comment]
Copying and pasting a file in is not really a manual merge.

I can rebase or change this PR if necessary.

**Comment by fehguy** [comment]
Sorry!  I manually merged it into develop_2.0

**Comment by dnephin** [comment]
@fehguy  copying my work and committing it as yourself is not a "manual merge".

You also missed the `.dockerignore` which is important.  If you'd like me to remove the README documentation and re-submit to the develop_2.0 branch, I can do that.

**Comment by fehguy** [comment]
hmm intention wasn't to copy, this made it easier to merge to the correct branch.  I can undo and accept your PR if you like.

**Comment by dnephin** [comment]
I can submit the PR to develop_2.0

**Pull request closed without merging**
