### PR TITLE
Add the packaging metadata to build the swagger-ui snap

### PR DESCRIPTION
**Pull request by elopio**
This is a package for the secure installation of apps that works in most Linux distributions.
Landing it upstream will enable builds that then can be distributed to many users through the Ubuntu store.

### CODE REVIEW

**Comment by elopio** [comment]
You can find more information about snapcraft here: http://snapcraft.io/

To test it in an Ubuntu 16.04 machine:

    $ sudo apt install git snapcraft
    $ git clone https://github.com/elopio/swagger-ui
    $ cd swagger-ui
    $ git checkout snapcraft
    $ snapcraft
    $ sudo snap install *.snap --dangerous
    $ sensible-browser localhost:8080

If you have any questions or comments, please let me know.

**Comment by elopio** [comment]
ping, anybody around to review this?

**Comment by webron** [comment]
@elopio Sorry for the delay. We've been really focused on the 3.x release. As such, the PR that was made against the older version, needs to be refreshed. Can you do that and then we'll review it?

**Comment by elopio** [comment]
Thanks for the reply @webron. I've refreshed my branch.

**Comment by elopio** [comment]
\o/ Thanks for the merge!

@webron @shockey you can now release one initial snap to the store: https://snapcraft.io/docs/build-snaps/publish 
And then I can help you automating the delivery so you push a new version to the edge channel every time that something lands in your master branch. That's great for early feedback. We can make crowd testing with the ubuntu to try this snap too.

If you and your users like it, maybe we can talk about making a snap for your swagger editor. That would also be a great addition to the Ubuntu store :)

**Comment by webron** [comment]
@elopio building the initial snap might prove slightly challenging as it seems you'd need to be on ubuntu, which none of us is...

**Comment by elopio** [comment]
@webron you can build it in a docker or lxc container. Let me know which distro do you use, and I can give you a hand.

**Comment by webron** [comment]
macOS ;)

**Comment by elopio** [comment]
lol. I was obviously not expecting that answer. We will have a very nice way for you to build and run snaps, there's some interesting work in progress here.

For now, you can install docker in your mac. We have an image snapcore/snapcraft, which has the latest snapcraft installed.

**Comment by shockey** [comment]
@elopio, would you be able to PR an automated setup for these releases? We use Ubuntu containers on TravisCI to publish on npm when we tag a release. I'm not too keen on adding a manual step to our release process - if I'm understanding you correctly, we'd need to spin up a Docker image to release each new version of the UI via Snapcraft.

**Comment by elopio** [comment]
@shockey no, the idea is to automate the delivery:
https://snapcraft.io/docs/build-snaps/ci-integration
This however needs your credentials for travis and the store, so I can't do it for you.

All the steps to enable travis for this can be run from that snapcore/snapcraft docker container.

I could register the snap under my name. This is ugly because when users search for your snap, I will be the publisher, not swagger. But it could be an ok way to get started, I can transfer it to you after some time, if you see good stats and good feedback from your users.

**Comment by elopio** [comment]
@webron I come with some very good news for you: https://build.snapcraft.io/

That service will take care of building the snap, and publishing it to the store. So continuous delivery to all the ubuntu users out there, with very little effort. It's in beta, so I would appreciate any feedback that you can give us to make it better before GA.

**Comment by webron** [comment]
@elopio thanks for that. We're a bit overloaded this week, but next week should be easier. I do ask that you ping me on the issue just because there are too many things going on, and I might end up forgetting about it.

**Pull request merged**
