### PR TITLE
Replace color values with variables for easier theming

### PR DESCRIPTION
**Pull request by casions**
To make it easier to customize Swagger UI,
replaced all color values with variables in scss files and
added associated variables to _variables.scss file

### CODE REVIEW

**Comment by james-world** [comment]
This makes it much easier to recolour. Good stuff.

**Comment by shockey** [comment]
+1, this is great!

I'm hoping to approve this sometime this week - reviewing all the new variables will be a bit tedious 😄

**Comment by Minasokoni** [comment]
@casions Very nice job man! This is pretty huge for anyone wanting to customize colors. 👍

**Comment by casions** [comment]
@shockey thank you.  As was writing them.  Please let me know if they don't conform to the naming conventions that you use and I will update them.

**Comment by casions** [comment]
Hi @shockey, I updated the code to reflect a couple of errors that I made.  There were a few changes that were related to code in other commits, so I rebased my work onto master and these seem to be resolved.  If you do the comparison again you should only see unimportant changes (#888 to gray, #008000 to green, etc).

Please let me know if you require anything else from me.

**Comment by shockey** [comment]
Merged 🎉 

Thanks again @casions!

**Pull request merged**
