### PR TITLE
Bug/update dependencies

### LINKED ISSUE #4495: Update Swagger-UI to latest dependencies (e.g. React 16, WebPack 3)
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Neither
| Which Swagger/OpenAPI version?  | N/A
| Which Swagger-UI version?       | v3.14.0
| How did you install Swagger-UI? | N/A
| Which browser & version?        | N/A
| Which operating system?         | N/A

### Expected Behavior

Project dependencies reasonably up-to-date so that performance/security improvements are taken advantage of. 

### Current Behavior

Noticed that package dependencies were significantly behind, e.g. Webpack 2 and React 14/15. 

### Possible Solution
Already updated to React 16.0 and WebPack 3. PR going up soon. 😄 

### Context

It makes developing Swagger-UI more pleasant if it stays current with the JS community.

### PR DESCRIPTION
**Pull request by dennisroche**
### Description

- Added `package-lock.json` as discussed in https://github.com/swagger-api/swagger-ui/pull/4496
- Updated to `webpack 3.11`
- Fixed dependency warnings
- Removed obsolete dependencies

### Motivation and Context

Fixes #4495

### How Has This Been Tested?

Running locally in Chrome and using current automation test suite. 

### My PR contains... 
- [x] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [x] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [x] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [ ] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by heldersepu** [comment]
@dennisroche look into the Conflicting files...

**Comment by shockey** [comment]
Conflicts resolved 😄

**Comment by dennisroche** [comment]
Another round of conflicts auto-resolved. :smile:

**Comment by dennisroche** [comment]
@shockey another round of conflicts resolved. is there anything blocking this PR from merging?

**Comment by shockey** [comment]
@dennisroche - no blocks, this is on our list of next PRs to review 😄

**Pull request merged**
