### PR TITLE
bug: show nested array member title correctly (#5276)

### LINKED ISSUE #5276: Array model name shown incorrectly
Consider this representation:
```
basePath: /
consumes:
- application/json
definitions:
  Domain:
    description: |-
      An example domain
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  domainsList:
    description: A list of all domains
    items:
      $ref: '#/definitions/Domain'
    type: array
info:
  description: This documentation describes example APIs
  license:
    name: MIT
  title: Example
  version: 1.0.0
paths:
  /domain:
    get:
      operationId: domains
      responses:
        "200":
          description: A list of all domains
          schema:
            $ref: '#/definitions/domainsList'
      summary: Get all domains
produces:
- application/json
responses:
  ok:
    description: The response type of a call to get all domains
schemes:
- https
securityDefinitions:
  bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
```

`domainsList` is of type `array` with items of type `#/definitions/Domain`. However when shown in the `Models` section this is rendered incorrectly:

### Expected
A list of `Domain` ie. `[Domain{...}]`
Screenshot 2019-03-29 at 21 05 24

### Actual
The name of the object is incorrectly shown as the name of the list
Screenshot 2019-03-29 at 21 04 28

This is reproducible by pasting the content above onto https://editor.swagger.io

### PR DESCRIPTION
**Pull request by xdrop**
### Description
Fixes #5276 

### How Has This Been Tested?
The example swagger `yaml` file was loaded and verified that the nested array member title is shown correctly.

### CODE REVIEW

**Comment by leggsimon** [comment]
@xdrop Are you able to provide some screenshots to show the result of this change?

**Comment by xdrop** [comment]
Hey I have provided some screenshots in the issue #5276 

Essentially consider this definition

```
  domainsList:
    description: A list of all domains
    items:
      $ref: '#/definitions/Domain'
    type: array
```

A `domainsList` is an array of `Domain`, yet it is displayed as:



Which is confusing as the objects within the array are not `domainsList` themselves.

After this patch the result is:



Which correctly shows a `domainsList` containing `Domain` objects

**Comment by heldersepu** [comment]
Would be nice to get some unit tests on this... 
that would ensure that future a changes do not causes an accidental regression

**Comment by maddymadh** [comment]
What is the fix?

I am facing below issue in swagger-ui

i have declared as array but swagger ui shows as string in multipart/form-data
'type[]':
          type: array
          items:
            $ref: '#/components/schemas/C1DocumentType'
          minItems: 1
          maxItems: 5
        file:
          type: array
          items:
            type: File
          minItems: 1
          maxItems: 5
        country:
            $ref: './common-schema.yml#/components/schemas/IsoCountryCodeEnum'
      encoding:
        'type[]':
          style: form
          explode: true

**Comment by caffeinatedMike** [comment]
@leggsimon Can this be re-opened or addressed in another PR? This is still an issue today.

**Pull request closed without merging**
