### PR TITLE
Adds ability to set oauth2RedirectUrl using env vars for Docker

### PR DESCRIPTION
**Pull request by shankie-san**
As per #3138 , added ability to set oauth2RedirectUrl by setting env var `OAUTH2_REDIRECT_URL` . Updated readme to better document the options available to Docker users.

### CODE REVIEW

**Comment by webron** [comment]
@fehguy - when you get a chance... :)

**Comment by shockey** [comment]
TODO: notify @webron upon resolution of this PR

**Comment by webD97** [comment]
What's the status on this? This is a serious problem when using Swagger UI from Docker...

**Comment by shockey** [comment]
I'm closing this out since we've support `OAUTH2_REDIRECT_URL` as an env var since #4965 landed — I've opened #5641 to update the docs accordingly.

Thanks for the PR, @shankie-san!

**Pull request closed without merging**
