### PR TITLE
refactor: replace randombytes with native methods

### PR DESCRIPTION
**Pull request by TrySound**
### Description

Replaced randombytes package with a few native methods
Converting values to base64 is less trivial but solvable.

### Motivation and Context

Native crypto.getRandomBytes has quite good browser support
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [x] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [x] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tim-lai** [comment]
@TrySound Thanks for the PR! It appears that this dependency was used to solve a browser vs node issue (likely test). While the node tests pass, are you able to comment and verify that everything still works as expected on the browser, e.g. Cypress test?

**Comment by TrySound** [comment]
Is it covered by cypress tests?

**Comment by TrySound** [comment]
Browser generated ids are a bit longer but work.

**Comment by tim-lai** [comment]
It looks like the `generateCodeVerifier` is used for OAuth2 authorization. However, the jest test uses a mock, and your update includes a node-based unit test, so my question is if OAuth2 authorization still works as expected in browser, ideally with a new Cypress test that is specifically checking for this functionality. Alternatively, if someone already has OAuth2 setup and can help verify that there is no effect, that would be helpful.

**Pull request closed without merging**
