### PR TITLE
generate handlerbars template as part of gulp build process

### PR DESCRIPTION
**Pull request by pwielgolaski**
At the moment build process is split, some is coordinated by npm and some by gulp.
It is most annoying then I want to develop a change and handlebars are not regenerated and reloaded when I make change.

I change it to generate handlerbars JS as part of gulp task and also enabled it directly in default and serve task.

### CODE REVIEW

**Comment by pwielgolaski** [comment]
are there any interest in merging this one?
If there is, I will make sure it is not conflicting.

I really think this small change make development easier with handlerbars.

**Comment by webron** [comment]
@pwielgolaski at the moment we're focused on 3.X. It doesn't mean PRs against 2.X will not be merged, but it might take us longer to review. Regardless, this PR would need to be resubmitted against the 2.x branch.

**Comment by pwielgolaski** [comment]
I was not aware of that you started 3.x development.
I rebased it to latest 2.x branch and also change PR base to 2.x.

I hope it makes it easier to make decision about merging it.

**Comment by webron** [comment]
Apologies for the (very) delayed feedback.

Unfortunately, our code base might have deviated from the time this PR was submitted, and we cannot easily merge it (certainly not against `master`), and so, we're going to close this PR.

If you find the change important and would like to resubmit it, please let us know. Be aware that we are focused on the 3.X version at the moment (now `master`), and new changes should be applied to it.

We appreciate the time you've taken into submitting this PR. We're now making extra effort to review PRs within a few days at most, to avoid situations like this.

**Pull request closed without merging**
