### PR TITLE
JSON Body Editor (Master PR)

### PR DESCRIPTION
**Pull request by lepinayl**
# Feature proposal: JSON Body Editor

## Previous history
This PR is a continuation of https://github.com/swagger-api/swagger-ui/pull/1088
You will find earlier informations/comments there about the history of this PR.

## Related work
This is a proposal to add a JSON editor for body requests in swagger UI.

This work is based on another open source project called [Json-editor](https://github.com/jdorn/json-editor) by [Jeremy Dorn](https://github.com/jdorn).

You will be able to find a demo of Jeremy's editor [here](http://jeremydorn.com/json-editor/) to give you an idea of the great potential of this editor.

## Configuration
The editor can be enabled/disabled using the swagger configuration key ```jsonEditor``` :
```javascript
      window.swaggerUi = new SwaggerUi({
        jsonEditor:true
      });
```

The option is currently enabled by default (just because it is more practical for e2e tests).

## Visual preview

This is how it looks like at the moment in a post request:
capture

## Online preview
You can try the UI with the editor here: http://thomsonreuters.github.io/swagger-ui/
*you will need to have CORS enabled on your endpoint*

## Backward compatibility
According to the way swagger now works, Specs 1.2 are now automaticaly converted to 2.0.

So it should work with 1.2 as well but I haven't not tested it yet.

## Current state of the implementation

Please let me know how I could improve both the internal design (code, unit tests, configuration) and external design (css, user experience).

## External dependencies
The following PR have been created on JSONEditor to implement this feature
https://github.com/jdorn/json-editor/pull/461 (closed)
https://github.com/jdorn/json-editor/pull/456 (open, need some rework)
https://github.com/jdorn/json-editor/pull/512 (merged)

So at the moment this PR is using a custom JSONEditor version until both remaining PR will be accepted.

## Tests
Tested on
http://petstore.swagger.io/v2/swagger.json
https://raw.githubusercontent.com/jabr9983/swagger.json/master/swagger.json

Not tested yet
http://ringcentral.github.io/api-explorer-beta/swagger-ring.json
https://api.swaggerhub.com/apis/fehguy/ringcentral-api/1.0

### CODE REVIEW

**Comment by webron** [comment]
Thanks again for all the work. I'll test the functionality in the upcoming days and hopefully we'll manage to get it merged soon. I'm sure many users would be excited for it.

If any user wants to clone the fork and test the PR and provide feedback, that would be great too.

**Comment by jontonsoup** [comment]
@lepinayl Thanks for this PR! It looks really awesome. 

I have a question about the functionality-- is the editor supposed to serialize automatically? 

For example: 

The user field is incorrectly set up when I load the page (it should be an object):

screen shot 2015-09-11 at 10 55 38 pm

But when I  choose "object" it is serialized properly. It seems to me that the "user" field should be pre chosen as an object (maybe I shouldn't even have an option to send it as a boolean?)

screen shot 2015-09-11 at 10 56 24 pm

Its possible my swagger definition has an error in it, but this seems like confusing behavior to me. 

Best,
Jon

**Comment by lepinay** [comment]
@jontonsoup thank you for the testing feedback, it would be great if you could share your json spec so that I can have a look to the issue.

**Comment by jontonsoup** [comment]
I tried to clean it up to the relevant parts. Please let me know if its missing anything. @lepinay 

```
paths:
  /orders:        
    post:
      tags:
        - order
      summary: Create a new order object
      description: ""
      operationId: create_order
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: order
          description: Information needed to create an order.
          required: true
          schema:
            $ref: "#/definitions/OrderRequest"
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/OrderResponse"
        "400":
          description: Invalid input
        
      security:
        - api_key: []

definitions:
  User:
    required:
      - first_name
      - last_name
    properties:
      first_name:
        type: string
      last_name:
        type: string
      phone:
        type: string
  OrderRequest:
    required:
      - user
      - address
    properties:
      user:
        $ref: "#/definitions/User"
      address:
        $ref: "#/definitions/Address"
      location:
        $ref: "#/definitions/Location"
  OrderResponse:
    required:
      - user
      - address
      - status
    properties:
      id:
        type: integer
        format: int64
      user:
        $ref: "#/definitions/User"
      address:
        $ref: "#/definitions/Address"
      location:
        $ref: "#/definitions/Location"
      price:
       type: number
      status:
        type: string
        enum:
         - "address_submitted"
         - "in_progress"
         - "completed"
        description: Order Status

  Location:
    type: array
    items:
      type: number

  Address:
    required:
      - street
      - city
      - state
      - zipcode
    properties:
      street:
        type: string
        description: Street name with number
      apartment_number:
        type: string
        description: an apartment number if there is one
      city:
        type: string
        description: Address City
      state:
        type: string
        description: Address State
      zipcode:
        type: integer
        maxLength: 5
        minLength: 5
        description: zipcode
```

**Comment by lepinay** [comment]
@jontonsoup this was indeed a regression, I've tested it on your schema and it should be fixed now.

**Comment by jontonsoup** [comment]
Awesome! This is a great feature-- thanks for adding it.

**Comment by jontonsoup** [comment]
@lepinay I actually just checked out the new branch and I still have the error. 

Best,
Jon

**Comment by lepinay** [comment]
@jontonsoup strange...the fix is supposed to handle this scenario and I've tested with your schema, it worked.

Basically here https://github.com/thomsonreuters/swagger-ui/commit/504095e10e7e027939dbe0c7c89aa3bdd28f6f1a

I specifically check that if the type is null or undefined, I force it to object.

**Comment by jontonsoup** [comment]
@lepinayl  did you update the dist? I've used that to do my check

Best,
Jon

**Comment by lepinay** [comment]
@jontonsoup yes dist is up to date, as a safety check, you should have the following lines in your  dist/swagger-ui.js around line 31130:

```javascript
if (!this.model.definitions[def].type){
         this.model.definitions[def].type = 'object';
       }
```

This is the actual fix.

**Comment by jontonsoup** [comment]
I confirmed that that code is running -- I also confirmed that it is correctly setting the def to object by doing a console log. The bug still exists though. 

For sanity sake, I'm going to include my full schema. 
```
swagger: "2.0"
info:
  version: "1.0.0"
  title: Api
  termsOfService: None
host: localhost:8000
basePath: /api/v1
schemes:
  - http
paths:
  /orders:
    get:
      tags:
        - order
      summary: Returns all your previous orders
      description: This will return all your orders (both in progress and completed)
      operationId: find_orders
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/OrderResponse"
    post:
      tags:
        - order
      summary: Create a new order object
      operationId: create_order
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: OrderRequest 
          in: body
          description: Information needed to create an order.
          required: true
          schema:
            $ref: "#/definitions/OrderRequest"
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/OrderResponse"
        "400":
          description: Invalid input
        
      security:
        - api_key: []

  /orders/confirm/{id}:
    put:
      tags:
        - order
      summary: Confirm an order
      operationId: confirmOrder
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: ID order to be confirmed
          required: true
          type: string
      responses:
        "404":
          description: Order not found
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/OrderResponse"
        "400":
          description: Invalid ID supplied
      security:
        - api_key: []

  /order/status/{id}:
    get:
      tags:
        - order
      summary: Retrieve information about a current order
      description: Returns current information about an order
      operationId: get_order_status
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: ID of order that needs to be fetched
          required: true
          type: string
      responses:
        "404":
          description: Order not found
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/OrderResponse"
        "400":
          description: Invalid ID supplied
      security:
        - api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: query
definitions:
  User:
    required:
      - first_name
      - last_name
    properties:
      first_name:
        type: string
      last_name:
        type: string
      phone:
        type: string
  OrderRequest:
    required:
      - user
      - address
    properties:
      user:
        $ref: "#/definitions/User"
      address:
        $ref: "#/definitions/Address"
      location:
        $ref: "#/definitions/Location"
  OrderResponse:
    required:
      - user
      - address
      - status
    properties:
      id:
        type: integer
        format: int64
      user:
        $ref: "#/definitions/User"
      address:
        $ref: "#/definitions/Address"
      location:
        $ref: "#/definitions/Location"
      price:
       type: number
      status:
        type: string
        enum:
         - "address_submitted"
         - "in_progress"
         - "completed"
        description: Order Status

  Location:
    type: array
    items:
      type: number

  Address:
    required:
      - street
      - city
      - state
      - zipcode
    properties:
      street:
        type: string
        description: Street name with number
      apartment_number:
        type: string
        description: an apartment number if there is one
      city:
        type: string
        description: Address City
      state:
        type: string
        description: Address State
      zipcode:
        type: integer
        maxLength: 5
        minLength: 5
        description: zipcode

```

**Comment by lepinay** [comment]
Okay, so

. I've cloned and checked out JSONEditorMaster from https://github.com/thomsonreuters/swagger-ui.git on a clean folder.
. Converted your yaml schema using http://editor.swagger.io to json

The result is hosted here: http://swagger.azurewebsites.net/
You can browse to http://swagger.azurewebsites.net/jontonsoup.json to have a look at your spec. Things to be working.

Tested in chrome and firefox.

So I'm now a bit clueless....could you send me a zip of your dist files so that I can run a diff between them ? Something must be different. Meanwhile I'm sending you mine as attachement.


[dist.zip | uploaded via ZenHub](https://files.zenhub.io/55fa7607dafc8bf5076c66a3)

**Comment by jontonsoup** [comment]
Thanks for investigating this with me. 



I’ve taken a look further at the differences between your code and mine. It appears that there is a bug in the difference between supplying a .yaml file vs a .json file. 


If I supply a yaml file, I get the bug, if I supply a .json file (translated via the editor) then the bug goes away.




I’m not sure if this matter for this PR or is a bug in a dependency. 





Best,

Jon

**Comment by lepinay** [comment]
@jontonsoup ah that's interesting! I didn't even know you could work with a yaml directly. I'll look into it. Thanks.

**Comment by jontonsoup** [comment]
The swagger editor only works with YAML files from my understanding. I just realized I’m also using https://github.com/BigstickCarpet/swagger-express-middleware, which might be the cause of the bug in terms of converying YAML to JSON. 


Best,

Jon

**Comment by lepinay** [comment]
@jontonsoup Do you think you could get the json that gets out of this middleware ? I'd be curious to look at it just to see if I didn't miss any corner cases. That would be really useful !

**Comment by jontonsoup** [comment]
This one is slightly different from the ones I sent before because of some rebasing, but I verified that it is still broken. 

```
{
   "swagger":"2.0",
   "host":"localhost:8000",
   "basePath":"/api/v1",
   "schemes":[
      "http"
   ],
   "paths":{
      "/orders":{
         "get":{
            "tags":[
               "order"
            ],
            "summary":"Returns all previous orders",
            "description":"This will return all your orders (both in progress and completed)",
            "operationId":"find_orders",
            "produces":[
               "application/json"
            ],
            "responses":{
               "200":{
                  "description":"successful operation",
                  "schema":{
                     "type":"array",
                     "items":{
                        "required":[
                           "user",
                           "address",
                           "status"
                        ],
                        "properties":{
                           "id":{
                              "type":"integer",
                              "format":"int64"
                           },
                           "user":{
                              "required":[
                                 "first_name",
                                 "last_name"
                              ],
                              "properties":{
                                 "first_name":{
                                    "type":"string"
                                 },
                                 "last_name":{
                                    "type":"string"
                                 },
                                 "phone":{
                                    "type":"string"
                                 }
                              }
                           },
                           "address":{
                              "required":[
                                 "street",
                                 "city",
                                 "state",
                                 "zipcode"
                              ],
                              "properties":{
                                 "street":{
                                    "type":"string",
                                    "description":"Street name with number"
                                 },
                                 "apartment_number":{
                                    "type":"string",
                                    "description":"an apartment number if there is one"
                                 },
                                 "city":{
                                    "type":"string",
                                    "description":"Address City"
                                 },
                                 "state":{
                                    "type":"string",
                                    "description":"Address State"
                                 },
                                 "zipcode":{
                                    "type":"integer",
                                    "maxLength":5,
                                    "minLength":5,
                                    "description":"zipcode"
                                 }
                              }
                           },
                           "location":{
                              "type":"array",
                              "items":{
                                 "type":"number"
                              }
                           },
                           "price":{
                              "type":"number"
                           },
                           "status":{
                              "type":"string",
                              "enum":[
                                 "address_submitted",
                                 "in_progress",
                                 "completed"
                              ],
                              "description":"Order Status"
                           }
                        }
                     }
                  }
               }
            }
         },
         "post":{
            "tags":[
               "order"
            ],
            "summary":"Create a new order object",
            "operationId":"create_order",
            "consumes":[
               "application/json"
            ],
            "produces":[
               "application/json"
            ],
            "parameters":[
               {
                  "in":"body",
                  "name":"order",
                  "description":"Information needed to create an order.",
                  "required":true,
                  "schema":{
                     "required":[
                        "user",
                        "address"
                     ],
                     "properties":{
                        "user":{
                           "required":[
                              "first_name",
                              "last_name"
                           ],
                           "properties":{
                              "first_name":{
                                 "type":"string"
                              },
                              "last_name":{
                                 "type":"string"
                              },
                              "phone":{
                                 "type":"string"
                              }
                           }
                        },
                        "address":{
                           "required":[
                              "street",
                              "city",
                              "state",
                              "zipcode"
                           ],
                           "properties":{
                              "street":{
                                 "type":"string",
                                 "description":"Street name with number"
                              },
                              "apartment_number":{
                                 "type":"string",
                                 "description":"an apartment number if there is one"
                              },
                              "city":{
                                 "type":"string",
                                 "description":"Address City"
                              },
                              "state":{
                                 "type":"string",
                                 "description":"Address State"
                              },
                              "zipcode":{
                                 "type":"integer",
                                 "maxLength":5,
                                 "minLength":5,
                                 "description":"zipcode"
                              }
                           }
                        },
                        "location":{
                           "type":"array",
                           "items":{
                              "type":"number"
                           }
                        }
                     }
                  }
               }
            ],
            "responses":{
               "200":{
                  "description":"successful operation",
                  "schema":{
                     "required":[
                        "user",
                        "address",
                        "status"
                     ],
                     "properties":{
                        "id":{
                           "type":"integer",
                           "format":"int64"
                        },
                        "user":{
                           "required":[
                              "first_name",
                              "last_name"
                           ],
                           "properties":{
                              "first_name":{
                                 "type":"string"
                              },
                              "last_name":{
                                 "type":"string"
                              },
                              "phone":{
                                 "type":"string"
                              }
                           }
                        },
                        "address":{
                           "required":[
                              "street",
                              "city",
                              "state",
                              "zipcode"
                           ],
                           "properties":{
                              "street":{
                                 "type":"string",
                                 "description":"Street name with number"
                              },
                              "apartment_number":{
                                 "type":"string",
                                 "description":"an apartment number if there is one"
                              },
                              "city":{
                                 "type":"string",
                                 "description":"Address City"
                              },
                              "state":{
                                 "type":"string",
                                 "description":"Address State"
                              },
                              "zipcode":{
                                 "type":"integer",
                                 "maxLength":5,
                                 "minLength":5,
                                 "description":"zipcode"
                              }
                           }
                        },
                        "location":{
                           "type":"array",
                           "items":{
                              "type":"number"
                           }
                        },
                        "price":{
                           "type":"number"
                        },
                        "status":{
                           "type":"string",
                           "enum":[
                              "address_submitted",
                              "in_progress",
                              "completed"
                           ],
                           "description":"Order Status"
                        }
                     }
                  }
               },
               "400":{
                  "description":"Invalid input"
               }
            },
            "security":[
               {
                  "api_key":[

                  ]
               }
            ]
         }
      },
      "/orders/confirm/{id}":{
         "put":{
            "tags":[
               "order"
            ],
            "summary":"Confirm an order",
            "description":"This confirms the order. It returns the orderId and the status. You will be charged at this point.",
            "operationId":"confirmOrder",
            "produces":[
               "application/json"
            ],
            "parameters":[
               {
                  "in":"path",
                  "name":"id",
                  "description":"ID order to be confirmed",
                  "required":true,
                  "type":"string"
               }
            ],
            "responses":{
               "200":{
                  "description":"successful operation",
                  "schema":{
                     "required":[
                        "user",
                        "address",
                        "status"
                     ],
                     "properties":{
                        "id":{
                           "type":"integer",
                           "format":"int64"
                        },
                        "user":{
                           "required":[
                              "first_name",
                              "last_name"
                           ],
                           "properties":{
                              "first_name":{
                                 "type":"string"
                              },
                              "last_name":{
                                 "type":"string"
                              },
                              "phone":{
                                 "type":"string"
                              }
                           }
                        },
                        "address":{
                           "required":[
                              "street",
                              "city",
                              "state",
                              "zipcode"
                           ],
                           "properties":{
                              "street":{
                                 "type":"string",
                                 "description":"Street name with number"
                              },
                              "apartment_number":{
                                 "type":"string",
                                 "description":"an apartment number if there is one"
                              },
                              "city":{
                                 "type":"string",
                                 "description":"Address City"
                              },
                              "state":{
                                 "type":"string",
                                 "description":"Address State"
                              },
                              "zipcode":{
                                 "type":"integer",
                                 "maxLength":5,
                                 "minLength":5,
                                 "description":"zipcode"
                              }
                           }
                        },
                        "location":{
                           "type":"array",
                           "items":{
                              "type":"number"
                           }
                        },
                        "price":{
                           "type":"number"
                        },
                        "status":{
                           "type":"string",
                           "enum":[
                              "address_submitted",
                              "in_progress",
                              "completed"
                           ],
                           "description":"Order Status"
                        }
                     }
                  }
               },
               "400":{
                  "description":"Invalid ID supplied"
               },
               "404":{
                  "description":"Order not found"
               }
            },
            "security":[
               {
                  "api_key":[

                  ]
               }
            ]
         }
      },
      "/order/status/{id}":{
         "get":{
            "tags":[
               "order"
            ],
            "summary":"Retrieve information about a current order",
            "description":"Returns current information about an order",
            "operationId":"get_order_status",
            "produces":[
               "application/json"
            ],
            "parameters":[
               {
                  "in":"path",
                  "name":"id",
                  "description":"ID of pet that needs to be fetched",
                  "required":true,
                  "type":"integer",
                  "format":"int64"
               }
            ],
            "responses":{
               "200":{
                  "description":"successful operation",
                  "schema":{
                     "required":[
                        "user",
                        "address",
                        "status"
                     ],
                     "properties":{
                        "id":{
                           "type":"integer",
                           "format":"int64"
                        },
                        "user":{
                           "required":[
                              "first_name",
                              "last_name"
                           ],
                           "properties":{
                              "first_name":{
                                 "type":"string"
                              },
                              "last_name":{
                                 "type":"string"
                              },
                              "phone":{
                                 "type":"string"
                              }
                           }
                        },
                        "address":{
                           "required":[
                              "street",
                              "city",
                              "state",
                              "zipcode"
                           ],
                           "properties":{
                              "street":{
                                 "type":"string",
                                 "description":"Street name with number"
                              },
                              "apartment_number":{
                                 "type":"string",
                                 "description":"an apartment number if there is one"
                              },
                              "city":{
                                 "type":"string",
                                 "description":"Address City"
                              },
                              "state":{
                                 "type":"string",
                                 "description":"Address State"
                              },
                              "zipcode":{
                                 "type":"integer",
                                 "maxLength":5,
                                 "minLength":5,
                                 "description":"zipcode"
                              }
                           }
                        },
                        "location":{
                           "type":"array",
                           "items":{
                              "type":"number"
                           }
                        },
                        "price":{
                           "type":"number"
                        },
                        "status":{
                           "type":"string",
                           "enum":[
                              "address_submitted",
                              "in_progress",
                              "completed"
                           ],
                           "description":"Order Status"
                        }
                     }
                  }
               },
               "400":{
                  "description":"Invalid ID supplied"
               },
               "404":{
                  "description":"Order not found"
               }
            },
            "security":[
               {
                  "api_key":[

                  ]
               }
            ]
         }
      },
      "/users":{
         "post":{
            "tags":[
               "user"
            ],
            "summary":"Create user",
            "description":"This can only be done by the logged in user.",
            "operationId":"create_user",
            "produces":[
               "application/json"
            ],
            "parameters":[
               {
                  "in":"body",
                  "name":"body",
                  "description":"Created user object",
                  "required":false,
                  "schema":{
                     "required":[
                        "first_name",
                        "last_name"
                     ],
                     "properties":{
                        "first_name":{
                           "type":"string"
                        },
                        "last_name":{
                           "type":"string"
                        },
                        "phone":{
                           "type":"string"
                        }
                     }
                  }
               }
            ],
            "responses":{
               "default":{
                  "description":"successful operation"
               }
            }
         }
      },
      "/users/login":{
         "get":{
            "tags":[
               "user"
            ],
            "summary":"Logs user into the system",
            "description":"",
            "operationId":"log_in_user",
            "produces":[
               "application/json"
            ],
            "parameters":[
               {
                  "in":"query",
                  "name":"username",
                  "description":"The user name for login",
                  "required":true,
                  "type":"string"
               },
               {
                  "in":"query",
                  "name":"password",
                  "description":"The password for login in clear text",
                  "required":true,
                  "type":"string"
               }
            ],
            "responses":{
               "200":{
                  "description":"successful operation",
                  "schema":{
                     "type":"string"
                  }
               },
               "400":{
                  "description":"Invalid username/password supplied"
               }
            }
         }
      },
      "/users/logout":{
         "get":{
            "tags":[
               "user"
            ],
            "summary":"Logs out current logged in user session",
            "description":"",
            "operationId":"log_out_user",
            "produces":[
               "application/json"
            ],
            "responses":{
               "default":{
                  "description":"successful operation"
               }
            }
         }
      }
   },
   "securityDefinitions":{
      "api_key":{
         "type":"apiKey",
         "name":"api_key",
         "in":"query"
      }
   },
   "definitions":{
      "User":{
         "required":[
            "first_name",
            "last_name"
         ],
         "properties":{
            "first_name":{
               "type":"string"
            },
            "last_name":{
               "type":"string"
            },
            "phone":{
               "type":"string"
            }
         }
      },
      "OrderRequest":{
         "required":[
            "user",
            "address"
         ],
         "properties":{
            "user":{
               "required":[
                  "first_name",
                  "last_name"
               ],
               "properties":{
                  "first_name":{
                     "type":"string"
                  },
                  "last_name":{
                     "type":"string"
                  },
                  "phone":{
                     "type":"string"
                  }
               }
            },
            "address":{
               "required":[
                  "street",
                  "city",
                  "state",
                  "zipcode"
               ],
               "properties":{
                  "street":{
                     "type":"string",
                     "description":"Street name with number"
                  },
                  "apartment_number":{
                     "type":"string",
                     "description":"an apartment number if there is one"
                  },
                  "city":{
                     "type":"string",
                     "description":"Address City"
                  },
                  "state":{
                     "type":"string",
                     "description":"Address State"
                  },
                  "zipcode":{
                     "type":"integer",
                     "maxLength":5,
                     "minLength":5,
                     "description":"zipcode"
                  }
               }
            },
            "location":{
               "type":"array",
               "items":{
                  "type":"number"
               }
            }
         }
      },
      "OrderResponse":{
         "required":[
            "user",
            "address",
            "status"
         ],
         "properties":{
            "id":{
               "type":"integer",
               "format":"int64"
            },
            "user":{
               "required":[
                  "first_name",
                  "last_name"
               ],
               "properties":{
                  "first_name":{
                     "type":"string"
                  },
                  "last_name":{
                     "type":"string"
                  },
                  "phone":{
                     "type":"string"
                  }
               }
            },
            "address":{
               "required":[
                  "street",
                  "city",
                  "state",
                  "zipcode"
               ],
               "properties":{
                  "street":{
                     "type":"string",
                     "description":"Street name with number"
                  },
                  "apartment_number":{
                     "type":"string",
                     "description":"an apartment number if there is one"
                  },
                  "city":{
                     "type":"string",
                     "description":"Address City"
                  },
                  "state":{
                     "type":"string",
                     "description":"Address State"
                  },
                  "zipcode":{
                     "type":"integer",
                     "maxLength":5,
                     "minLength":5,
                     "description":"zipcode"
                  }
               }
            },
            "location":{
               "type":"array",
               "items":{
                  "type":"number"
               }
            },
            "price":{
               "type":"number"
            },
            "status":{
               "type":"string",
               "enum":[
                  "address_submitted",
                  "in_progress",
                  "completed"
               ],
               "description":"Order Status"
            }
         }
      },
      "Location":{
         "type":"array",
         "items":{
            "type":"number"
         }
      },
      "Address":{
         "required":[
            "street",
            "city",
            "state",
            "zipcode"
         ],
         "properties":{
            "street":{
               "type":"string",
               "description":"Street name with number"
            },
            "apartment_number":{
               "type":"string",
               "description":"an apartment number if there is one"
            },
            "city":{
               "type":"string",
               "description":"Address City"
            },
            "state":{
               "type":"string",
               "description":"Address State"
            },
            "zipcode":{
               "type":"integer",
               "maxLength":5,
               "minLength":5,
               "description":"zipcode"
            }
         }
      }
   }
}
```

**Comment by lepinay** [comment]
@jontonsoup  thanks for the json, I can reproduce the issue and have something to debug. By looking at the json, things seems ok...so probably a corner case I need to figure out.

**Comment by jontonsoup** [comment]
Sounds good — let me know if there is anything I can do to help.

**Comment by lepinay** [comment]
@jontonsoup found the issue, working on a fix.

**Comment by webron** [comment]
@lepinay - once you push the fix, I'll spend some time trying to break it myself ;) If all is well, we'll be happy to review the code and merge it :)

**Comment by lepinay** [comment]
@jontonsoup This is fixed. What was actually happening is that the ;iddleware you are using leaves out all the "type='object'" int the generated schema. JSonEditor is a bit strict on this, so I made a PR [here](https://github.com/jdorn/json-editor/pull/512]) to help infer that case.

But IMO I think the middleware should set this property, plus I've also noticed the generated JSON spec is much larger than what is generated by swagger.io (around 4 times) because it seems not be using $ref and instead re-expand everything.

Anyway let me know if you find anything else, I'm on the hunt for those corner cases :hurtrealbad: 

@webron 
I've been playing with http://petstore.swagger.io/v2/swagger.json and /user/createWithArray /user/createWithList it seems not to be working for this scenario (posting an array of object directly).
So I need to figure out that one now :)

**Comment by webron** [comment]
Okay, sounds good. I'd suggest using the swagger-editor examples too for testing if you have the capacity.

**Comment by jontonsoup** [comment]
@lepinay thanks! That's great.

**Comment by lepinay** [comment]
@webron for  /user/createWithArray and /user/createWithList I think the issue is actually in the schema rather than in the code for the editor. The type used for the root in the schema is set to 'object' instead of 'array', that's why things don't display properly. If I change it to 'array' things work as expected.

**Comment by kulkarniankita** [comment]
Will this also fix: https://github.com/swagger-api/swagger-ui/issues/1478

**Comment by lepinay** [comment]
@kulkarniankita Unfortunately it won't fix this issue because it is limited to only POST body not query parameters.

**Comment by lepinay** [comment]
@webron been through all examples on http://editor.swagger.io/ but only the pet store api provides POST with a json body. Are you aware of any other API I could test this on ?

**Comment by grokify** [comment]
@lepinay The [RingCentral API](https://developer.ringcentral.com/api-docs/latest/index.html) also consumes POST JSON bodies. We are currently working on updating the spec and would like to use this capability. You can try the following for testing purposes:

Lastest Spec: http://ringcentral.github.io/api-explorer-beta/swagger-ring.json
Update: https://api.swaggerhub.com/apis/fehguy/ringcentral-api/1.0

You can see a JSON body example here: http://ringcentral.github.io/api-explorer-beta/#!/Messages/v1_0_account__accountId__extension__extensionId__sms_post

Any thoughts on when this can be merged?

**Comment by lepinay** [comment]
@grokify At the moment this PR is waiting for review/feedback (@webron). Thanks for the endpoint it is really valuable to me. I'll give it a go this week.

**Comment by lepinay** [comment]
@grokify I've deployed the UI here http://thomsonreuters.github.io/swagger-ui/ if you want to have a check, you will probably spot issues faster than me. Since your API is quite extensive, it might take me a while to test it, but that will be definitively helpful, there are a lot of stuff there :+1:

**Comment by frol** [comment]
@lepinayl This is an awesome PR! Thank you for your work! However, the images in the dist folder are broken, please, revert the changes. I was bumping my head debugging JS tryng to find what get broken and only an hour later I realised that I'm just missing an image for "On/Off" switch!

**Comment by lepinayl** [comment]
@frol Thanks for pointing out the images issue, it's fixed now.

**Comment by frol** [comment]
@lepinayl I've been using your fork for the last 3 days and it has been working great even on semi-complex nested schemas! Great job!

I have spotted only one minor bug. JSON Editor ignores validation of required fields and sends empty string values instead of preventing sending the data. Here is my endpoint config:

```json
"post": {
    "operationId": "post_users",
    "parameters": [
        {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
                "properties": {
                    "username": {
                        "description": "Example: root",
                        "location": "json",
                        "type": "string"
                    },
                    "password": {
                        "description": "No rules yet",
                        "location": "json",
                        "type": "string"
                    }
                },
                "required": [
                    "username",
                    "password"
                ]
            }
        }
    ]
}
```

P.S. It would be nice if JSON Editor might use free space of "Description" column to be wider.

**Comment by lepinayl** [comment]
@frol Thanks for the kind feedback, I'll look into that issue.

**Comment by frol** [comment]
@lepinayl I caught one more minor bug - re-adding (add -> remove -> add) a new item to a list results in ignoring (not-showing) non-required fields (see `value` field on the screenshot):

screenshot from 2015-11-22 18-33-36

Here is my endpoint specification:

```json
"patch": {
    "operationId": "patch_user_by_id",
    "parameters": [
        {
            "in": "path",
            "name": "user_id",
            "required": true,
            "type": "integer"
        },
        {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
                "items": {
                    "properties": {
                        "op": {
                            "enum": [
                                "replace",
                                "remove",
                                "test",
                                "add"
                            ],
                            "location": "json",
                            "type": "string"
                        },
                        "path": {
                            "enum": [
                                "/password",
                                "/email",
                            ],
                            "location": "json",
                            "type": "string"
                        },
                        "value": {
                            "location": "json",
                            "type": "string"
                        }
                    },
                    "required": [
                        "op",
                        "path"
                    ]
                },
                "location": "json",
                "type": "array"
            }
        }
    ]
}
```

**Comment by agongdai** [comment]
@lepinayl There is a bug after "Delete last item" of an array: the "Move Down" button of the last item remains.

**Comment by grokify** [comment]
Here's a updated implementation of the JSON Body Editor with the RingCentral API Spec:

1. http://ringcentral.github.io/api-explorer-beta/
2. http://ringcentral.github.io/api-explorer-beta/#!/Messages/post_v1_0_account_accountId_extension_extensionId_sms

We found that our property descriptions were long enough that it created too much vertical space so we've implemented an initial approach to convert these descriptions to tooltips.

**Comment by lepinay** [comment]
@agongdai I've been trying to reproduce the issue on http://thomsonreuters.github.io/swagger-ui/ but with no success, could you double check if you have the issue there ?

**Comment by lepinay** [comment]
@grokify I like the idea of the tooltip, if you have time to make a PR on https://github.com/thomsonreuters/swagger-ui/tree/JSONEditorMaster with a feature toggle in swagger options (some people might prefer to use the current version) then I will merge it.

**Comment by frol** [comment]
@lepinay I have easily reproduced the issue reported by @agongdai. Note that the issue can be reproduced only with "Delete Last Item" button, while it works as expected when using regular "Delete Item" button.

**Comment by lepinay** [comment]
@frol Thanks got it now

**Comment by fehguy** [comment]
First off, thank you again for keeping this PR going.  The delay merging has been on our side.

Next, I'm setting the editor to off by default, and we'll update the documentation.  

Finally, it's getting merged into master now.  Thanks again!

**Comment by lepinay** [comment]
@fehguy Thanks for the merge, it will definitively help other interested into that feature to contribute and help manage bug fixes more efficiently. I'll now focus on getting the pending PR I have at jdorn/json-editor to be merged so that we can rely on the official version instead of the custom built one coming with this PR.

**Comment by fehguy** [comment]
Yes, again many thanks for the patience, and apologies for the delay on merging.  I did default it to `false` in the index.html for now, which is breaking the tests, but that will be fixed soon.

**Comment by grokify** [comment]
@lepinay Thanks for the suggestion for a tooltip PR. There's a dependency on getting an PR into jdorn/json-editor first. Once that's been done we can work on a PR for the JSON body editor.

**Comment by lucasweb78** [comment]
Would it be possible to be able to toggle between the json-editor and text field, rather either having to use one or the other? In some cases the editor is simpler to use and in others the text field is easier.

**Comment by webron** [comment]
@lucasweb78 It's hard trying to make everything configurable at that level. This is not only about code, but about UX. Having you and others wanting this feature doesn't mean others would want it as well. However, this being an open source project with a permissive license allows you to customize the code to your own needs. We're not offended by it, we even encourage you to do so.

**Comment by atdiff** [comment]
With this update, is the payload now getting validated within the editor as well?  It'd be cool if it compared the JSON payload returned to the Swagger schema.

**Comment by lepinay** [comment]
@atdiffthis unfortunately no...

**Comment by atdiff** [comment]
Bummer. Thanks @lepinay.  Do you know if there are plans to integrate that as an option at some point?  I might log it as an issue if not.

**Comment by lepinay** [comment]
@atdiff No there are no plans to share functionality between the two. I think it might be a good idea to raise that as a separated issue for the standard editor only.

**Pull request merged**
