### PR TITLE
Read the x-example field and use them as values

### LINKED ISSUE #2874: Example value not pre-populated
Previously, the @ApiParam example property value was used to pre-populate the input field. In 3.0.X, after pressing "Try it out", the input field remains blank.

### PR DESCRIPTION
**Pull request by dawez**
Fixes #2874.

Allows to show the value defined in the "x-example" field when pressing try-out. The "default" value will have the precedence over the x-example.

### CODE REVIEW

**Comment by webron** [comment]
Thanks for this. I'm not sure it follows the implementation in 2.x though. `x-example` was only valid to non-body parameters. Body parameters supported the `x-examples` property which had a more complex structure.

**Comment by mikeldpl** [comment]
@shockey  @dawez 
Hi guys.
Could you please assume when this feature will be merged?
We need this functionality ASAP.

Thanks in advance.

**Comment by webron** [comment]
@dawez - @shockey and I just discussed this. We need to make a minor change to it but should be merged soon.

**Comment by shockey** [comment]
thanks, @dawez! 🎉

**Pull request merged**
