### PR TITLE
Fix a null pointer in OperationView.js in headers

### PR DESCRIPTION
**Pull request by TomDataworks**
The check for "Download" content type in OperationView.js does not
determine if the header is available before checking the regular
expression. If the header is not available, then the operation will
fail and the behavior will resemble:

https://github.com/swagger-api/swagger-ui/issues/1109

This issue appears to extend to other content types, including
application/yaml, or any not explicitly defined before the
"Download" conditional. Simply checking for a null value before
testing the regular expression is enough to get things to work
properly again.

### CODE REVIEW

**Comment by Arven** [comment]
Should read that it applies to application/yaml, not application/xml.

**Comment by webron** [comment]
@mohsen1 - can you please review this one? I imagine it'd need a rebase but no point asking for one if it's not the right solution.

**Comment by mohsen1** [comment]
Null pointer is one issue, the other issue is we're using `.test` on strings. It should be on the RegEx.


`(headers['Content-Disposition'] && headers['Content-Disposition'].test(/attachment/))` should be `(headers['Content-Disposition'] && (/attachment/)).test(headers['Content-Disposition'])`

**Comment by webron** [comment]
@TomDataworks - can you rebase the PR and make the additional change @mohsen1 suggested? Looks like this could help us solve several issues.

**Comment by rswijesena** [comment]
I tested PR manually, Error: TypeError: headers['Content-Disposition'] is undefined is fixed now.
Thanks.

**Pull request closed without merging**
