### PR TITLE
Allow Custom Nginx Port in Docker

### PR DESCRIPTION
**Pull request by pseudomuto**
@shockey 

### Description

Adding the ability to use a custom port for Nginx within the docker container.

### Motivation and Context

In some environments, it can be desirable to specify a custom port to use within the container. Specifically, I'm referring to Kubernetes, where all pods within a deployment are addressable (to each other) via `localhost`. This means that within a deployment, we can't have multiple side car pods/containers listening on the same port.

Normally, this isn't an issue. But when there are multiple hardcoded ports it can be difficult to get things working without having to create services to map ports and separate deployments.

### How Has This Been Tested?

* `docker build -t swaggertest .`
* `docker run --rm -it -p 8900:8709 -e PORT=8709 swaggertest`
* `open http://localhost:8900`
* 🎆  🍾 

I also added a _.dockerignore_ file to decrease the build context size (faster docker builds). It went from ~195MB to ~18MB.

### Types of changes

- [x] No code changes (changes to documentation, CI, metadata, etc)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality) 
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by shockey** [comment]
> I also added a .dockerignore file to decrease the build context size (faster docker builds). It went from ~195MB to ~18MB.

Nice!

I'll review this before the end of the week, thanks @pseudomuto!

**Comment by shockey** [comment]
Merged.

Thanks, @pseudomuto!

**Comment by pseudomuto** [comment]
Sweet! Thanks, man. Is there a normal schedule you follow for pushes to docker hub? (Can you tell I'm excited to drop my custom image :smile:)

**Comment by shockey** [comment]
Yes! We run releases every Friday, so this will be live in three hours or so.

**Pull request merged**
