### PR TITLE
Support multiple SwaggerUi objects in a single HTML page

### PR DESCRIPTION
**Pull request by aleung**
Fixes swagger-api/swagger-ui#1069
Verified.

### CODE REVIEW

**Comment by mohsen1** [comment]
@aleung please run `gulp` to make new set of dist files with this change

**Comment by aleung** [comment]
@mohsen1 I have built dist files but I didn't commit them. Because my pull request doesn't include latest changes in your develop_2.0 branch, I wondered I should not commit the dist files which aren't built from latest code.

Shall I merge upstream develop_2.0 first and re-issue the pull request?

**Comment by mohsen1** [comment]
Yes please do rebase from develop_2.0 and commit your dist after that.

**Comment by webron** [comment]
@mohsen1, @aleung - any updates here?

**Comment by aleung** [comment]
I agree with @pedrosland's comment. Now it's a dirty fix but works fine. Changing id to class will impact more code. I'm afraid I haven't enough knowledge on this project to update it.

**Comment by aleung** [comment]
@webron Read for merge.

**Comment by fehguy** [comment]
added this logic

**Pull request closed without merging**
