### PR TITLE
Remove IE7 CSS hack

### PR DESCRIPTION
**Pull request by silverwind**
### Description
Remove this [star property hack](https://stackoverflow.com/a/14927670/808699) that was targeting IE 5.5 to 7. 

### Motivation and Context

It causes warnings during ESBuild's CSS minification and IE 7 is unsupported anyways.

```
warnings when minifying css:
 > <stdin>:192:30201: warning: Expected identifier but found "*"
    192 │ ...fter{clear:both}.swagger-ui .cf{*zoom:1}.swagger-ui .cl{clear:le...
```

### How Has This Been Tested?
Did not test, but risk is essentially zero because only IE 5.5 to 7 are supposed to recognize such properties. All other browsers will just fail to parse it and skip over the unknown property.

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by char0n — APPROVED** [review]
Thanks for contributing!

Your absolutely right. We can remove this as we claim this in our browser support section of readme:

> Swagger UI works in the latest versions of Chrome, Safari, Firefox, and Edge.

**Comment by frozenbonito** [comment]
`dist/swagger-ui.css` still contains star property hack.
It seems to come from [tachyons-sass](https://github.com/tachyons-css/tachyons-sass).
https://github.com/tachyons-css/tachyons-sass/blob/2dce89b83729bddb9f4498c7d6f82b73d60d6538/scss/_clears.scss#L21

**Comment by silverwind** [comment]
Regarding `tachyons-sass` issue, I opened https://github.com/tachyons-css/tachyons-sass/pull/63, but I think chances for a merge are slim as the module appears abandones, so `swagger-ui` is better off replacing this dependency.

**Comment by Bykiev** [comment]
Maybe migration to Tailwind CSS or Bootstrap is better way to solve the issue? I'd like to contribute on this

**Comment by silverwind** [comment]
Hack to get rid of the rule:

```sh
perl -p -i -e 's#.swagger-ui \.cf\{\*zoom:1\}##g' node_modules/swagger-ui-dist/swagger-ui.css
```

**Pull request merged**
