### PR TITLE
Handle relative urls for oauth authorization

### LINKED ISSUE #5243: Handling of relative urls for Oauth2 authorizationUrl and tokenUrl
### Q&A (please complete the following information)
 - OS: Linux
 - Browser: Firefox
 - Version: 65
 - Method of installation: Docker (via official hub image)
 - Swagger-UI version: v3.21.0
 - Swagger/OpenAPI version: 3.0.2

### Content & configuration

I'm in the process of documenting my OAuth2 endpoints, and have the following definitions:

```yaml
openapi: "3.0.2"
info:
  version: "1.0.0"
  title: "Funkwhale API"

servers:
  - url: https://demo.funkwhale.audio/api/v1
    description: Demo server
  - url: https://{domain}/api/v1
    description: Custom server
    variables:
      domain:
        default: yourdomain
        description: Your Funkwhale Domain
      protocol:
        enum:
          - 'http'
          - 'https'
        default: 'https'

components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /authorize
          tokenUrl: /api/v1/oauth/token/
```

As you can see, I have multiple servers configured, with a dynamic domain, because my API can be deployed in multiple places. The `authorizationUrl` and `tokenUrl` are relative.

### Describe the bug you're encountering

Based on what is described in [Swagger's documentation](https://swagger.io/docs/specification/authentication/oauth2/):

> Relative Endpoint URLs
>
> In OpenAPI 3.0, authorizationUrl, tokenUrl and refreshUrl can be specified relative to the API server URL. This is handy if these endpoints are on same server as the rest of the API operations. 

I expect the relative urls in the oauth definition to be resolved to the current API server. That is, if my server is `https://demo.funkwhale.audio/api/v1`, the authorization URL should be `https://demo.funkwhale.audio/api/v1/authorize`.

However, I don' observe that behaviour, and when trying to authenticate with OAuth, I'm redirected to `http://localhost:8002/authorize` instead. `http://localhost:8002` is the url of my Swagger UI, so I think the relative url is actually resolved on the swagger UI URL, and not the current API server URL.

### To reproduce...

1. Add an oauth definition to your swagger.yml file with a relative URL as the autorizationUrl value
2. Try to authenticate with oauth
3. Observes that you are redirected to the relative URL you specified but on the Swagger UI host, instead of the API server.

### Expected behavior

I expect the relative urls in the oauth definition to be resolved to the current API server. That is, if my server is `https://demo.funkwhale.audio/api/v1`, the authorization URL should be `https://demo.funkwhale.audio/api/v1/authorize`.

### Additional context or thoughts

Let me know if you need any additional info :)

### PR DESCRIPTION
**Pull request by EliotBerriot**
Closes #5243 and #3992

The full URL is computed based on the current selected server
if a relative URL is used as authorizationUrl or tokenUrl

### Description

Ensure we support relative `authorizationUrl` and `tokenUrl` (relative to the server endpoint) with OAuth.

I'm not sure if this can break backward compatibility, just let me know if you need any change :)

### How Has This Been Tested?

- Unit tests
- Manually on my personal projects/swagger UI definition
- With variable in servers urls

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shockey** [comment]
@EliotBerriot thanks for this, your implementation is well-architected 👍

Have you tested this with an OpenAPI 2.0 definition? All the `oas3Selectors` return null in 2.0.

**Comment by EliotBerriot** [comment]
thanks @shockey, I'll try that and let you know :)

**Comment by EliotBerriot** [comment]
@shockey I've tested locally with a swagger 2.0 file and the full oauth flow seems to work. I've pushed an additionial safeguard just in case. :)

**Comment by EliotBerriot** [comment]
@shockey is there anything I can do to proceed here? The CI build failed but it was apparently aborted on the jenkins node, and I don't find a way to relaunch it.

**Comment by shockey** [comment]
@EliotBerriot yep, one sec, I'll trigger it again

**Comment by shockey** [comment]
please build

**Comment by EliotBerriot** [comment]
it passed :tada:

**Comment by hthetiot** [comment]
Rebase? Thank you for PR!
@EliotBerriot

**Comment by EliotBerriot** [comment]
@hthetiot: just did that, it should be up to date now :)

**Comment by shockey** [comment]
bumped into the lack of support for this myself today...

(FYI: we haven't forgotten about this, or any, of our open PRs! we have a big branch we've been working on internally that needs to land on master before we merge more community PRs -- should be resolved in a matter of weeks.)

**Comment by dereksdev** [comment]
Is this going to be merged in anytime soon? Is there a workaround currently?

**Comment by FBlass** [comment]
Any updates on this?

**Comment by pszalko** [comment]
I just want to notice that it was almost a year since the original PR.
Someone put the effort to make the PR, few others are waiting for the PR to be merged, and all we need is just a click on the button from someone in the collaboration team.

Please merge this PR.

**Comment by EliotBerriot** [comment]
Can someone from the team have a look at this please?

**Comment by tim-lai** [comment]
@EliotBerriot Thanks for the PR and patience! Can you rebase and resolve merge conflicts? Once done, should be good to go!

**Comment by EliotBerriot** [comment]
@tim-lai I'm sorry, I currently lack the time and energy to do so. Can someone else take over and finish this?

**Comment by tim-lai** [comment]
merged via PR #6546

**Pull request closed without merging**
