### PR TITLE
fix params showing as undefined

### PR DESCRIPTION
**Pull request by jt1796**
This fixes:

https://github.com/swagger-api/swagger-ui/issues/2381

### CODE REVIEW

**Comment by darrenleeweber** [comment]
Can we get a new release version for this fix?

**Comment by fehguy** [comment]
We will soon, looking into one other issue first.

**Comment by sukrit007** [comment]
👍  for the fix.  Waiting for the release.

**Comment by fehguy** [comment]
2.2.4 just hit npm.

**Pull request merged**
