### PR TITLE
improvement: expose docExpansion setting as a prop in swagger-ui-react

### PR DESCRIPTION
**Pull request by laurence-hudson-mindfoundry**
### Description
Adds a `initialDocExpansion` prop to swagger-ui-react which acts a value for swagger-ui's docExpansion configuration setting.

### Motivation and Context
I needed to be able to set docExpansion to "full" so that my APIs swagger-ui-react was fully expanded by default. This allows that through an `initialDocExpansion` prop. I've added the "initial" prefix to re-enforce that this prop is only applied on mount.

### How Has This Been Tested?
Manually added the same changes to the transpiled JS in the swagger-ui-react npm package. Correct behaviour observed.

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.
> The new prop is not marked as required, if omitted `swagger-ui`'s default value (`list`) will kick in (as per current behaviour).

### Documentation
- [ ] My changes do not require a change to the project documentation.
- [x] My changes require a change to the project documentation.
- [x] If yes to above: I have updated the documentation accordingly.
> Just the `swagger-ui-react` readme.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.
> There is no testing in place for `swagger-ui-react` yet.

### CODE REVIEW

**Comment by shockey** [comment]
Thanks for this, @laurence-hudson-mindfoundry!

As you've noticed, Swagger UI's core has some limitations around config values being reliably updated and propagated through the React application. I hope to address this soon by refactoring the config system itself (likely by modifying the configs to live in our Redux store, and eliminating the use of `getConfig` in non-container components)... in the meantime I'd like to avoid introducing a set of `initial*` props, then having to keep them around once the config limitations are fixed. 

With that in mind, I'm planning to do the following:
- modify the PR to introduce `docExpansion` instead of `initialDocExpansion`
- keep the "on mount only" warning you have in the docs
- someday: polish off the config system changes, transparently remove the `docExpansion` limitation and scrub the warning from the docs

**Comment by shockey** [comment]
thanks @laurence-hudson-mindfoundry!

**Comment by laurence-hudson-mindfoundry** [comment]
Great, any plan when the next release will be?

RE the longer term plan for the other config options, I did consider sending you this https://github.com/swagger-api/swagger-ui/compare/master...laurence-hudson-mindfoundry:config-props?expand=1 as a PR instead, which would have added props for all of the config options, but didnt have the time to five it the testing it needs.

**Comment by nightowlengineer** [comment]
+1 for adding in the additional configuration options as per @laurence-hudson-mindfoundry's comment above. I had to switch to the React flavour to fix #4745 but doing so has stopped the alpha sorting of tags/models etc.

**Pull request merged**
