### PR TITLE
Fix #779 Expand Operations link not working

### LINKED ISSUE #779: Expand operations tab not able to get it to work
Hey,

So I am using pretty much the standard swagger UI index page , but my UI doesn't seem to expand the operations of my api's on clicking. Is there some specific details that need to be part of the index page or the swagger document?

### PR DESCRIPTION
**Pull request by bakaat**

### CODE REVIEW

**Comment by deepthienagalur** [comment]
Did you guys update the swagger-ui.js with the fix yet? i tried to add it manually, but i think I didn't do it right

**Comment by bakaat** [comment]
Looks like it's already there

**Comment by webron** [comment]
@deepthienagalur - it should be in master

**Comment by deepthienagalur** [comment]
thanks

**Comment by deepthienagalur** [comment]
i took the master version and i am not able to view any of my api's. I don't see any activity in my network as well.. If you can tell me what exactly was the change, i can just make that change for my current version in our project. I can email you separately if you like.

**Comment by webron** [comment]
Any chance you can share your spec?

**Comment by deepthienagalur** [comment]
I can email it to you

**Comment by webron** [comment]
That would work.

**Comment by deepthienagalur** [comment]
I sent it to fehguy's email since that's the only one i see

**Comment by webron** [comment]
I don't have access to @fehguy's email (yet :wink:). You can find my email in the google group.

**Comment by webron** [comment]
no worries, he's forwarding it to me.

**Pull request closed without merging**
