### PR TITLE
Added support for oauth2-password-flow (refactored #1574)

### PR DESCRIPTION
**Pull request by frol**
It is based on #1574. However, I made some refactoring and merging with the master branch, so multiple Security Schemes should be supported.

### CODE REVIEW

**Comment by frol** [comment]
@pusherman I have created this PR based on your code, but with some refactoring and merging to the current state, where Client Credentials (application) Flow was recently added, and multiple Security Schemes support. My PR seems to work fine with Resource Owner Password Credentials Flow, but it would be helpful if you could also confirm this. 

@TomDemeranville I've seen that you have contributed Client Credentials (application) Flow. Could you please try my PR against this kind of flow (and any other if you have a chance)? I don't have a OAuth2 server with this flow enabled in place to test it out completely, but in theory it should work unless there is a typo somewhere.

Everybody is welcome to try it! :)

**Comment by frol** [comment]
@fehguy Could you please review the change? I have a RESTful API server with OAuth2 Password Flow available for test on http://example-restful-api.prostoksi.com/api/v1/ (this is running from https://github.com/frol/flask-restplus-server-example)

**Comment by fehguy** [comment]
@frol I've been waiting on #2014 to be merged, then work this in.  Sorry for that delay--it may be worth taking a look at that PR which makes the authentication process fully driven by the spec, and pluggable.

**Comment by frol** [comment]
@fehguy I've just looked at that PR. It certainly looks nice and makes code cleaner. However, it doesn't have OAuth2 Password Flow, so it doesn't work with my server, which has implemented only Password Flow at this point of time. I will take a closer look at how to integrate OAuth2 Password Flow into the new Auth implementation once that PR is merged.

Cheers!

**Comment by Ciantic** [comment]
umm, I've got same situation. I only want to have password flow, and swagger ui can't show me username/password field.

**Comment by frol** [comment]
I'm closing my PR since it is outdated. Auth implementation was greatly refactored since I proposed this PR.

**Pull request closed without merging**
