### PR TITLE
fix(style): response data flows off the screen

### LINKED ISSUE #6749: Response data no longer wraps text and flows off the screen.
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 87.0.4280.88
 - Method of installation: dist assets
 - Swagger-UI version: 3.38.0
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0

### To reproduce...

1. Go to https://editor.swagger.io/#
2. Post a pet with a really long name
3. Scroll down to the response

### Expected behavior
Response data no longer wraps text and flows off the screen.

### Screenshots
editor.swagger.io
Screen Shot 2020-12-28 at 1 05 20 PM

swagger-ui 3.37.2
Screen Shot 2020-12-28 at 12 43 29 PM

swagger-ui 3.38.0
Screen Shot 2020-12-28 at 12 45 08 PM

### PR DESCRIPTION
**Pull request by mathis-m**
### Description

Response data no longer wraps text and flows off the screen.
Fixed it by changing:
```css
code {
      background-color: #dedede;
      padding: 4px 4px 2px;
      white-space: pre;
 }
```
To:
```css
code {
      background-color: #dedede;
      padding: 4px 4px 2px;
      white-space: pre-wrap;
      word-break: break-all;
 }
```

### Motivation and Context

Fixes #6749

### How Has This Been Tested?

browser

### Screenshots (if appropriate):
Before:
image
After:
image

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by watery** [comment]
Can you test this with a single long word (no spaces)? I hit this issue with a JWT token that I can no longer copy from the UI.

**Comment by mathis-m** [comment]
Would look like this: image

**Comment by watery** [comment]
> 
> 
> > Can you test this with a single long word (no spaces)? I hit this issue with a JWT token that I can no longer copy from the UI.
> 
> Would look like this:
> image

Very good. Thank you.

**Comment by tim-lai** [comment]
@mathis-m PR is now merged! Thanks for the contribution!

**Pull request merged**
