### PR TITLE
Support RFC 6570 optional path segments

### PR DESCRIPTION
**Pull request by gwicke**
This adds support for the substitution of RFC 6570 optional path segments in
swagger-client. Example:

 /some/path{/optional}{/path}

This patch is rather simple and limited. For example, it does not properly
handle order constraints. A better solution would be to use one of the
existing RFC 6570 libraries. One candidate for this would be
https://github.com/bramstein/url-template.

### CODE REVIEW

**Comment by webron** [comment]
That's not supported by the spec so it cannot be supported by the UI.

**Comment by gwicke** [comment]
@webron, I don't see an explicit mention either way in the spec. I did find a few inconclusive discussions on the subject, so went ahead & implemented it.

**Comment by webron** [comment]
The spec explicitly says that path parameters are always mandatory, and as such cannot be optional. 
Indeed, there have been talks about it and I expect it to be part of the next version of the spec. 

I do appreciate the effort in taking the time to create this PR, however we can't incorporate it if it doesn't correspond to the spec.

**Comment by gwicke** [comment]
@webron, thanks! Looking forward to 2.1 with URL template support.

**Comment by webron** [comment]
Currently, there's https://github.com/swagger-api/swagger-spec/issues/93. If you feel that doesn't cover enough, either add your input there or create a new issue with detailed information. That would help drive it forward. @maxlinc has good knowledge of it and together I'm sure we can come up with a stable solution for the next spec.

**Comment by gwicke** [comment]
@webron, commented there.

**Pull request closed without merging**
