### PR TITLE
Fixes #3032 - Wrong property order

### LINKED ISSUE #3032: Wrong Order
By looking at the screenshot below you will find that the order of the properties are wrong (Top right in screenshot).  I find that it only happens if the model have more than 8 properties: 

image

The YAML to test on http://editor.swagger.io is:

```
swagger: '2.0'
info:
  description: ''
  version: 1.0.0
  title: my API
basePath: /api/v1
tags:
  - name: params
    description: Parameters
paths:
  /params/layer:
    get:
      tags:
        - params
      summary: ''
      description: ''
      operationId: layer
      produces:
        - application/json
      parameters:
        - name: layerId
          in: query
          required: false
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Layer'
      security:
        - token: []
securityDefinitions:
  token:
    type: apiKey
    name: token
    in: query
definitions:
  Layer:
    type: object
    properties:
      layerId:
        type: integer
        format: int64
      layerType:
        type: string
      layerCaption:
        type: string
      layerDescription:
        type: string
      primaryField:
        type: string
      searchCaption:
        type: string
      isBaseLayer:
        type: boolean
      visibility:
        type: boolean
      opacity:
        type: number
        format: float
      minScale:
        type: integer
        format: int32
      maxScale:
        type: integer
        format: int32
      layerOrder:
        type: integer
        format: int32
      layerGroup:
        type: string
```

### PR DESCRIPTION
**Pull request by owenconti**
Fixes #3032 

`fromJS` does not maintain the order of the properties in the object. Instead, we use the optional [`reviver` function](https://facebook.github.io/immutable-js/docs/#/fromJS) to parse each property in the original `schema` object as an `OrderedMap`.

### CODE REVIEW

**Comment by shockey** [comment]
@owenconti can I get some Enzyme tests for this?

**Comment by owenconti** [comment]
Will do. I also found a `fromJSOrdered` in the utils.js file. I will try using that too.

**Comment by owenconti** [comment]
@shockey I've added a basic enzyme test for response.jsx. I've also created a PR to further test that the `<ObjectModel />` component is rendering properties in the order passed-in.

**Comment by shockey** [comment]
@owenconti thanks!

**Pull request merged**
