### PR TITLE
Will show headers on response messages

### LINKED ISSUE #1117: Response headers not being displayed for either 200 or other responses
Response headers not being displayed for either 200 or other results, error sample below shows the issue.

In the sample below the ETag header is defined for the parameters and for the 200 and 405 responses, but it's only being show for the parameters.

image

```
{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "Test sample showing swagger error",
        "description": "Show that response headers are not rendered",
        "contact": {
            "name": "Troels Liebe Bentsen",
            "email": "tlb@nversion.dk"
        }
    },
    "host": "localhost",
    "basePath": "/",
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/test": {
            "post": {
                "summary": "Test",
                "description": "Test stuff",
                "operationId": "doTest",
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/test"
                            }
                        }                       
                    },
                    {
                        "in": "header",
                        "name": "ETag",
                        "description": "Used as caching key for future requests",
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Test stuff response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/test"
                            }
                        },
                        "headers": {
                            "ETag": {
                                "description": "Used as caching key for future requests",
                                "type": "string"
                            }
                        }
                    },
                    "405": {
                        "description": "Invalid input",
                        "headers": {
                            "ETag": {
                                "description": "Used as caching key for future requests",
                                "type": "string"
                            }
                        }
                    }
                },
                "tags": ["test"]
            }
        }
    },
    "definitions": {
        "test": {
            "required": [
                "test1"
            ],
            "properties": {
                "test1": {
                    "type": "string"
                }
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by mklaus1**
Fixes #1117 by adding the headers to the status code model.

### CODE REVIEW

**Comment by DavidBiesack** [comment]
I tried this patch and did not see the expected results. 

It could be that I'm not updating swagger-ui dist folder correctly after applying the source change to `/src/main/javascript/view/OperationView.js` I ran 

```
gulp
```
then refreshed the Swagger UI in the browser. My swagger contain (snippet)

```
        '200':
          description: Resource created, data returned 
          schema:
            $ref: '#/definitions/resource'
          headers:
            Location:
              description: The location of the new resource
              type: string
```

Do I need to do something else to see the change?

**Comment by sawatzkylindsey** [comment]
@DavidBiesack I think the problem is this patch fixes showing the headers in non-`200` responses.  It worked for me, thanks @mklaus1!

**Comment by fehguy** [comment]
This has been added in a different PR

**Comment by vamsi-dev** [comment]
I had looked at this patch & tried it. Even after downloading the latest version of the swagger-ui, i do not see all the request headers that are visible in post-man.
I also tried pet store example in local. No use.
I don't how this can be resolved.
swagger-resp-headers

**Pull request closed without merging**
