### PR TITLE
it should not unnecessarily stringify string values for text/plain content type

### LINKED ISSUE #6430: Content Type text/plain should not be stringified
### Q&A (please complete the following information)
 - OS: [e.g. macOS] Windows 10 Pro
 - Browser: [e.g. chrome, safari] chrome
 - Version: [e.g. 22] Version 85.0.4183.102 (Official Build) (64-bit)
 - Method of installation: [e.g. npm, dist assets] raw code
 - Swagger-UI version: [e.g. 3.10.0] master @ 12ccab79d2df670d7157d23c38eb938f868d3f6f
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0] 3.0.1

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: SimpleAspNetCoreSample
  description: Sample App using MM Framework.
  version: v1.0.0-alpha
paths:
  /api/Sample:
    post:
      tags:
        - Sample
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              format: byte
              nullable: true
          text/json:
            schema:
              type: string
              format: byte
              nullable: true
          application/json:
            schema:
              type: string
              format: byte
              nullable: true
      responses:
        '200':
          description: Success
components: {}
```

### Describe the bug you're encountering

Sample for text/plain should not be stringified. Introduced with #6412 the json sample for type string will be stringified. This should only be the case if the content type is not text/plain.

### To reproduce...

explore provided yaml openapi definition.
change the content type. If it is text/plain the sample will be stringified.

### Expected behavior
Do not stringify type string if content type is text/plain.

### Screenshots
How it should look like:
image
image

### Additional context or thoughts
#6412

### PR DESCRIPTION
**Pull request by mathis-m**
### Description
Sample for text/plain should not be stringified. Introduced with #6412 the json sample for type string will be stringified. This should only be the case if the content type is not text/plain.

### Motivation and Context

Fixes #6430

### How Has This Been Tested?
in browser
by new tests

### Screenshots (if appropriate):

see #6430

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [x] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by hkosova** [comment]
The logic should probably be changed to apply JSON.stringify specifically to JSON media types (`application/json`, `application/vnd.api+json`, etc.) and ignore all other media types.

**Comment by mathis-m** [comment]
The json sample generation is the default case.
I have refactored the code to clarify the different cases.

**Comment by mathis-m** [comment]
@hkosova do you think it is better to use the old behavior(only stringify object values) before #6412 was merged as default sample case and introduce case for json content type where sting values will be stringified as well?
text/plain content type sample generation would then implicitly match the default case where only object values will be stringified.

**Comment by tim-lai** [comment]
> @hkosova do you think it is better to use the old behavior(only stringify object values) before #6412 was merged as default sample case and introduce case for json content type where sting values will be stringified as well?
> text/plain content type sample generation would then implicitly match the default case where only object values will be stringified.

@mathis-m I this suggestion is better. Revert to original behavior to only stringify object values, but add a function for an `allowList` for non-object values. e.g `if (object || allowList) { stringify }`

**Comment by mathis-m** [comment]
@tim-lai thanks for your input. Will implement this in the next days.

**Comment by mathis-m** [comment]
@tim-lai could you review the changes made.

**Comment by mathis-m** [comment]
while testing locally I observed that bugs\5072.js  jest test is failing.

**Pull request merged**
