### PR TITLE
Some style fixes for model container

### PR DESCRIPTION
**Pull request by neon-dev**
Unfortunately Swagger-UI has many odd formatting decisions and/or bugs. I tried to fix some easy ones.

### Description
For one the model box received some alignment and font size improvements:
standard fixed
(left before, right after)
Also in there is a fix for paragraphs (\<p> elements) which were too large, but that's not in the picture. Note: Such elements still have a too large margin in the Schemas box, so that's not fixed.

Then the text spacing in the Download button for responses got fixed as well.

### Motivation and Context
Aesthetics and usability

### How Has This Been Tested?
Only by applying committed changes via the browsers developer console. So please test it thoughoughly, since I don't have the time or motivation to struggle properly setting this project up :x
I think the CSS changes shouldn't break anything, but can't say for sure.

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by neon-dev** [comment]
The checks should not have failed, especially not oauth related ones.
Let me also add that my CSS changes surely aren't a perfect or complete solution. For example the model-toggle chevron in the Schemas section still jumps around and there are rendering differences between models there and the same models in the operation sections. Nevertheless I think that it's still an improvement.
And using !important wasn't my first choice, but moving blocks around would require more testing and certainly have a higher probability of introducing new style bugs.

**Comment by neon-dev** [comment]
@shockey I just updated the branch, anything else missing to make this good to merge for you?

**Comment by neon-dev** [comment]
@webron / @shockey I just updated the branch, anything else missing to make this good to merge for you?

**Comment by neon-dev** [comment]
@webron / @shockey what does it take to get a response ? :upside_down_face:
I'm offering non breaking minimal changes for a better UX. What's holding you back to merge this? Thanks.

**Comment by neon-dev** [comment]
@webron / @shockey happy new year. Any update on this topic?

**Comment by webron** [comment]
@neon-dev Sorry for the delayed response. At the moment, we're having a bit of a backlog when it comes to Swagger UI, which I hope to get resolved soon. In the mean time, I'd like someone from our UX team to take a look at the changes. Would you mind adding before/after pictures for all the changes?

**Comment by neon-dev** [comment]
@webron thanks for your reply. The changes pretty much can be all compared on the screenshots above in my first post. Minor spacing and font size fixes. I don't think I can show much more. Also don't have swagger set up anymore.

**Comment by tim-lai** [comment]
@neon-dev Thanks for the contribution. However, after further review, we are going to pass on merging this PR.

**Pull request closed without merging**
