### PR TITLE
Removed ReadOnly properties from the JSON Parameters body example

### PR DESCRIPTION
**Pull request by mattbryson**
This strips read only properties from the example parameters JSON, as PUT/POST ing them is a bit pointless.

They are still present in the model view.

The only file changed was the `src/main/javascript/view/partials/signature.js`  the rest are changes from building the app.

### CODE REVIEW

**Comment by webron** [comment]
@mattbryson did you intend to submit that against the 2.x branch? I'll be upfront and say it's unlikely we'll merge fixes against 2.x as we're focused on 3.x and don't have much capacity for more than that.

**Comment by webron** [comment]
Just saw the comment on the other issue, so I know this is intended to 2.x. So first, you need to change the PR to go against the right branch. Secondly, any chance you could provide something similar to 3.x instead? We'd love to merge it if it's all good.

**Comment by mattbryson** [comment]
Yeah, sorry, not sure how I made a PR for master, was supposed to be 2.x.   Ill update this to the correct branch for anyone else looking for it.

I'll have a look at the master branch, and see if I can port it over. Might have to be next week though.

**Comment by webron** [comment]
Thanks, @mattbryson.

**Comment by webron** [comment]
@mattbryson can you please resolve the conflicts?

**Comment by webron** [comment]
Thanks for the effort, @mattbryson - unfortunately I don't have anyone to review the ticket for 2.x, so I'm forced to close this one out. If you find it relevant for the current version, please resubmit against it.

**Comment by igorko** [comment]
@webron hello. Do you mean fix was not merged?

**Pull request closed without merging**
