### PR TITLE
'available authorization' popup: only show oauth2 scopes relevant for current endpoint (issue #8219)

### PR DESCRIPTION
**Pull request by kai-morich**
### Description

Endpoint specific filtering of oauth2 scopes for 'available authorization' popup

### Motivation and Context

Issue #8219

### How Has This Been Tested?
- existing `plugins/auth/selectors.js` unit test did not need modifications as pet-store adds all scopes everywhere
- manually tested against scenario at #8219 
- manually tested against some openapi 2 and 3 definitions

### Screenshots (if appropriate):

**Before**:

GET /pets

image

**After**:

GET /pets
image

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tim-lai** [comment]
@kai-morich Thanks for the PR! It looks very promising! I think it would be beneficial to add Cypress E2E tests to cover and replicate in CI all of the manual testing that you have done so far. 

Separately, this PR seems like it might also obsolete the need for https://github.com/swagger-api/swagger-ui/pull/7712, by hiding non-relevant fields? Not sure, but would like to get your thoughts.

**Comment by kai-morich** [comment]
i will look into automated tests, but I don't think it is related to #7712. The number of input boxes is not affected by my change, only the number of scopes listed below

**Comment by kai-morich** [comment]
added unit tests for new functionality (oauth2 scope filtering) and for existing functionality (security filtering)

**Comment by tim-lai** [comment]
@kai-morich PR merged! Thanks for the fix and contribution!

**Pull request merged**
