### PR TITLE
Add more e2e tests

### PR DESCRIPTION
**Pull request by mohsen1**

### CODE REVIEW

**Comment by fehguy** [comment]
@mohsen1 do the tests pass for you locally?  I suggest we host the swagger spec on your mock server and use the 'url' query param to load it on startup

**Comment by mohsen1** [comment]
It did pass locally. Is specs now a single file?

**Comment by fehguy** [comment]
Yes you can use this:

https://github.com/swagger-api/swagger-spec/blob/master/examples/v2.0/json/petstore.json

They fail for me locally and Travis seems mad too. I got a cors error in the error messages

**Comment by mohsen1** [comment]
Closing in favor of #893 

My tests caught my own bug!

**Pull request closed without merging**
