### PR TITLE
Remove forced width on model display

### PR DESCRIPTION
**Pull request by gareth-ib**
### Description
For the first cell in the model display tables, removed the hard set 174px width and gave it a 1em right padding.
Now deep structures fit much better on the screen horizontally

### Motivation and Context
The model display mode was too horizontally expended to follow easily visually

results fit as shown here:

image

### CODE REVIEW

**Comment by gareth-ib** [comment]
also tighten up the input options display

image

**Comment by heldersepu** [comment]
I don't think the CSS changes are made directly on the dist directory

**Comment by gareth-ib** [comment]
yeah I didn't notice the source scss files before, I have them both committed now

**Comment by heldersepu** [comment]
@gareth-ib I only see one file changed:
https://github.com/swagger-api/swagger-ui/pull/4666/files
And you do not need to make the change on both places only in the scss, the other is compiled after merge

**Comment by shockey** [comment]
I'm going to close this out - we have some UI/UX changes in the pipeline that are overhauling the components in question here.

@gareth-ib, nonetheless, thank you for the PR 😄 even the ones we don't merge inform our strategy for what we work on in the project.

**Pull request closed without merging**
