### PR TITLE
Allow local ref's to be served by nginx

### PR DESCRIPTION
**Pull request by waterkip**
This changeset uses the directory name of the SWAGGER_JSON file to use
as a root for all the files that have the following {json,yml,yaml}
extension.

By doing this one can use a docker-compose.yml like so:
```
environment:
- "SWAGGER_JSON=/openapi/foo.yaml"
volumes:
- "./openapi:/openapi"
```
or run docker like described in the installation.md file:
```
docker run -p 80:8080 \
-e SWAGGER_JSON=/foo/swagger.json -v /bar:/foo swaggerapi/swagger-ui
```
Everything from /bar is mounted in /foo and /foo is than used by nginx
to serve it's openapi specification files.

Fixes: #5318, #5496, #4915

### How Has This Been Tested?

I manually tested my changes by running docker-compose with the configuration described above and manually by running `docker run -p 8081:8080 -e "SWAGGER_JSON=/app/zd.yaml" -v $(pwd)/openapi:/app swaggerapi/swagger-ui`

### My PR contains... 

- [x] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by btkelly** [comment]
Is there a timeframe for merging this change into master and deployed? I would like to leverage this from the main DockerHub image to allow me to break my Swagger spec up into multiple files.

**Comment by stickgrinder** [comment]
Guys, any news on this? I tried this myself and it works like a charm. It allows me to break my huge API specs to separated files.

This is such a no-brainer that I wonder why this is not yet in master.

**Comment by waterkip** [comment]
Leave me a comment when you want to merge this so I can rebase it again. Rebasing every week is getting old.

**Comment by tim-lai** [comment]
@waterkip Merged, thanks for contribution!

**Comment by vanhove** [comment]
It looks like this change is causing a bug. When defining BASE_URL environment variable, the docker image is not able to find the json/yaml file.

**Comment by waterkip** [comment]
@vanhove Oops :) I'll have a look later today to see if I can reproduce and fix it.

**Comment by waterkip** [comment]
@vanhove could you see if this resolves the issue for you? https://github.com/swagger-api/swagger-ui/pull/6147

**Pull request merged**
