### PR TITLE
provide gulp target for iterating over local specs in development

### PR DESCRIPTION
**Pull request by seanpkps**
add targets to the gulpfile to simplify testing how various local specs display
(and modifying and looking again at those specs iteratively)

new gulp targets:

* **dev-dist**: [lint, copy]
    * this runs the same code in dist, but without doing a clean first
* **dev**: [default, serve]
    * the task to run if you're iteratively making changes and don't want/need the dist directory to be regenerated every time

### CODE REVIEW

**Comment by seanpkps** [comment]
will create a new pull request to pick up the code for the new `defaultModelRendering` option

**Comment by hlubovac** [comment]
I'm not sure if this is relevant, but option `defaultModelRendering` doesn't seem to have any effect. I can't find a single reference to it within the code (although I wasn't looking too hard; just a user here). Possibly related code is `SwaggerUi.Views.SignatureView > render`, where `this.switchToSnippet()` or `this.switchToDescription()` can be invoked based on that setting.

**Comment by seanpkps** [comment]
@hlubovac the latest version in the repository does have the `defaultModelRendering` option (delivered through PR #1770) working, but that doesn't look to be what's available through `npm` (which still has v 2.1.3)

@fehguy - what are the plans for pushing a 2.1.4 update to npmjs.org?

**Comment by webron** [comment]
@seanpkps - we're looking to include a few additional fixes. We estimate a new version would be pushed around the end of the month.

**Pull request closed without merging**
