### PR TITLE
fix(sample-gen): should return json literal example

### LINKED ISSUE #6595: Response examples line break not working
### Q&A
 - OS: macOS & windows
 - Browser: chrome & safari
 - Version: 3.36.2
 - Method of installation: npm
 - Swagger-UI version: 3.36.2
 - Swagger/OpenAPI version: OpenAPI 3.0

### Here an example of the result.

Parameters works fine.
Screen Shot 2020-11-08 at 16 58 21

But responses don't render the `\n`.
Screen Shot 2020-11-08 at 16 58 27

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  title: Pet store
  description: Add your description
  license:
    name: MIT
    url: ''
  termsOfService: ''
  version: 1.0.0
servers: []
components:
  schemas:
    Song:
      description: A song
      required:
        - title
      type: object
      properties:
        title:
          description: The title
          type: string
        artist:
          description: The artist
          type: string
        year:
          description: The year
          type: integer
          format: int64
    Pet:
      description: A pet
      required:
        - name
        - type
      type: object
      properties:
        name:
          description: The name
          type: string
        type:
          description: The type of pet
          type: string
        breed:
          description: The breed
          type: string
paths:
  /api/v1/pet:
    post:
      deprecated: false
      summary: ''
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Song'
            examples:
              example1:
                summary: payload example
                value: |-
                  {
                    "title": "Bury The Light",
                    "artist": "Casey Edwards ft. Victor Borba",
                    "year": 2020
                  }
              example2:
                summary: other payload example
                value: |-
                  {
                    "title": "The war we made",
                    "artist": "Red",
                    "year": 2020
                  }
        description: song info
        required: true
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
              examples:
                xml:
                  summary: A sample XML response
                  value: |-
                    '<objects>
                      <object><id>1</id><name>new</name></object><object><id>2</id></object></objects>'
                example1:
                  summary: example success response
                  value: |-
                    [
                       "example": "asdasd"
                    ]
                example2:
                  summary: second example success response
                  value: |-
                    [
                      {
                        "name": "Hachiko",
                        "type": "Dog"
                        "breed": "Akita Inu"
                      },
                    ]
        '403':
          description: forbidden request response
          content:
            application/json:
              schema:
                type: object
              examples:
                example3:
                  summary: example error response
                  value: |-
                    {
                      "message": "you cannot access pet data",
                    }
      parameters: []
      tags: []
tags: []
```

Swagger-UI configuration options:
The same as this library https://github.com/scottie1984/swagger-ui-express

### Describe the bug you're encountering
We found a problem with the response examples when we use editor.swagger.io. The line breaks are not working. This only happens on this website which is using v3.36.2 of this library. If we use [swagger-ui-dist](https://www.npmjs.com/package/swagger-ui-dist) this doesn't happen 🤔 we are using that library in [this package](https://github.com/BRIKEV/express-jsdoc-swagger) and the problem does not happen there, maybe that helps to find the solution.

### To reproduce

1. Go to https://editor.swagger.io/
2. Paste the yaml that I wrote above
3. Scroll down to responses

### Expected behavior
Example response adds a line break.

### Screenshots
Parameters works fine.
Screen Shot 2020-11-08 at 16 58 21

But responses don't render the `\n`.
Screen Shot 2020-11-08 at 16 58 27

### Additional context or thoughts
I think this problem appears after this [version](https://github.com/scottie1984/swagger-ui-express/blob/master/package.json#L49) because as I said in [this package](https://github.com/BRIKEV/express-jsdoc-swagger) the problem does not happen.

### PR DESCRIPTION
**Pull request by mathis-m**
### Description

The sample gen should, in case of json media type and string literal example, try to parse the example. If it can not parse the example like the xml example shown in issue(for media type json) it will return it like it is a json string example. 
In case it is parable it will return the json. This will result in rendering the json string literal examples as expected. 

### Motivation and Context

Fixes #6595

### How Has This Been Tested?

Have taken care to ensure that literals are generated as json. 

### Screenshots (if appropriate):
https://editor.swagger.io/?url=https://gist.githubusercontent.com/mathis-m/20bf8fb2deabd2a5a0821418aa4adacc/raw/df18fb826d8fac8a648250dfa4e9050672992cbf/Zs2qqBv9YU.txt

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [x] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tim-lai** [comment]
@mathis-m PR merged! Thanks for another contribution!

**Comment by smagafurov** [comment]
This merge breaks the schema:

```
openapi: 3.0.0
info:
  title: Probe
  version: 1.0.0
servers: []
components:
  schemas:
    Probe:
      type: object
      properties:
        probe:
          type: string
          example: '1.0'
paths:
  /api/v1/probe:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Probe'
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Probe'
```

"Example Value" incorrectly shown as:

```
{
  "probe": 1
}
```

Correctly expected as:

```
{
  "probe": "1.0"
}
```

**Comment by mathis-m** [comment]
> Fixes #6827:
> 
> https://gist.githubusercontent.com/mathis-m/6ccf292b5560fc09f50e52f2ad0f1e23/raw/f8b16efb750879d279e1c1fb3fffdb521b6dcad0/rxx6ldSupt.txt
> image
> _Originally posted by @smagafurov in https://github.com/swagger-api/swagger-ui/issues/6827#issuecomment-768512523_
>

**Comment by mathis-m** [comment]
@tim-lai Would it be a requirement that 1.0 is displayed instead of 1?

**Pull request merged**
