### PR TITLE
Markdown rendered tag descriptions.

### PR DESCRIPTION
**Pull request by erikvanzijst**
Added Markdown rendering to the tag descriptions as per the 2.0 spec
http://swagger.io/specification/#tagObject

This required some rejigging of the layout of the tag name itself.

It now looks like:

swagger ui 2015-09-14 14-37-24

### CODE REVIEW

**Comment by fehguy** [comment]
The tag description should be short--I believe the spec suggests ~140 chars.  Moving into markdown and a new line really makes it appear like a longer description.

**Comment by erikvanzijst** [comment]
Really? Is there a 140 char recommendation? I don't think I've seen that. It does state that it's to be interpreted as MD though.

**Comment by fehguy** [comment]
My bad--that's the operation `summary`, not the tag description.

**Comment by NilsLattek** [comment]
Hi guys, what's the status on this one?

**Pull request closed without merging**
