### PR TITLE
Hide "Try It Out" and "Authorize" buttons when no servers are specified

### PR DESCRIPTION
**Pull request by biochimia**
### Description

If a base URL for the server is not specified, it will not be possible
to interact with its API. As such, UI elements for the top-level
"Authorize" button along with the endpoint-specific "Try It Out" buttons
are not shown.

This reduces UI clutter with components that cannot be used.

Additionally, the container grouping Server lists, Schemes, and the
Authorize button is removed altogether if no URLs or schemes are
configured to avoid an empty container in that case.

### Motivation and Context

The motivation for this change is to reduce UI clutter when OpenAPI/Swagger specifications are missing server lists.

### How Has This Been Tested?

I built the bundle and tried it out with OpenAPI 3 spec files missing different combinations of the `servers` and `securitySchemes` sections.

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [ ] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by biochimia** [comment]
Thank you for taking the time to review this and offer comments, @shockey.

The OpenAPI Specification defaulting the server to `/` somewhat invalidates what I was attempting to do, but perhaps I can make this configurable, instead. In the default setup, the specification would be respected.

To expand a bit on the motivation, in my project, we're hosting documentation for different services under a common documentation portal. There, I know the server hosting the docs is not hosting the services, and can justify this deviation from the specification. In more general terms, I can see a point in keeping this decision outside the swagger/OpenAPI file, in case the `baseURL` varies or is client-specific.

What I'm looking for is a way to enable and disable both _Try It Out_ and _Authorize_ buttons functionality in a dynamic fashion based on information in the API spec that is being rendered. Initially, I tried to follow your suggestions in https://github.com/swagger-api/swagger-ui/issues/3314#issuecomment-362418815 and https://github.com/swagger-api/swagger-ui/issues/3725#issuecomment-334899276, but both of those disable the features before having a chance to look at the spec.

About the new `AuthContainer` I introduced, I don't have a use case for it, and split it out solely to keep the logic separate. Given the performance and maintenance impact, I can just as well keep the logic in `BaseLayout`, hiding the section if there are no `servers`, `schemes`, or `securityDefinitions` to display.

**Comment by shockey** [comment]
@biochimia:

> Initially, I tried to follow your suggestions in #3314 (comment) and #3725 (comment), but both of those disable the features before having a chance to look at the spec.

This is not impossible 😄 I've published a plugin that will achieve this for you: https://github.com/shockey/swagger-ui-plugins/blob/master/packages/disable-try-it-out-without-servers/README.md

> I don't have a use case for it, and split it out solely to keep the logic separate. Given the performance and maintenance impact, I can just as well keep the logic in BaseLayout

This sounds like a good plan to me.

**Comment by biochimia** [comment]
> > Initially, I tried to follow your suggestions in #3314 (comment) and #3725 (comment), but both of those disable the features before having a chance to look at the spec.
> 
> This is not impossible 😄 I've published a plugin that will achieve this for you: https://github.com/shockey/swagger-ui-plugins/blob/master/packages/disable-try-it-out-without-servers/README.md

Your plugin implements the removal of the _Try It Out_ buttons, but still leaves the _Authorize_ button visible, if I read it right.

Would it be appropriate to expose a similar per-endpoint `allowAuthorizeOperationFor` hook that would hide the `AuthorizeOperationBtn` instances?

Could we introduce another hook to control the top-level `AuthorizeBtn`, say `showAuthorizeButton`?

**Comment by biochimia** [comment]
@shockey:
> > I don't have a use case for it, and split it out solely to keep the logic separate. Given the performance and maintenance impact, I can just as well keep the logic in BaseLayout
> 
> This sounds like a good plan to me.

I've now implemented only this: removing the empty element at the top if there are no servers, schemes or security definitions to show in it, and dropped the other changes while we continue the discussion around potential new hooks.

This is also still missing tests.

**Comment by shockey** [comment]
thanks @biochimia!

**Pull request merged**
