### PR TITLE
Preserve authorization on browser refresh and close/reopen

### LINKED ISSUE #4851: Authorization value is lost on refresh
### Q&A (please complete the following information)
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 68
 - Method of installation: docker hub
 - Swagger-UI version: 3.18.2
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
components:
  securitySchemes:
    x-api-token:
      type: apiKey
      name: x-api-token
      in: header
  links: {}
  callbacks: {}
security:
  - x-api-token: []
```

### Describe the bug you're encountering

Authorization value is lost on refresh

### To reproduce...

1. Click on 'Authorize'
2. Enter value
3. Press 'Authorize'
4. Refresh the page
5. Click 'Authorize' again

### Expected behavior

I should see "Value: ******"

### Screenshots

screenshot from 2018-09-06 06-26-58
screenshot from 2018-09-06 06-27-47

### Additional context or thoughts

I thought that's the whole purpose of authorize button - to save user session so that it's not lost on refresh

### LINKED ISSUE #5803: Feature: An option to remember authentications
Authentications are lost on page reload and I think a elegant way to solve it would be a "Remember Authorization" checkbox for each auth that was entered. With it enabled, auths could be stored persistently in `localStorage` and applied on page load again after a sanity check that the auth parameters have not changed since it was last stored.

Related: https://github.com/swagger-api/swagger-ui/issues/4851

### PR DESCRIPTION
**Pull request by AmirBitaraf**
### Description

This pull request is a continuation of #4864. I just managed to write it in a more clear manner, and it would also satisfy the requirement by @shockey to have a configuration which is `configs.preserveAuthorization`.

### Motivation and Context

- Fixes #4851 
- Fixes #5803 

### How Has This Been Tested?

Refreshing or closing/reopening the the page will preserve authorization if we have `configs.preserveAuthorization` set to `true`. Contray to older pull requests, it also works with OAuth2.

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [ ] My changes do not require a change to the project documentation.
- [x] My changes require a change to the project documentation.
- [x] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [x] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by cognifloyd** [comment]
I don't see any tests here. Could you please add tests? That was one of the things missing in the other PRs (the other thing was the feature flag, which you've added :+1: )

**Comment by AmirBitaraf** [comment]
@cognifloyd yeah sure I will add tests

**Comment by triptec** [comment]
this would sure be nice to have.

**Comment by dilame** [comment]
Waiting for this feature like mother waits for her son from the army

**Comment by AmirBitaraf** [comment]
> Waiting for this feature like a mother waits for her son from the army

@dilame sorry I didn't have time to work on this recently. I'll write tests and doc in next two weeks to finalize this feature.

**Comment by JariKuipers** [comment]
Good to see that this is being worked on

**Comment by constantine008** [comment]
> Good to see that this is being worked on

agree

**Comment by AmirBitaraf** [comment]
@tim-lai I've refactored existing code and made some changes as below:

- As reducers were not a good option to do storage tasks, I removed all `localStorage` codes from them to keep them pure. So I added wrapper actions around `authorize`, `authorizeOauth2` and `logout` to check if they need to persist authorization data.
- I renamed the configuration key to `persistAuthorization` to be more informative
- I moved the check code to restore authorization to configs' `loaded` hook, so it can be extended later to load any persistent object after configuration load. (Check if it is logically ok to call actions from another plugin)
- I wrote unit tests on both `loaded` hook and wrappers (let me know if e2e tests are also needed)
- I upgraded all my unit tests to newly added `jest`
- I updated `usage.md` to contain `persistAuthorization` parameter

Regards

**Review by tim-lai — CHANGES_REQUESTED** [review]
@AmirBitaraf Looks good, but let's do one more refactor and make `wrapped` more descriptive.
wrappedAuthorize => AuthorizeWithPersistOption
wrappedAuthorizeOauth2 => AuthorizeOauth2WithPersistOption
wrappedLogout => LogoutWithPersistOption

**Comment by AmirBitaraf** [comment]
@tim-lai done

**Review by tim-lai — APPROVED** [review]

**Comment by tim-lai** [comment]
@AmirBitaraf PR Merged! Thanks for the contribution!

**Comment by AmirBitaraf** [comment]
@tim-lai Your welcome :)

**Comment by vudaltsov** [comment]
@AmirBitaraf , thank you for such a great improvement! Why is it unavailable for Docker?

**Comment by AmirBitaraf** [comment]
@vudaltsov your welcome, I'll add it soon

**Comment by vudaltsov** [comment]
@AmirBitaraf , looking forward ;)

**Comment by vudaltsov** [comment]
@AmirBitaraf, hi! Any updates for Docker?

**Comment by AmirBitaraf** [comment]
> @AmirBitaraf, hi! Any updates for Docker?

@vudaltsov sorry I was too busy, docker support added in #6832.

**Comment by vudaltsov** [comment]
> > @AmirBitaraf, hi! Any updates for Docker?
> 
> @vudaltsov sorry I was too busy, docker support added in #6832.

Thank you!

**Comment by andreisaikouski** [comment]
are there any details on how to configure this?

none of this is included in [docs](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md)

**Comment by AmirBitaraf** [comment]
> are there any details on how to configure this?
> 
> none of this is included in [docs](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md)

@andreisaikouski this is not a part of OpenAPI specification but a swagger configuration as documented [here](https://github.com/swagger-api/swagger-ui/blob/HEAD/docs/usage/configuration.md#authorization).

**Comment by piyush-bhattad** [comment]
I’ve gone through the [documentation ](https://github.com/swagger-api/swagger-ui/blob/HEAD/docs/usage/configuration.md#authorization) and tried setting the `persistAuthorization` parameter to **true** as mentioned in the doc, but I’m still unable to get my auth data saved on refresh. Am I missing any additional steps? Thanks

Here is my usage-

```
private renderSwaggerDocumentation(): void {
    // instantiate the editor
    const oauth2RedirectUrl = `${window.location.origin}/api-manager/swagger-ui/oauthredirect`;
    const ui = SwaggerUIBundle({
      oauth2RedirectUrl,
      dom_id: '#swagger-ui',
      persistAuthorization: true,
    });

    // attach the editor to window
    const swaggerWindow = window as any;
    swaggerWindow.ui = ui;

    // update the spec w/ yaml document
    if (this.apiSpecification) {
      ui.specActions.updateSpec(this.apiSpecification);
    }
  }
```

**Comment by piyush-bhattad** [comment]
> > @AmirBitaraf Am I missing any additional steps?
> 
> Make sure you're using at least [version 3.34.0](https://github.com/swagger-api/swagger-ui/releases/tag/v3.34.0) where the feature is added.

@AmirBitaraf Thanks for your reply. Using version 3.34.0 partially worked. Since Swagger UI is configured with `persistAuthorization: true`, I can see that the currently active credentials are saved in the authorized key in the browser's local storage. With this setup, the saved credentials should be pre-applied after refreshing or reopening the Swagger UI page, right? However, the UI is still not displaying the stored key when the page is refreshed. I know the UI recognizes that there is a key present because it also displays the logout button in the authorization dialog popup.

https://github.com/swagger-api/swagger-ui/assets/114017807/670ff70a-548f-4793-849a-216147aa58e6


Any idea if we previously identified this issue and if it’s already being worked on or actively getting worked on? If that’s not the case, I can file a ticket. I did some research and couldn’t find this issue reported by anyone, so I’m thinking this could also be related to previous versions of the library (I'm hesitant to switch to a newer version of this library since it might have different requirements for the Node.js version. The project I'm working on uses Node.js version 10.24.1, and currently, we are restricted from upgrading the Node.js version)

**Pull request merged**
