### PR TITLE
Remove redundant attributes

### PR DESCRIPTION
**Pull request by Maks3w**

### CODE REVIEW

**Comment by mohsen1** [comment]
IE8 might not like that. Specially the script tag. I'm not sure tbh

**Comment by Maks3w** [comment]
May but are IE8 users a target?

We are talking here about experienced people with software development skills. I can't believe there are developers working with IE8 as primary browser.

**Comment by webron** [comment]
@Maks3w - PRs should be made against the develop_2.0 branch, so please resubmit against it.

**Comment by Maks3w** [comment]
@webron Are you serious? develop_2.0 is already merged on master.

**Comment by fehguy** [comment]
@Maks3w yes, we do not merge directly to master until we release.  develop_2.0 is our development branch.

**Comment by Maks3w** [comment]
@fehguy Then sync develop_2.0 with master first

**Comment by fehguy** [comment]
I'm confused.  I really appreciate your PRs and contributions, but our process is consistent--we accept PRs made against develop_2.0 and will merge to master upon release.

**Pull request closed without merging**
