### PR TITLE
OAuth2 Owner Credentials flow now matches specification

### LINKED ISSUE #3227: OAuth2 Password Flow modes do not match RFC
Currently, only one out of three implemented OAuth2 Password Flow modes match [RFC 6749 section 2.3.1](https://tools.ietf.org/html/rfc6749#section-2.3.1), which explicitly states:

>   The authorization server **MUST support the HTTP Basic authentication** scheme for authenticating clients that were issued a client password.
>
>   For example (with extra line breaks for display purposes only):
>
> ```
>       Authorization: Basic czZCaGRSa3F0Mzo3RmpmcDBaQnIxS3REUmJuZlZkbUl3
> ```
>
>   Alternatively, the authorization server **MAY support** including the client credentials in the **request-body** using the following parameters:
>
>   client_id
>
>   REQUIRED.  The client identifier issued to the client during the registration process described by Section 2.2.
>
>   client_secret
>
>   REQUIRED.  The client secret.  The client MAY omit the parameter if the client secret is an empty string.
>
>   Including the client credentials in the **request-body** using the two parameters is **NOT RECOMMENDED** and SHOULD be limited to clients unable to directly utilize the HTTP Basic authentication scheme (or other password-based HTTP authentication schemes). The parameters can only be transmitted in the request-body and **MUST NOT be included in the request URI**.

There are 3 modes implemented in OAuth2 Password flow:

1. "Request body" - Pass `username` with `password` in request-body and `client_id` with `client_secret` in "Authorization" header (`Basic`) - this is the CORRECT and RECOMMENDED way of doing this according to RFC.
2. "Basic auth" - Pass `username` with `password` in "Authorization" header (`Basic`) with no `client_id`/`client_secret` - this has NOTHING TO DO with OAuth2 as far as I can tell, this is just someone's simplified authentication method. If there is no other place to implement this, well let it be there, but this might be a bit confusing.
3. "Query parameters" - Pass `username` with `password` in request-body and `client_id` with `client_secret` in URI query encoded parameters - this is EXPLICITLY DISCOURAGED in the RFC since URLs are usually logged on the web servers and this would expose the plaintext secrets to anyone reading the logs.

The names in Swagger UI are completely misleading, by the way.

Here is my proposal:

1. Rename "Basic auth" to "Basic username & password auth" to be more explicit, and move to the end of the list, though the only reason to leave it there is that there is no other place for it :(
2. Rename "Request body" to "Basic auth" and leave it as default just as it is now.
3. Replace "Query parameters" with new "Request body" and implement it so it passes `client_id` and `client_secret` via request-body.

/cc @bodnia @Naid405 @benoj @webron

### PR DESCRIPTION
**Pull request by krotscheck**
### Description

This pull request updates the "Password" flow to match the RFC, in
accordance to #3227, with the following changes:

- Two methods have been explicitly removed (though names have been repurposed): Using login/pass in Basic Auth and including client_id and client_secret in the query string. The former has been removed because it is not in the specification at all, the latter because it's explicitly discouraged.
- The "Basic" auth method now uses the client_id and client_secret in the Authorization header, via Basic auth, in accordance with RFC section 2.3.1: https://tools.ietf.org/html/rfc6749#section-2.3.1
- The "Request Body" auth method now adds the client_id and the client_secret to the form body, in accordance to section 3.2.1: https://tools.ietf.org/html/rfc6749#section-3.2.1
- The form no longer hides the client_id or client_secret.

### Motivation and Context

* Security: Putting client_id and client_secret in the query string will be cached by the browser, which is insecure.
* Fixes #3227
* Usage: I want to add Password-based swagger UI to an OAuth2 server that I've built, and the implementation doesn't actually match the spec.

### How Has This Been Tested?

I created a custom build including my fixes, and hosted them off of an OSS OAuth2 compliant authorization server, then validated that both private and public password-based clients could authenticate. 

### Types of changes
- [ ] No code changes (changes to documentation, CI, metadata, etc)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change

### Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by krotscheck** [comment]
I wasn't certain if I needed to commit my custom `/dist` directory, opted for the smaller delta.

**Comment by frol** [comment]
This looks right to me!

@krotscheck Thank you!

/cc @bodnia @Naid405 @benoj @webron

**Comment by shockey** [comment]
Thanks @frol 😄 

Hoping to get at this in the coming days with @webron - I'm a bit concerned by the breaking change... we need to hash out how "in the weeds" the current implementation is before dropping the functionality altogether.

**Comment by shockey** [comment]
Closing; source branch is no longer available 😿

**Comment by krotscheck** [comment]
What? Drat! Sorry, lemme go get it back up.

**Comment by krotscheck** [comment]
IT'S ALLLIIIIIIVE

**Pull request closed without merging**
