### PR TITLE
Added search

### PR DESCRIPTION
**Pull request by lijulia**
The interactive search allows you to filter the API content on the page.
search

### CODE REVIEW

**Comment by fehguy** [comment]
What is this supposed to do?

**Comment by lijulia** [comment]
What's the status of my pull request "Added search #2116"?

**Comment by webron** [comment]
@lijulia - well... @fehguy did ask a question about the meaning of the PR...

**Comment by lijulia** [comment]
Sorry, I must have missed it.  The PR is to add an interactive search to allow you to filter the API content on the page.

**Comment by lijulia** [comment]
I am wondering if you need more info for this pull request.

**Comment by cabbonizio** [comment]
This is a nice little feature!

**Comment by webron** [comment]
@lijulia - I think the info is fine - it's time now :)

**Comment by lijulia** [comment]
@webron Thanks!

**Comment by lijulia** [comment]
what's the status now?

**Comment by Shuan-Ku** [comment]
@lijulia , @webron - I use Swagger in my ASP.NET WebAPI project recently, but I met some problems that I describe in [stackoverflow](http://stackoverflow.com/questions/40435451/how-to-implement-search-function-and-add-comments-in-swagger). Could somebody help me? Thanks a lot

**Comment by JFCote** [comment]
Why is this not merged in the main project? It's exactly what I need!
Any status on this?

**Comment by webron** [comment]
We're focused on the next major version of the UI (which will also make this PR inapplicable), and unfortunately can't spend the time to review such PRs (as much as we appreciate the efforts).

If you need that functionality, you can always check out the PR and apply it locally.

**Comment by JFCote** [comment]
Thanks @webron. Do you have any link that we can consult to see the features that will be in the next major version of the UI?

**Comment by webron** [comment]
It's not publicly available yet.

**Comment by webron** [comment]
Apologies for the (very) delayed feedback.

Unfortunately, our code base might have deviated from the time this PR was submitted, and we cannot easily merge it (certainly not against `master`), and so, we're going to close this PR.

If you find the change important and would like to resubmit it, please let us know. Be aware that we are focused on the 3.X version at the moment (now `master`), and new changes should be applied to it.

We appreciate the time you've taken into submitting this PR. We're now making extra effort to review PRs within a few days at most, to avoid situations like this.

Notice that #3196 could be a good starting point for this feature in 3.X.

**Comment by donratta** [comment]
This is an awesome feature.. Will try opening a PR for v3

**Comment by webron** [comment]
Thanks @donratta - just giving you a heads up that we might have an upcoming feature that would cover this functionality, but I need to look into it a bit more.

**Comment by Hootlook** [comment]
I need that search bar sorry to ask but how do you implement it for asp net core ?

**Comment by giorgiocc** [comment]
how to enable this?

**Comment by Vturnus** [comment]
Why is this closed when people still have questions about it?

**Comment by KaKi87** [comment]
Hi,
Any news on this ?
Without this feature, searching requires expanding all sections before hitting Ctrl-F, which is annoying.
Thanks

**Comment by Ashwin-hp** [comment]
Any updates?

**Pull request closed without merging**
