### PR TITLE
hide deprecated properties in examples

### PR DESCRIPTION
**Pull request by refractalize**
Hide deprecated properties in schema examples

### Motivation and Context

Showing deprecated properties in examples gives false impression that they are still current and should be used. This PR hides deprecated properties from examples shown in the UI, so new users are less likely to use deprecated properties by copy/pasting examples, or by using the examples as a form of ad-hoc documentation.

### How Has This Been Tested?

Deprecated a property, verified that it does not appear in the example section of a POST request body.

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [x] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [ ] are not breaking changes.

### Documentation
- [ ] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [x] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by refractalize** [comment]
hi guys - i removed the `dist/*` stuff to resolve conflicts.

**Comment by shockey** [comment]
ping @webron

**Comment by webron** [comment]
@refractalize Thanks for the PR (and apologies for the delay)! It makes perfect sense and should be a good update for the project.

**Comment by shockey** [comment]
thanks @refractalize!

**Pull request merged**
