### PR TITLE
hide base64-encoded credentials from UI

### PR DESCRIPTION
**Pull request by ovesh**
Replace the `Authorization` header with a `-u` flag in the
displayed curl command, for requests that use basic auth.

### Description
in curlify, check if an authorization header includes basic auth details, and replace that header with a `-u` flag, so that when pasted in the terminal, users will be prompted for a password.

### Motivation and Context

https://github.com/swagger-api/swagger-ui/issues/5425

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [ ] are not breaking changes.

### Documentation
- [ ] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by shockey** [comment]
@webron tagging you for feature review — I'm not certain we want to hide auth details in the cURL outputs, seems like one of those "api designer UX vs api consumer UX" questions!

**Comment by webron** [comment]
Yeah, this is a bit tricky because different users are going to want different things. Is this something that can be customized via a plugin?

**Comment by shockey** [comment]
@webron we could definitely expose this as a plugin touchpoint, but beyond that, do you think what we do now is the more reasonable choice as a default?

**Comment by tim-lai** [comment]
@ovesh Thanks for the PR! Per comments above, this would be better as a plugin feature (with config, options, and documentation). Closing PR.

**Pull request closed without merging**
