### PR TITLE
Add isShown to ModelCollapse, to tie it to state

### PR DESCRIPTION
**Pull request by ponelat**
Simple oneline to add tie isShown to the outer component: ModelCollapse.

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shockey** [comment]
@ponelat, thanks for this, what does this change functionality-wise?

**Comment by ponelat** [comment]
It allows calling layoutActions.show(...), which would then directly open/collapse the model section. 
Idealy, we should probably remove the internal state with Models, but for now this will make it match other components, which use layoutActions.show

**Comment by shockey** [comment]
bump @ponelat, is this still relevant?

**Comment by ponelat** [comment]
Lets close it, there doesn't seem to be any need for it yet.

**Pull request closed without merging**
