### PR TITLE
Filter by one or more tags

### PR DESCRIPTION
**Pull request by DavidVujic**
### Description
In this Pull Request, the "filter by tag" input field accepts one or more phrases to use for filtering the list of operations. When using more than one phrase, they are separated by comma.

Example: pet, store

### Motivation and Context
One scenario is when testing out an operation that requires an authenticated session or token. Usually, getting a session/token is made executing a different operation. So, there are two operations that will be tested out. A filter that accepts more than one phrase will solve that. 

### How Has This Been Tested?
Two unit tests are added to the source code (the test/components folder), testing the filter function with one phrase, and with two phrases.

### My PR contains... 
- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [x] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [ ] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shockey** [comment]
Thanks @DavidVujic! I like this idea. 

I'll do a full review next week, but right off the bat I am concerned by the blessing of `,` as a separator character.... Tag names are not limited to any particular set of characters in OpenAPI 2.0 or 3.0, so a tag name of, for example, `this,is,my,tag` would be unfilterable with this change. Further, if someone is using filter with such a tag name today, their implementation would break 😢 

Some possible solutions to chew on:
- Choose a more esoteric character (or sequence of characters) to bless for splitting
- Make this functionality opt-in, with the user needing to provide a separator character via config in order to activate it

Totally open to discuss these, or any other solutions you can think of!

**Comment by DavidVujic** [comment]
Thank you @shockey for sharing feedback! 

I wasn't aware of that tag name can include any character. Maybe an opt-in featue is the way to go. Or, (haven't tried this out yet, just an idea) maybe it is possible to write the filter so it will run once again (if comma separated) as if it were a single filter. 

Example: when typing "pet, store", the filter could treat the input value as both an array, and then as a single phrase running a filter just like the version in the Master branch today. What do you think about it?

I would like to write some unit tests expecting the behaviour and then write a filter that makes the tests pass in this PR. OK?

**Comment by DavidVujic** [comment]
Updates:
the filter will fallback to a single filter string, if any tag name in the list contains `,`. 

Maybe this filter feature is now trying to be too clever (and produces side effects)? 😄  If so I can undo this PR.

**Comment by webron** [comment]
@DavidVujic - Ahoy! Thanks for the PR. It's always exciting to see new ideas coming from the community. 

That said, as you can tell, the implementation is becoming a bit complex for the user. It means additional configuration settings, understanding the expectations and all that - to support a use case that we haven't really gotten requests to support. To support it for a one-of, that would be more suitable to be a plugin that you add to your own deployment, than something that gets into the main project. I'd be happy to revisit the functionality in the future should we get additional requests for it, but until then, I'm inclined to not accept the feature as-is.

**Comment by heldersepu** [comment]
I do use the filters quite often, I even created my own backend param to handle them in the URL like:
http://offleaseonly.azurewebsites.net/swagger/ui/index?filter=Stats (probably you seen it in my comments)

But I've never had a need to show multiples...
That's not saying that the idea is not good, **I think it's brilliant!** I truly do
but the implementation could use some refining, and for the separator char we need to put a bit more thought into it, what is a char least used in Tags? Space, Plus, Pipe...

**Comment by DavidVujic** [comment]
@webron @heldersepu Thank you for the feedback!

I am not sure I agree the implementation is complex for the user. The filter works right of the box, and if you happen to have "," in your tag names it will fall back to filter only one at a time just like today. No configuration needed.

The first thing I did (without knowing how it worked) when using the filter in the new Swagger UI was to type two phrases (with comma as a separator), expecting to filter our very long list of API's.

The users in our organisation also expect a filter to display the ones needed for testing (example: a "user" auth endpoint, and another one to get some user specific data), probably because of it is a very long list of endpoints.

Also, writing a plugin for this feature is a bit tricky, because the filter in the Master branch is baked in to the Layout (and is not written as a separate component). In our installation, we have solved this with a "DOM-hack", scripts overriding the default behaviour. That is why I went back to the source, and sent a Pull Request 😄 

I won't argue anymore with you! 🤓 What do you want me to do, should I undo the PR?

**Comment by shockey** [comment]
> Also, writing a plugin for this feature is a bit tricky, because the filter in the Master branch is baked in to the Layout (and is not written as a separate component)

An interesting way to sidestep this would be to expose a filter function via the [`fn` plugin interface](https://github.com/swagger-api/swagger-ui/blob/master/docs/customization/plugin-api.md#fn), which would allow one to provide their own filter value processor 😄

**Pull request closed without merging**
