### PR TITLE
Allow to skip submitting empty values in form data

### LINKED ISSUE #5303: Omit empty and optional values in form data
I have this request body:
```yaml
...
requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                nick:
                  type: string
...
```

If I send a request wihin Swagger UI with some `name` but with empty value in the `nick` field, the UI evaluates the request like this:

`curl -X POST "address" -H "accept: application/json" -H "Content-Type: application/x-www-form-urlencoded" -d "name=vaclav&nick="` 

But I need not to have the `nick` field contained in the request body if the field is empty, like this: 

`curl -X POST "address" -H "accept: application/json" -H "Content-Type: application/x-www-form-urlencoded" -d "name=vaclav"`

Can I mark a property field as optional and not sending if the field is empty? Unfortunately, my API does not accept empty values, but it is able to omit some post field if it is not included in a request.

### PR DESCRIPTION
**Pull request by abcang**
### Description

Adds an option to send an empty value when submitting values in form data. This only works for OpenAPI 3 if the content type starts with `multipart/` or is `application/x-www-form-urlencoded`.

### Motivation and Context

Fixes #5303

Two implementations were suggested, but I chose the way to add the options. 
Since it is not possible to explicitly send an empty string when automatically skipping empty values, I thought an implementation that could choose whether or not to send an empty string would be better. (Skip empty values by default.)

### How Has This Been Tested?

Using [OpenAPI 3 petstore definition](http://petstore.swagger.io:8080/api/v3/openapi.json), I checked if `PUT / pet` skips empty values.

### Screenshots (if appropriate):

image

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [x] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [x] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [ ] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tim-lai** [comment]
please build

**Comment by zkatemor** [comment]
is it possible to use this functionality in [rswag](https://github.com/rswag/rswag)? if so, tell me how to do this?

**Comment by abcang** [comment]
I think the new swagger-ui will allow you to use this feature with the non-required parameters of the requestBody.

**Comment by zkatemor** [comment]
@abcang, sorry, but I don’t understand what I’m doing wrong

```
requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  allowEmptyValue: true
                  required: false
                area:
                  type: string
                  allowEmptyValue: true
                  required: false
                country:
                  type: string
                  allowEmptyValue: true
                  required: false
```

but still no checkboxes...

**Comment by abcang** [comment]
Hmmm... this feature came in from version 3.26.0, is that the right version?
It looks correct, except that the `allowEmptyValue` and `required` fields are not needed.

**Comment by Chrno21** [comment]
Hi,

I do not get it to work... is there something missing?

`put:
      security:
        - basicAuth: []
      description: Chenge directory
      tags:
      - folder
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 80
                  example: new folder
                order:
                  type: integer
                  minimum: 1
      responses:
        301:
          $ref: "#/components/responses/folders"
        401:
          $ref: "#/components/responses/UnauthorizedError"`

**Comment by abcang** [comment]
I have confirmed that a checkbox is displayed in `POST ​/pet​/{petId}` of this petstore definition (you have to click the button of `Try it out`).

1. Visit http://petstore.swagger.io/
2. Enter the URL in the input field
  - https://gist.githubusercontent.com/danielflower/5c5ae8a46a0a49aee508690c19b33ada/raw/b06ff4d9764b5800424f6a21a40158c35277ee65/petstore.json
  - (gist page: https://gist.github.com/danielflower/5c5ae8a46a0a49aee508690c19b33ada )
3. Open `POST ​/pet​/{petId}`
4. Click `Try it out`

image


(The URL of the petstore definition in the pull request description was broken, so I replaced it with a valid link.)

**Comment by Chrno21** [comment]
Thanks, works great. I forgot to update the swagger-editor.
But is it possible to set "Send empty values" as default?

**Comment by abcang** [comment]
Sorry, this pull request doesn't implement the ability to change the default behavior.

**Comment by diavrank** [comment]
I am looking for something similar but for arrays. How to skip submitting empty arrays for a query parameter? 

I'am using Swagger Module for NestJS.

**Pull request merged**
