### PR TITLE
OAS3 multi examples in requestbody

### PR DESCRIPTION
**Pull request by biggates**
This provides multiple examples in OAS3 examples in requestBody.

### CODE REVIEW

**Comment by biggates** [comment]
visual_effect

example OAS3 spec is [here](https://gist.github.com/biggates/4955d608379a8b1b3224e815c7dd0dc9)

**Comment by biggates** [comment]
The rendering of `externalValue` as a link (`<a href="location" target="_blank">`) is a bit odd here. Should it be fetched and displayed directly in a `<HighlightCode>` component ? Maybe only apply to `text/*` is better?

**Comment by webron** [comment]
@biggates thanks for the contribution and sorry for the delayed response. I'd like to take a bit of a closer look into the implementation. This is not exactly what I had in mind for implementing it, though it's definitely a needed solution.

Would you be open to change it based on feedback and also apply the same behavior to responses and regular parameters?

**Comment by biggates** [comment]
> Would you be open to change it based on feedback and also apply the same behavior to responses and regular parameters?

@webron Sure, I'm glad to contribute on this.

**Comment by shockey** [comment]
@webron, bump 😄

**Comment by biggates** [comment]
@shockey  I'm still working on this, the current progress looks like this:

image

using the definition https://gist.github.com/biggates/4955d608379a8b1b3224e815c7dd0dc9 

I'm not sure whether this is what you have in mind, so I still keep the examples in response as my previous implmentation.

Also the examples in parameters is not finished yet.

**Comment by darrenhinderer** [comment]
I've been trying this PR out extensively today. I started using the 3.0 spec just for this request body multi-examples feature.  For the most part things are working well, but I'm running out of space with the horizontal treatment that was used.

screen shot 2017-10-03 at 4 13 22 pm

I have one usage of multiple response examples and it seem to be behaving fine. The text for it still says Example Value instead of Example Value**s** even though there are two of them though.

**Comment by biggates** [comment]
Oops, this breaks RequestBodyEditor. 😭

**Comment by galuszkak** [comment]
@biggates is it possible to rebase it to the master and merge in near future?

**Comment by shockey** [comment]
Closing in favor of https://github.com/swagger-api/swagger-ui/pull/4092.

**Pull request closed without merging**
