### PR TITLE
Indent JSON examples.

### PR DESCRIPTION
**Pull request by mhw**
Adds the necessary arguments to indent the JSON examples. Addresses issue #2928.

### CODE REVIEW

**Comment by shockey** [comment]
Can you provide a spec that will illustrate the change, or a before/after screenshot?

Thanks! 😄

**Comment by webron** [comment]
@shockey there's a snippet in the linked ticket.

**Comment by shockey** [comment]
Thanks for the improvement @mhw 🎉 

This will go live when we release on Friday.

**Comment by mhw** [comment]
Hey, you beat me to getting the screenshots uploaded! :smile:

No problem - glad to help out.

**Pull request merged**
