### PR TITLE
add simple translation support

### PR DESCRIPTION
**Pull request by kalinin-k-a**
Added simple and plain translator. 
Description is in https://github.com/kalinin-k-a/swagger-ui/blob/master/dist/lang/translator.js

### CODE REVIEW

**Comment by fehguy** [comment]
Interesting!  Thank you for submitting, we'll review this for 2.1.  Definitely want to introduce translation support but haven't gone through the various options yet.

**Comment by mohsen1** [comment]
* Please change the attribute to not use cameCase. `data-swTarnslate` can be `data-sw-tarnslate`.
* When using  `data-sw-tarnslate` attribute, presence of the `data-sw-tarnslate` attribute should be enough. It doesn't have to have a value. (`data-sw-tarnslate="1"`)
* Please add documentation of how it should be used under [**Customize** section of README](https://github.com/swagger-api/swagger-ui#customize)

**Comment by mohsen1** [comment]
Also if you can, please make a PR to `develop_2.0` branch

**Comment by kalinin-k-a** [comment]
Done. 
Documentation is added, data-sw-translate is fixed.
PR to develop_2.0 is here - https://github.com/swagger-api/swagger-ui/pull/967

**Comment by mohsen1** [comment]
Closing in favor os #967

**Pull request closed without merging**
