### PR TITLE
slimmed Docker image + usage

### PR DESCRIPTION
**Pull request by romant**

### CODE REVIEW

**Comment by fehguy** [comment]
would alpine be smaller?

**Comment by romant** [comment]
most likely; and although in this case we go from 904.5MB down to 372MB.

will look at slimming it even further; needed to start somewhere 😄

**Comment by romant** [comment]
@fehguy … we're down to 9.771 MB. Give it a try.

**Comment by fehguy** [comment]
nice :)  Can you keep the external port on 8080 so it's compatible?

**Comment by romant** [comment]
@fehguy reverted.

**Pull request merged**
