### PR TITLE
fixes #2221

### LINKED ISSUE #2221: JavaScript runtime error: Object.keys: argument is not an Object error while using Swagger UI in IE 11.
I am getting the following error while using Swagger UI in Internet Explorer 11.

Unhandled exception at line 2, column 27219 in http://localhost:52697/service/help/swagger-ui.min.js

0x800a138f - JavaScript runtime error: Object.keys: argument is not an Object.

I am using "Swashbuckle.SwaggerUi": "6.0.0-beta9"

### PR DESCRIPTION
**Pull request by bodnia**

### CODE REVIEW

**Comment by bodnia** [comment]
@fehguy @webron could you please review

**Comment by fehguy** [comment]
@bodnia can you bundle the es5-shim into the gulp package?  If not, every index.html will need to be updated, which tends to cause a lot of problems (it's essentially a breaking change)

**Comment by bodnia** [comment]
@fehguy the reason why it's in the `index.html` is that library `<script src='lib/js-yaml.min.js' type='text/javascript'></script>` requires it too. Otherwise this would be inside `swagger-ui.js` and `swagger-ui.min.js` Does it make sense?

**Comment by bodnia** [comment]
@fehguy added es5-shim to swagger-ui.js (and min), but for now it's included twice: in `index.html` and in  `swagger-ui.js`

**Comment by bodnia** [comment]
@fehguy could you please review?

**Comment by fehguy** [comment]
@bodnia I still don't understand why it needs to be in `index.html` if it's included in swagger-ui.js.  Can we just export it if it's bundled in swagger-ui.js?  I really don't want to change the index.html file as it causes many upgrade problems for people.

If we must, we can, but it's best not to.

**Comment by bodnia** [comment]
@fehguy `js-yaml` (that used `Object.keys`) and `es5-shim` are removed from `index.html`
`js-yaml` is present in `swagger-ui.js`

**Comment by bodnia** [comment]
@fehguy did you have a chance to review?

**Comment by fehguy** [comment]
merged in https://github.com/swagger-api/swagger-ui/commit/0d250acf58e86230cd297ba335e84acd8e5cba3a

**Pull request closed without merging**
