### PR TITLE
Add useQueryConfig parameter

### LINKED ISSUE #4332: Allow disabling of queryConfig
Swagger-ui can accept configuration parameters through a query string with no ability to disable this functionality. For us this represent a security issue. It allows a malicious user to phish users through your documentation site.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         | Feature request
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.12.1
| How did you install Swagger-UI? | swagger-ui-dist
| Which browser & version?        | Any
| Which operating system?         | Any

### Expected Behavior

An option to disable the `queryConfig` entirely: https://github.com/swagger-api/swagger-ui/blob/master/src/core/index.js#L81-L86.

### Current Behavior

Imagine I am a malicious person attempting to phish users. I can use your documentation site by creating cloning your openapi/swagger spec and hosting that somewhere, then pass that URL as  query parameter to your docs site. I can then shorten/distribute this URL maliciously.

http://petstore.swagger.io/?url=https://gist.githubusercontent.com/dfsdfsdfsdfsdfdfdfdfds/0c46fa0f333cec4d06bfd9a80392d86d/raw/29537fd4c0b30c4151fbfd2129c4a9ac389e7d33/1.json#/translation/getLocalizations

The above link has a URL in the beginning of its swagger ui component, that says click me. I am now able to inject external content into your page in this manner.

### Possible Solution

This could be implemented as a configuration option, which will prevent loading of a the configuration from query parameters.

### Context

We are a https://github.com/vanilla/vanilla and are attempting to host a documentation for our users. We currently have to check query parameters and strip them ourselves to prevent phishing through our documentation.

### PR DESCRIPTION
**Pull request by charrondev**
Add's a `useQueryConfig` parameter that defaults to true. If the parameter is set to fault in the passed `opts`, the `queryConfig` will be initialized to an empty object, and will not be able to override other configuration.

### Description

I've updated the docs and ran the build process as well.

### Motivation and Context

Closes #4332 

Motivations are discussed in the issue. TL;DR Disabling the query configuration is desirable 2 prevent clashes with a containing application, and/or to prevent people from linking hijacked versions of public documentation that is actually pulling its data from an unknown 3rd party.

### How Has This Been Tested?

This was manually tested by linking the project into our own documentation site, and product dashboard, as well as in the development environment on `localhost:3200`. When set in the configuration, `useQueryConfig: false` prevents the queryParameters from being parsed at all.

This was tested on Node 9.8 in Google Chrome 65 on MacOS.

I looked for unit tests around the configuration, but there were none that I could see. I considered writing some, but that might involve some refactoring that would make this more than a simple 3 line change.

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [x] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [ ] My changes do not require a change to the project documentation.
- [x] My changes require a change to the project documentation.
- [x] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by charrondev** [comment]
Hmm, I guess this represents a bit of a dilemma. I was imagining that this parameter would be set from JS (yaml works too though) and not through the queryConfig. Being able to set `useQueryConfig: false` from the queryConfig doesn't really seam like it would be that useful right? Either way re-ordering this to be able to pull from the yaml config will require some larger changes because the `constructorConfig` is already contaminated by `queryConfig` by the time we get the `localConfig` (from yaml).

I'm having trouble following what actually happens in between the initial creation of the `System` and the updating of it with the results from the yaml config with all of the different functions being spread out between the different plugins and files and slightly different but similar names of things.

The creation of the config (and updating of it) is complex enough that I can't just look at it on its own and would need to have a deeper understanding of the whole system, so I can't budget all of the necessary time to unravel this at the moment. I'll see if I can return to this in the next couple weeks.

**Comment by shockey** [comment]
> Being able to set useQueryConfig: false from the queryConfig doesn't really seam like it would be that useful right? 

I can't think of a reason 😄 

That being said, my reason for requesting the change is that currently, we don't have any config options that are silently ignored at lower config levels, so I'd like to avoid introducing the concept, as it adds complexity to the config system.

**Comment by shockey** [comment]
Closing due to inactivity. 

This is simply to keep our issue tracker clean - feel free to comment if there are any further thoughts or concerns, and we'll be happy to reopen this.

**Comment by cjelger** [comment]
What's the status of this? We are having the same issue, and I think this PR was perfectly fine. IIUC, @shockey you would like to allow setting the `useQueryConfig` in the constructor config, and also in the local build config and `configUrl` document, right?

**Comment by charrondev** [comment]
Not to dissuade you, but the requested change would completely neuter the any security improvement the rest of the PR brought.

**Comment by cjelger** [comment]
I have never used the `configUrl` option, but surely if one can set the `configUrl` in a query parameter like `?configUrl=http://my-bad-config`, then yes the whole purpose of introducing `useQueryConfig` is lost.

@shockey WDYT of https://petstore.swagger.io/?url=https://xpoc.pro/8.php ?

**Comment by charrondev** [comment]
> I have never used the configUrl option, but surely if one can set the configUrl in a query parameter like ?configUrl=http://my-bad-config, then yes the whole purpose of introducing useQueryConfig is lost.

This is precisely why I had opted to load the `useQueryConfig` parameter before initializing anything thing from the query config!

For this fix to work securely it _must_ not be settable from the query config.

**Pull request closed without merging**
