### PR TITLE
remove inline-code

### PR DESCRIPTION
**Pull request by AndreKoepke**
### Description

Removing inline-codes in `/dist`.

### Motivation and Context

Inline-Code in HTML-files should be avoided. Good systems using CSP-header to prevent XSS-attacks. If a HTML-document contains inline code, then a CSP-header `script-src: 'unsafe'` is necessary. And this is unsafe. :)

### How Has This Been Tested?

Local in IntelliJ, all seems fine. And successfully run `npm run test`.   
Nice tests btw. :+1:  

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tim-lai** [comment]
@AndreKoepke Thanks for the PR! Have you tried this PR with a Docker instance? Also, there could be sharing/consolidation with the `/dev-helpers`.

**Comment by AndreKoepke** [comment]
@tim-lai you're welcome. :)

## Docker
No, I just started the pages in the webserver of my IDE. Screenshot incoming:
image
Should I put it into a docker-image?

## /dev-helpers
Yes, you're right. I will fix them too.

**Comment by tim-lai** [comment]
> Should I put it into a docker-image?

I'm not expecting any changes needed for a docker image. I just wanted confirmation that one can still build the docker image locally and that it otherwise runs as expected without additional changes.

**Comment by AndreKoepke** [comment]
Ah, I see what you mean. The docker-image will build correctly and it runs fine. All works as expected.  
But the is a error-log, when the container will start:

```
```

**Comment by lpilon** [comment]
Hi, quick follow-up; any sight on a merge?

**Comment by AndreKoepke** [comment]
@lpilon not now. Why have a day only 24 hours? I need more. :D

**Comment by AndreKoepke** [comment]
Sorry for the very late response.

I had a deeper look into the "configurator"-logic. It checks for environment-variables and it allows to write a OAuth-flow the api-documentation.  
With my changes, this is broken, so I'm going to fix that. I think, that I would be done in the next hours.

**Comment by AndreKoepke** [comment]
Aaaand, I'm done.  
I deleted some unsued functions and removed code for deprecated features (api-key in index.html ...).  
And I added some documentation into the code to reduce the required "brain" for future devs to understand this. :)

Last but not least: I changed the markers for the configurator to a value that is reconginzed by IDE (tested with IntelliJ).  
Here are some pics:
image  
image

**Comment by danielleontiev** [comment]
Hello @tim-lai!
Any estimates on merging this?

**Comment by tim-lai** [comment]
@AndreKoepke Hi there, I'm following up on this PR. There was a recent SwaggerUI patch update with Webpack@5. One of the webpack-related changes was the removal of specifying the `swagger-ui-bundle.js` and `swagger-ui.css` from `dev-helpers/index.html`. There was not a change to `/dist/index.html`, so at minimum, could you try rebasing this PR for `dev-helpers` and re-verify that everything else is still working for you? Thanks!

**Comment by inanbayram** [comment]
@AndreKoepke Is there an update on this PR? It would be nice, if this PR could be merged. We have also the problem, that we don't want to use ```script-src: 'unsafe'``` to use the swagger-ui. Thanks :)

**Comment by danielleontiev** [comment]
@AndreKoepke I've updated your changes and put it in new PR: https://github.com/swagger-api/swagger-ui/pull/7905

You is still mentioned as author in `git`. @tim-lai don't you mind for looking at the changes, please?

**Comment by AndreKoepke** [comment]
@danielleontiev thanks for the rebased PR. We can move to your PR, I will close this one soon.  
@inanbayram WIP, the new pull-request must be merged.

**Pull request closed without merging**
