### PR TITLE
fix(ui): change copy to clipboard button location

### PR DESCRIPTION
**Pull request by char0n**
Refs #8465
Refs #8153
Refs #8131

---

This PR uses changes from https://github.com/swagger-api/swagger-ui/pull/8465 and retains keyboard navigation. "black outline that appears on focus" has been retained, and chevron icon has been made not navigable as it would be redundant and anoying.

https://github.com/swagger-api/swagger-ui/assets/193286/415a02cf-3fed-4f0e-b910-a1da44800bf0

### CODE REVIEW

**Comment by thinkjson** [comment]
Looks good to me!

**Comment by remcolam** [comment]
I am using version 6.5 and I still have the jumping layout on hover. How can I get rid of this bad UX behaviour?

**Comment by char0n** [comment]
Hi @remcolam,

There is no version 6.5. Latest version of SwaggerUI is https://github.com/swagger-api/swagger-ui/releases/tag/v5.11.4

**Comment by remcolam** [comment]
🤦 I was confusing the swagger ui with the package I use in my application to add swagger... Thank you for your reaction. Will check if I can update the UI in it myself

**Pull request merged**
