### PR TITLE
if param.schema doesn't exist, then the line will fail

### PR DESCRIPTION
**Pull request by mikexliu**

### CODE REVIEW

**Comment by mikexliu** [comment]
Encountered a simple case where an object didn't have the schema field. Let me know if you need any other information.

**Comment by mikexliu** [comment]
@fehguy Can you review this? It is affecting my springfox plugin.

**Comment by fehguy** [comment]
@mikexliu please give an example specification that exhibits the issue

**Comment by mikexliu** [comment]
@fehguy 
Here is my example: https://gist.githubusercontent.com/mikexliu/c25c007d3f69844688020de26756b2ec/raw/010aebe8e7e56b733e4353e457bef81d30a95efa/gistfile1.txt (sorry it's a bit large)

If you paste that link into http://petstore.swagger.io/, then you can see the error. The endpoint was auto-generated using springfox.

**Comment by fehguy** [comment]
Thanks.  PR was merged so 2.2.0 no longer shows the issue.  I'll get the petstore updated later today with the latest, but you can get it from master or the [2.2.0](https://github.com/swagger-api/swagger-ui/releases/tag/v2.2.0) tag.

**Pull request merged**
