### PR TITLE
Basic Auth - OAuth Password Flow

### PR DESCRIPTION
**Pull request by benoj**
Provides ClientId/Secret in BASIC auth header and always provides user/pass in request body see #3173

### CODE REVIEW

**Comment by webron** [comment]
@bodnia can you please review this PR?

**Comment by bodnia** [comment]
@benoj can you please add one more point to drop-down to cover this case?

**Comment by frol** [comment]
@benoj You didn't need to do this! The thing you were looking for was just named incorrectly as "Request body" type. Read more in #3227.

Please, do not merge this in until read #3227! I think this PR should be closed as the implemented functionality duplicates the existing (incorrectly named) "Request body" type.

**Comment by benoj** [comment]
@bodnia  which case am i covering?

**Comment by shockey** [comment]
Closing in favor of @frol's assertions in #3227 - thanks for your efforts @benoj!

Happy to discuss if anyone would like to.

**Pull request closed without merging**
