### PR TITLE
Add support for JWT token based authentication

### PR DESCRIPTION
**Pull request by K1ll3rF0x**
This pull request adds support for JWT token based authentication in Swagger UI. 

The motivation of adding this feature is that many organizations (including my organization) secure their apis with JWT based authentication. Earlier approaches in implementing this feature have been hacky at best, or they have modified the existing authorization schemes, such as the ApiKeyAuthorization. Many have to keep their custom code in a forked repository, which is cumbersome in the long run.

The beef of this feature is in separated and optional JwtAuthorization module that can be included in index.html if JWT authentication is required. So there are only minimal changes in the Swagger UI itself. The module has been included in the example index.html.

JwtAuthorization implements the following features: 1. Login with credentials 2. Fetch the JWT token from the login endpoint and perform a light token validation 3. Inject the token automatically in Swagger UI REST queries in the Authorization header.

One can activate the JWT authorization by using the securityDefinitions option in the swagger spec:
```JSON
"securityDefinitions": {
    "jwt": {
        "type": "jwt",
        "authHeaderType": "JWT",
        "tokenPropertyName": "access_token",
        "authorizationUrl": "your-authserver-url.com/auth",
        "description": "Please log in by using your email as an username."
    }
}
```
* The **"type"** option is *required*.
* Option **"authorizationUrl"** is required. This defines URL to the REST endpoint which is used for the JWT authentication. The option respects the "schemes" protocol definitions, i.e. if "scheme":"https" or "schemes": ["https"] is used, 'https://' is injected automatically in front of the authorizationUrl.
* Option **"authHeaderType"** is *optional*. It defines the token type of the injected Authorization header. The default value is *'Bearer'*, althought using *'JWT'* is adviced.
* Option **"tokenPropertyName"** is *optional*. This defines the property name which is used for getting the token data from the auth endpoint JSON response. The default value is *'access_token'*.

One can also customize how the login payload is structured in the client before it is sent to the server, by adding the following code snippet before loading the Swagger UI:
```JavaScript
// This is the default behaviour of the module. 
// As result, payload {"username":"yourUsername","password":"yourPassword"}' will be 
// sent to your authorization endpoint.
JwtAuthorization.prototype.createPayload = function (username, password) {
    return {
        username: username,
        password: password
    };
};

// You can modify it to serve your needs:
JwtAuthorization.prototype.createPayload = function (username, password) {
    return {
        email: username,
        pwd: password
    };
};

```

### CODE REVIEW

**Comment by webron** [comment]
Thank you for the contribution but we generally do not accept PRs that extend the capabilities of the spec. The way to get it in would be to [push for direct JWT support in the spec](https://github.com/OAI/OpenAPI-Specification) and then we'd gladly add support for it in swagger-ui.

**Comment by K1ll3rF0x** [comment]
Hi @webron.
I'm slightly dissatisfied with your decision. But, maybe if you'll hear me out why I chose this approach, you'll change your mind.

I anticipated that this pull request would overlap at least with Swagger Client scope, but not with OpenAPI. The main reason why I implemented the major part of this feature as optional extension is that it is easy to deprecate. Making separate pull requests to OpenAPI and Swagger Client repositories will take their own time, but I'd like that this feature should be available to anyone using Swagger UI right now.

I propose the following approach:
1. Merge this pull request into Swagger UI repository
2. Create a pull request to OpenApi repository and additionally to Swagger Client repository if required.
3. Deprecate the JwtAuthorization extension after the pull requests have been accepted.

I am open to discussion how to improve the OpenAPi specification concerning the JWT token based authentcation. It is not for me to decide how it should be done. I engourage the Swagger community to participate in this debate.

Happy Midsummer Day to you from here in Finland!

**Comment by jannikweichert** [comment]
Would appreciate a solution as well! Thanks @K1ll3rF0x

**Comment by fletchgqc** [comment]
The best way to make progress is usually step-by-step. If you wait for everything to be perfectly in place for the ideal solution, then you usually never manage. Therefore, the process outlined by @K1ll3rF0x makes sense to me in giving a short term solution which is compatible with the vision for a possible long-term solution.

**Comment by amcdnl** [comment]
+1 for JWT

**Comment by jvkumar** [comment]
+1 for JWT

**Comment by andrew-makarenko** [comment]
+1 for JWT

**Comment by tommasop** [comment]
+1 for JWT

**Comment by evansong** [comment]
+1 for JWT

**Comment by yunixon** [comment]
+1 for JWT

**Comment by TwinbrotherPro** [comment]
+1 for JWT !!!!

**Comment by malagant** [comment]
+1 for JWT

**Comment by jeff9finger** [comment]
+1 for JWT

**Comment by dnascimento** [comment]
+1 for JWT.

**Comment by Breezess** [comment]
+1 JWT

**Comment by fehguy** [comment]
JWT is being added in the 3.0 spec

**Comment by doron2402** [comment]
👍

**Comment by verbunk** [comment]
+1 for JWT. If this happens, can we go the extra mile and implement scope support?

**Comment by vanyabrovary** [comment]
1+ for JWT

**Comment by pdushkin** [comment]
+1 for JWT.
I have previously done a lot of customization to pass my JWT bearer token in the header. Would be great to have native support for this.

**Comment by Sicaine** [comment]
I'm somehow confused. Apparently a lot of people are using JWT/oauth/whatever but can't use it in swagger properly. But there is no simple solution. And by simple i mean that i don't have to extend swagger-ui and have to maintain it somehow.

I'm not sure if i wanna hack it into my swagger ui.

I guess i will use my "Modify Headers" extension as i did before and create myself a few tokens which have a much longer duration. And just sit this issue out.

**Comment by OmgImAlexis** [comment]
@fehguy are there any recommended workarounds for now?

**Comment by pqzxc** [comment]
I would also be very interested to hear if anyone has an answer to @OmgImAlexis's question.

**Comment by doron2402** [comment]
@OmgImAlexis, 
The way I found is to create a new app that proxy all of my services. the new app can use a different authentication but also can be open public.

**Pull request closed without merging**
