### PR TITLE
Wrong usage of https://lodash.com/docs/4.17.5#lowerCase

### PR DESCRIPTION
**Pull request by ysavary**
### Description
I think that using the lodash method lowerCase() which is a method like camelCase, kebabCase,
 ... (https://lodash.com/docs/4.17.5#lowerCase) instead toLower() is just a mistake.

lowerCase('text/html') will return "text html"

Luckily, a 'text/html' content is currently handled by this if branch:
https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/response-body.jsx#L90

### Motivation and Context
Just to fix this typo and make the code cleaner if you want to handle 'text/html' with a different response-body template

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [ ] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by heldersepu** [comment]
Some UnitTests will be nice...

**Comment by shockey** [comment]
Good catch here!

As @heldersepu mentioned, some unit tests to prevent a regression would be great :wink: if writing a React component unit test isn't something you've done before, let me know and I can add one!

**Comment by webron** [comment]
@ysavary ping :)

**Comment by ysavary** [comment]
Sorry for the delay! I tried to add some basic tests but with little success. I'm not confortable with React.

**Comment by heldersepu** [comment]
@ysavary you might want to look at the Conflicting files...

**Pull request merged**
