### PR TITLE
Fix/render responses

### PR DESCRIPTION
**Pull request by ponelat**
fixes https://github.com/swagger-api/swagger-ui/issues/1297
fixes https://github.com/swagger-api/swagger-ui/issues/1186

Partially fixes... There is no place for ResponseClass headers...
fixes https://github.com/swagger-api/swagger-ui/issues/1117

Uses the exposed schema-markup from swagger-js to render Inline Model, Inline Primitives, $ref primitives in the Response Class section and the Secondary Responses at the bottom of the operations.

relies on: https://github.com/swagger-api/swagger-js/pull/486

- Add `ResponseClassView` to encapsulate that section
- ... and relative handlebars template `response_class`
- Clean up `OperationsView` (only in the affected areas ... a lot more cleaning up can take place here)
- Moved the logic of rendering Model Schemas and Models into `SignatureView`... which uses exposed methods from http://github.com/swagger-api/swagger-js
- Also adds _headers_ to the Secondary Responses.

### CODE REVIEW

**Comment by ponelat** [comment]
This won't pass until we release swagger-js with the matching PR, and update the package.json with the new release.

**Comment by fehguy** [comment]
closing as not relevant anymore

**Comment by ponelat** [comment]
I think there might be some useful code here... to fix https://github.com/swagger-api/swagger-ui/issues/1297
Seeing as its old, I can try to take a look at this soon and get it to work.

**Comment by ponelat** [comment]
So that I don't forget, I'll reopen. and close as soon as possible

**Comment by fehguy** [comment]
fixed long ago

**Pull request closed without merging**
