### PR TITLE
fix for issue 1350

### PR DESCRIPTION
**Pull request by gorfik**

### CODE REVIEW

**Comment by mpestritto** [comment]
Hi @gorfik @fehguy .  
Why isn't this commit reflected in master and in the 2.1.3 tag? Did it get stomped?  What am I missing?
I just ran into the same issue on the 2.1.3 tag. 
I ended up setting `oauth2RedirectUrl = "a-random-string"`
https://github.com/swagger-api/swagger-ui/blob/master/src/main/javascript/SwaggerUi.js#L39

**Comment by fehguy** [comment]
not sure, but I'll make sure it gets reapplied if it was clobbered.

**Comment by pkwarren** [comment]
Does the fix need to be applied to the source file here: https://github.com/swagger-api/swagger-ui/blob/52f3b6d50ec727a8f4d8ddd06388a7edb5d4f97e/src/main/javascript/SwaggerUi.js#L45 instead of dist/swagger-ui.js?

**Comment by fehguy** [comment]
yes it does.

**Comment by skwp** [comment]
This is definitely broken in release 2.1.4. This fix did not get applied.

**Pull request merged**
