### PR TITLE
fix: optional empty validation

### LINKED ISSUE #6998: Query with example turns field into required
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome, safari
 - Version: chrome 88.0.4324.192, safari 14.0.3 (16610.4.3.1.4)
 - Method of installation: Swashbuckle.AspNetCore
 - Swagger-UI version: 3.42.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: example
  version: v1
paths:
  /example:
    get:
      parameters:
        - name: page
          in: query
          description: Page number
          schema:
            type: integer
            format: int32
          example: 1
      responses:
        '200':
          description: OK
```

### Describe the bug you're encountering
When a query param has the example set, if we try to remove the value to send an empty query string, validation fails like the field is required.

### To reproduce...

1. Go to query filed
2. Remove the value
3. Click Execute

### Expected behavior

When example is set the query field must not be required.

### Screenshots

Screenshot 2021-02-25 at 01 16 42

Screenshot 2021-02-25 at 01 18 21

Screenshot 2021-02-25 at 01 16 26

### PR DESCRIPTION
**Pull request by mathis-m**
### Description

internal logic does send null to validation in case of empty parameter input. This should be included in the validation, This was introduced with:
5c4dfc2d	Mahtis Michel	02/03/2021 09:29 PM	feat: enhance parameter validation (#6878) 

I decided to refactor the validation condition to more readable state.
I think this is even more readable then the comment before.

### Motivation and Context

Fixes #6998

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tim-lai** [comment]
@mathis-m PR merged! Thanks for the contribution!

**Comment by dferretti** [comment]
I know I'm late to the party, but I think this is relevant to this PR. I believe you can have a non-required string array param in the query, with `minItems: 1` to represent "either don't pass it at all, or if you do it must include at least 1 item". Well, I think so anyway..
I know you can have a non-required, non-nullable parameter meaning "either don't provide it, or provide a non-null value, but never provide `x: null`". So I believe you can additionally constrain the array with `minItems: 1` IIRC.

I am trying this in https://editor.swagger.io :
```yaml
openapi: 3.0.3
info:
  title: Test
  version: 1.0.0
paths:
 /test:
   get:
     parameters: 
       - name: names
         in: query
         required: false
         schema:
           type: array
           minItems: 1
           items:
             type: string
     responses:
       200:
         description: OK
```

I would like to be able to test omitting the `names` parameter by not providing any elements, but swagger-ui tells me I must provide at least 1 value.

Should these minItems validation checks include whether or not the param is required? Or am I way off here and the spec doesn't allow that?

**Comment by dferretti** [comment]
Actually I may be off on what I'm talking about anyways - I was initially reading this older PR https://github.com/swagger-api/swagger-ui/pull/6878, but poking through this PR I do see some null/required checking going on. Maybe editor.swagger.io is not running this code yet (is there an easy way to see what version it is running?).
Tomorrow I'll try just running swagger-ui locally on this version and see if it still is happening.

**Comment by mathis-m** [comment]
@dferretti you are right when there is no value provided and the param is optional there should not be any error.

Have moved this to  issue #7111.
#7112 will fix this.

**Comment by dferretti** [comment]
Awesome thank you!

**Pull request merged**
