### PR TITLE
make redirect_uri global

### PR DESCRIPTION
**Pull request by sebastianwahn**
Make redirect_uri global as it is in swagger.auth.js:164

```
redirect_uri = redirectUrl;
```

If the redirect_uri is not global, the oauth request (swagger-auth.js - processOAuthCode) is missing this value:

```
window.processOAuthCode = function processOAuthCode(data) {
  var OAuthSchemeKey = data.state;
  var params = {
    'client_id': clientId,
    'code': data.code,
    'grant_type': 'authorization_code',
    'redirect_uri': redirect_uri              // undefined if not global
  };

  if (clientSecret) {
    params.client_secret = clientSecret;
  }

  $.ajax(
  {
    url : window.swaggerUi.tokenUrl,
    type: "POST",
    data: params,
    success:function(data, textStatus, jqXHR)
    {
      onOAuthComplete(data, OAuthSchemeKey);
    },
    error: function(jqXHR, textStatus, errorThrown)
    {
      onOAuthComplete("");
    }
  });
};
```

### CODE REVIEW

**Comment by fehguy** [comment]
but redirectUrl _is_ global:

```
var redirectUrl = window.oAuthRedirectUrl || defaultRedirectUrl;
```

So if you want to set a global redirectURL, that's where you do it (see https://github.com/swagger-api/swagger-ui/pull/2179/files#diff-6597f567105c15be158c097f2226a489R100).

**Comment by sebastianwahn** [comment]
I see. but swagger-auth.js expects 'redirect_uri' to be global. Either make 'redirect_uri' global as in my PR or exchange 'redirect_uri' to 'redirectUrl' and make 'redirectUrl' global.
Currently, only 'window.oAuthRedirectUrl' seems to be global available.

**Comment by fehguy** [comment]
I must be missing something, so please bear with me.  If `window.oAuthRedirectUrl` is global, and `redirectuUrl` is set to that value, then it will always be configured from a global variable, correct?

**Comment by fehguy** [comment]
@sebastianwahn if you can give more info, we can work this in, but if not, I'll consider it solved and close the PR.

**Comment by sebastianwahn** [comment]
@fehguy Sorry for the late answer.

redirectUrl is defined with "var" making it only visible for the current function.

```
var redirectUrl = window.oAuthRedirectUrl || defaultRedirectUrl;
```

Also redirect_uri is local (with "var"):
```
var redirect_uri = redirectUrl;
```

But in this code:
```
var params = {
    'client_id': clientId,
    'code': data.code,
    'grant_type': 'authorization_code',
    'redirect_uri': redirect_uri              // undefined if not global
  };
```
the variable `redirect_uri` needs to be global.

**Pull request merged**
