### PR TITLE
fix(UI): allow summary path to be selectable

### PR DESCRIPTION
**Pull request by freakzlike**
### Description

This allows the user to select and copy the path within the summary.

### Motivation and Context

Currently it is not possible to copy the API path from the swagger-ui and it must by typed by yourself.

### How Has This Been Tested?

Open any API, try to select the path with the Mouse + Drag.
I tried to test this with Cypress but seems to be a bit difficult.

### Screenshots (if appropriate):

swagger

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [X] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [X] are not breaking changes.

### Documentation
- [X] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [X] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tim-lai** [comment]
@freakzlike Thanks for the PR! While this change does make the operation path selectable, it also expands/collapses the operation block on mouse click release (e.g. end selection of path), which a user may not want to do. I do agree it would be improved usability to be able to select the operation path (and separately, the operation description), but as-is, this PR introduces a different usability issue. Open to changes however, let me know, thanks!

**Comment by tomasbruckner** [comment]
@tim-lai so what is a recommended way to copy the path? Is there other way than right clicking it in browser and inspecting the element and copying it from the HTML?

**Comment by tim-lai** [comment]
> so what is a recommended way to copy the path? Is there other way than right clicking it in browser and inspecting the element and copying it from the HTML?

Unfortunately, I think this is a UX flaw. A different hacky way would be to use the "Try It Out" -> execute, and copy/paste the `Request Url` code tidbit.

**Comment by tomasbruckner** [comment]
@tim-lai what would be the recommended way to fix it then? I can help with that but would like to discuss how it should work so I don't spend my time implementing something that wouldn't be approved at the end.

I am thinking of something like a button that copies the URL to the clipboard? It could be next to the arrow down/up in the collapse.

Or it could be text somewhere in the opened collapsible block (above parameters tab or something like this). So you could select it and copy it as much as you want and it wouldn't open/close the collapsible block.

**Comment by tomasbruckner** [comment]
@tim-lai I opened a PR here https://github.com/swagger-api/swagger-ui/pull/8094

**Comment by tim-lai** [comment]
superceded by #8094. Closing this PR.

**Pull request closed without merging**
