### PR TITLE
Fix basic-auth.jsx: do not require password in UI

### LINKED ISSUE #5410: Basic auth shouldn't require a password change reverted?
I am using swagger-ui version 3.19.5 (via Swashbuckle.AspNetCore.SwaggerUI v4.0.1) with an API that uses basic auth with a username but no password.

(One example of a high traffic and well-designed API that uses this approach for authentication is the [Stripe API](https://stripe.com/docs/api/authentication).)

It looks like in #2114 swagger-ui was changed to not require a password, but in the authorize dialog the password [seems to always be required](https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/auth/basic-auth.jsx).

Was reverting this change intentional? Is there a workaround I can use to make it optional?

### PR DESCRIPTION
**Pull request by Simran-B**
### Description

The `password` input is not PropTypes.string.isRequired, but the HTML markup wrongly makes it mandatory (`required="required"`).

### Motivation and Context

Fixes #5410 (a regression of #2156)

### How Has This Been Tested?

Removed `required` attribute from input element in Chrome, then tried the basic authorization with success. Without the fix, Swagger UI asks you to fill out the field.

### Screenshots (if appropriate):

Basic auth modal error

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...

- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation

- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests

- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Simran-B** [comment]
There is actually more to it... if the password is empty, then somewhere `undefined` is cast to a string and ends up in the base64-encoded password instead of using an empty string:
- `"root:undefined"` → `"cm9vdDp1bmRlZmluZWQ="` ❌
- `"root:"` → `"cm9vdDo="` ✔

Will try to fix it.

**Comment by Simran-B** [comment]
There seems to be a fairly large rabbit hole right there...

First off, trying to build Swagger UI under Windows without Docker is a challenge, to say the least. Anyway, the files in `dist/` do get updated, but I only see the UI changes.

At first I added checks for `password` and `clientSecret` to default to an empty string if it's falsy. It didn't work, so I commented out the code which concats the password to the user name followed by a colon. This does not show any effect either. I changed four different places where `btoa()` is used, but to no avail.

Frankly, I'm lost. I am either looking at the wrong pieces of code, or something fishy is going on.

```diff
diff --git src/core/components/auth/basic-auth.jsx src/core/components/auth/basic-auth.jsx
index 8d45d210..14998028 100644
--- src/core/components/auth/basic-auth.jsx
+++ src/core/components/auth/basic-auth.jsx
@@ -71,7 +71,7 @@ export default class BasicAuth extends React.Component {
         </Row>
         <Row>
           <label>Password:</label>
-            {
+            { // where is this used?
               username ? <code> ****** </code>
                        : <Col><Input required="required"
                                      autoComplete="new-password"
diff --git src/core/plugins/auth/actions.js src/core/plugins/auth/actions.js
index 7c6c0951..3b2771ee 100644
--- src/core/plugins/auth/actions.js
+++ src/core/plugins/auth/actions.js
@@ -87,7 +87,7 @@ export const authorizePassword = ( auth ) => ( { authActions } ) => {
       break
 
     case "basic":
-      headers.Authorization = "Basic " + btoa(clientId + ":" + clientSecret)
+      headers.Authorization = "Basic " + btoa(clientId + ":" /*+ clientSecret*/)
       break
     default:
       console.warn(`Warning: invalid passwordType ${passwordType} was passed, not including client id and secret`)
@@ -109,7 +109,7 @@ function setClientIdAndSecret(target, clientId, clientSecret) {
 export const authorizeApplication = ( auth ) => ( { authActions } ) => {
   let { schema, scopes, name, clientId, clientSecret } = auth
   let headers = {
-    Authorization: "Basic " + btoa(clientId + ":" + clientSecret)
+    Authorization: "Basic " + btoa(clientId + ":" /*+ clientSecret*/)
   }
   let form = {
     grant_type: "client_credentials",
@@ -136,7 +136,7 @@ export const authorizeAccessCodeWithFormParams = ( { auth, redirectUrl } ) => (
 export const authorizeAccessCodeWithBasicAuthentication = ( { auth, redirectUrl } ) => ( { authActions } ) => {
   let { schema, name, clientId, clientSecret } = auth
   let headers = {
-    Authorization: "Basic " + btoa(clientId + ":" + clientSecret)
+    Authorization: "Basic " + btoa(clientId + ":" /*+ clientSecret*/)
   }
   let form = {
     grant_type: "authorization_code",
diff --git src/core/plugins/auth/reducers.js src/core/plugins/auth/reducers.js
index 6e4d0702..1a72dac9 100644
--- src/core/plugins/auth/reducers.js
+++ src/core/plugins/auth/reducers.js
@@ -30,7 +30,7 @@ export default {
 
         map = map.setIn([key, "value"], {
           username: username,
-          header: "Basic " + btoa(username + ":" + password)
+          header: "Basic " + btoa(username + ":" /*+ password*/)
         })
 
         map = map.setIn([key, "schema"], security.get("schema"))
diff --git src/core/plugins/oas3/components/http-auth.jsx src/core/plugins/oas3/components/http-auth.jsx
index 5df10ddf..376fe96b 100644
--- src/core/plugins/oas3/components/http-auth.jsx
+++ src/core/plugins/oas3/components/http-auth.jsx
@@ -79,10 +79,9 @@ export default class HttpAuth extends React.Component {
         </Row>
         <Row>
           <label>Password:</label>
-            {
+            { // used for the authorize modal
               username ? <code> ****** </code>
-                       : <Col><Input required="required"
-                                     autoComplete="new-password"
+                       : <Col><Input autoComplete="new-password"
                                      name="password"
                                      type="password"
                                      onChange={ this.onChange }/></Col>
```

**Comment by Simran-B** [comment]
I tracked it down to the Swagger client, `swagger-ui\node_modules\swagger-client\dist\index.js:3550`:

```js
function applySecurities(...
    ...
        if (type === 'http') {
          if (schema.scheme === 'basic') {var
            username = value.username,password = value.password || ""; // do not cast undefined to a string here!
            var encoded = external_btoa_default()("".concat(username, ":").concat(password));
            result.headers.Authorization = "Basic ".concat(encoded);
```

There is also another place on line 3670, but not sure when that is used:

```
function build_request_applySecurities(...
    ...
            value.base64 = external_btoa_default()("".concat(value.username, ":").concat(value.password || "")); // when is this used?
            result.headers.authorization = "Basic ".concat(value.base64);

```

**Comment by shockey** [comment]
thanks @Simran-B!

**Pull request merged**
