### PR TITLE
housekeeping: migrate to release-it v11

### PR DESCRIPTION
**Pull request by webpro**
### Description

As I was working on release-it v11, I tried a few projects in the wild and yours was one of them (also since it has a bit of a custom release setup). So why not open a PR if I have the changes already :)

### How Has This Been Tested?

`npm run automated-release`

### My PR contains... 

- [x] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [x] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shockey** [comment]
Rebased!

**Comment by shockey** [comment]
^ installed `source-map-support` to fix tests... looks like release-it@7 was pulling it in before, which was covering for me not declaring it as a devDependency:

```sh
swagger-ui@3.23.0 /Users/kyle/Code/ui
├─┬ @babel/register@7.4.4
│ └── source-map-support@0.5.12 
├─┬ release-it@7.6.1              <----- this
│ └─┬ babel-register@6.26.0
│   └── source-map-support@0.4.18 
└─┬ terser-webpack-plugin@1.3.0
  └─┬ terser@4.1.2
    └── source-map-support@0.5.12 
```

**Comment by shockey** [comment]
thanks @webpro!

**Comment by webpro** [comment]
You're welcome! v12 has already been released in the meantime. You could safely upgrade (but the `scripts` have been deprecated, it's `hooks` now).

**Pull request merged**
