### PR TITLE
Remove default of opening links in new tab in markdown content

### LINKED ISSUE #3473: Markdown link open a new tab/window
- swagger-ui version: v3.0.21

```
swagger: '2.0'
info:
  version: "1.0.0-alpha"
  title: Answer to life
  description: |

      # Documentation

      This endpoint can solve the problems of the world:
      [look at its specification](#/WorldEndpoint)

paths:
  #  endpoints
  /:
    get:
      summary: the answer is 42
      description: |
        # Information
          for understanding this endpoint you have to have a look at the
          [Documentation](#/Documentation)
      operationId: getanswer
      tags:
        - WorldEndpoint
      responses:
        200:
          description: The api information is returned. 
```

Using this example is impossible to have a normal navigation between the two generated paragraph.

The link from the "Documentation" section open a new tab/window.
The link from the endpoint it isn't referring the paragraph.

As a solution I would like to suggest these two things:

- intercept the default href behaviour and add the "preventdefault" and the call to the "scrolltosource" (into the Markdown provider)
- add ids to the h1 - h3 header in order to use the solution mentioned above.

the problem has been tested here: http://editor.swagger.io/#/

### PR DESCRIPTION
**Pull request by owenconti**
Fixes #3473 
Remove default of opening links in new tab in markdown content

### CODE REVIEW

**Comment by webron** [comment]
@owenconti The opening of links in a new tab is the expected behavior. #3473 is talking about something a bit different - _local_ links should not open in new tabs - that is, other anchors in the same instance of swagger-ui, should just jump to those anchors. However, I'm not sure our markdown parser generates those anchors in the first place, making this a harder problem to solve.

**Comment by owenconti** [comment]
@webron Wouldn't it be more user friendly if we gave the user the choice of opening in a new tab or not? If we do that, we can handle the local links without any issue.

**Comment by webron** [comment]
Even if we do, there's a difference between local links and external ones. It never makes sense for local links to open in an external tab. 

As for external links - we used to open them in the same tab, but due to (very) popular demand, implemented the opening in a new tab. It makes sense - if you navigate away from the documentation every time, it can break the flow.

**Comment by owenconti** [comment]
I don't see how we can solve/add local links unless we remove the automatic addition of `_target="blank"` to all of the links in Markdown content. 

Closing this PR.

**Pull request closed without merging**
