### PR TITLE
#3135 - Add request duration to response details

### LINKED ISSUE #3135: Show Response time for all calls next to Response Body tag.
Not sure if this is already available or easy to add. It would be very useful to show response time for the calls made on the swashbuckle UI, just like postman shows the response time.

### PR DESCRIPTION
**Pull request by owenconti**
Fixes #3135 - Add `duration` property to the response object so the duration can be displayed in the component.

When initially reviewing the issue, I assumed setting the duration should be part of `swagger-js`, however it seems like the `swagger-ui` spec plugin is actually response for making the request. Please correct me if my assumption is incorrect.

Here's what the UI looks like:

screen shot 2017-06-25 at 9 16 00 am

I can rename the field to "Response duration" too since the other fields start with "Response". I just wanted it to be clear that the value displayed is the round trip time, to the server and back, not just the 'response' portion of the request.

### CODE REVIEW

**Comment by webron** [comment]
I think it's ok for now that the functionality is part of the UI. However, I think this should be a configuration (whether to display it *and* measure it), and by default it should be off. Can you add that?

**Comment by owenconti** [comment]
@webron Added the config option. The URL parameter won't work though because the config type is a boolean and the application parses ?displayRequestDuration=true as a string. Known bug?

**Comment by webron** [comment]
I don't think it's a known bug, but it would affect other configs as well. I'd file a separate ticket for that. As long as you can pass it as a config parameter to the constructor (and the default is false), it's good.

**Comment by shockey** [comment]
^^ Boolean config discussion can be found at #3302.

As I mentioned in the other ticket, I think we should assume string values in configs for now, and migrate to booleans with a different PR.

**Comment by shockey** [comment]
> When initially reviewing the issue, I assumed setting the duration should be part of swagger-js, however it seems like the swagger-ui spec plugin is actually response for making the request.

@owenconti close! The spec plugin is the abstraction layer for the rest of the UI for requests, but the reference to `fn.execute` uses the `execute` function from swagger-client (aka swagger-js), which is introduced to the plugin system here: https://github.com/swagger-api/swagger-ui/blob/master/src/core/plugins/swagger-js/index.js. That execute call actually fires the request.

**Pull request merged**
