### PR TITLE
fix: add aria label to select element for content types

### PR DESCRIPTION
**Pull request by gileswells**
The goal here is to add aria-labels to the dropdowns to provide people using assistive tech like screen readers with more information about the page / part of the page they're interacting with.

### Description

We added an `ariaLabel` prop to the ContentType component and then updated instances where `<ContentType />` is used to include the new prop.

### Motivation and Context

At the VA we have always have a focus on accessibility and SwaggerUI has been on our radar as something we use that could receive some accessibility love. There isn't any specific issue to link on this repo but there have been past accessibility issues that we hope overlap.

### How Has This Been Tested?

We've tested this using VoiceOver on Mac and JAWS for Windows. With there being no visual changes for this we didn't see any regressions elsewhere in the project.

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [x] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by mathis-m — APPROVED** [review]

**Review by tim-lai — APPROVED** [review]

**Comment by tim-lai** [comment]
@gileswells Thanks for the PR! It looks good. If you can rebase, or better yet given asynchronous timing, allow maintainers to make edits to this PR, I will be able to merge this PR.

**Comment by gileswells** [comment]
@tim-lai I thought I had checked that box. I pulled master back to our fork. If there's something else you need  or if there's a better way to submit a PR I'll keep an eye out here but I'm also available on the IRC channel if that's easier.

**Comment by gileswells** [comment]
@tim-lai sorry missed your comment. This is merged again for you.

**Comment by tim-lai** [comment]
@gileswells PR merged! Thanks again!

**Pull request merged**
