### PR TITLE
Add support of authorization_code in oauth2-redirect.html

### LINKED ISSUE #6741: oauth2-redirect.html not honoring "authorization_code" flow
### Describe the bug you're encountering

I'm using a security scheme with an `openIdConnectUrl` with an authorization server that support the "authorization_code" grant type.

When I attempt to login with the authorization code flow, the authorization server performs the login and redirects back to `oauth2-redirect.html` with the code in the path param.  So far so good.  Unfortunately, the javascript on `oauth2-redirect.html` page is not properly pulling the code because the `oauth2.auth.schema.get("flow")` is equal to `authorization_code` (as viewed via a chrome dev tools breakpoint), but [the script is expecting either `authorizationCode` or `accessCode`](https://github.com/swagger-api/swagger-ui/blob/f35acced49d027cf1f645189dcae2edb4b1f41a3/dist/oauth2-redirect.html#L34-L35).

When I set a breakpoint in chrome dev tools, and change the `oauth2.auth.schema.get("flow")` value to `authorizationCode`, the script works properly, and I am able to authenticate successfully.

I'm not sure if the fix should be to change the script in `oauth2-redirect.html` to look for `authorization_code` in addition to `authorizationCode`, or to somehow change `oauth2.auth.schema.get("flow")` to be `authorizationCode` (I believe it's populated [here](https://github.com/swagger-api/swagger-ui/blob/0807687f9161a3293ff679ac9a1208df24921dd1/src/core/plugins/oas3/auth-extensions/wrap-selectors.js#L72) for openIdConnect cases).

### To reproduce...

1. Configure a flow with openIdConnectUrl that supports `authorization_code` grant type
2. Attempt to login to with authorization_code grant type
4. See error because code is not passed to token endpoint

### Expected behavior
I expect the code to be retrieved from the redirect request, and successfully passed to the token url.

### Q&A 
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86.0.4240.75
 - Method of installation: springdoc-openapi 1.5.2
 - Swagger-UI version: 3.38.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### PR DESCRIPTION
**Pull request by IhnatKlimchuk**
Fixes #6741 [Issue - oauth2-redirect.html not honoring "authorization_code" flow](https://github.com/swagger-api/swagger-ui/issues/6741)

### Description
Add support of `authorization_code` flow similar to other cases: [example](https://github.com/swagger-api/swagger-ui/blob/0807687f9161a3293ff679ac9a1208df24921dd1/src/core/oauth2-authorize.js#L35)

### Motivation and Context
This fix required to proceed with [Swashbuckle.AspNetCore PR](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1941) that is required for [Issue 1241](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1241)

### How Has This Been Tested?
Testing is pending

### My PR contains... 
- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by AlexeyBogdan95 — APPROVED** [review]

**Comment by tim-lai** [comment]
@IhnatKlimchuk Thanks for the PR! Please add tests that validate desired behavior to https://github.com/swagger-api/swagger-ui/blob/master/test/unit/core/oauth2-authorize.js

**Review by tim-lai — CHANGES_REQUESTED** [review]
Please add tests that validate desired behavior to https://github.com/swagger-api/swagger-ui/blob/master/test/unit/core/oauth2-authorize.js

**Comment by IhnatKlimchuk** [comment]
@tim-lai thank you for a feedback, will add tests soon.

**Comment by IhnatKlimchuk** [comment]
@tim-lai I hope I understood you correctly related to tests. OpenAPI support was already added before me so it's actually a bug fix, rather than new feature. Please let me know your thoughts on that.

**Review by tim-lai — APPROVED** [review]

**Comment by tim-lai** [comment]
@IhnatKlimchuk PR merged! Thanks for the contribution! Fyi, I consider this a feature because it supports a "new" parameter type.

**Pull request merged**
