### PR TITLE
Fix for #2004

### PR DESCRIPTION
**Pull request by patrickhulce**

### CODE REVIEW

**Comment by xiaolongyuan** [comment]
thanks , +1

**Comment by pluma** [comment]
Could someone please merge this and publish a new release?

**Comment by fehguy** [comment]
I will merge this, but be aware that if you don't have a `param.type`, you have an invalid spec, and it technically should not be supported.

**Comment by pluma** [comment]
@fehguy Negative. According to the spec and the editor the `type` property is forbidden on body parameters and must instead be specified as part of the schema (using either `schema` or `$ref`):

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object

I'm not sure whether this PR indeed fixes the underlying root cause of #2004 but anything is better than Swagger UI breaking completely when rendering a perfectly valid schema.

**Comment by patrickhulce** [comment]
Awesome thanks @fehguy and @pluma !

**Pull request merged**
