### PR TITLE
Add test for console errors

### PR DESCRIPTION
**Pull request by mohsen1**

### CODE REVIEW

**Comment by mohsen1** [comment]
@fehguy it fails because something is broken
screen shot 2015-01-30 at 1 55 27 pm

**Comment by fehguy** [comment]
Thanks - looking at this.

**Comment by olensmar** [comment]
ResourceView.prototype.initialize and MainView.prototype.initialize weren’t assigning the opts variable to this.options, adding

this.options = opts

In both methods fixed the error… 

Do you want a PR for this? Or should it be fixed in coffeescript somehow?

**Comment by mohsen1** [comment]
@olensmar that would be appreciated

**Comment by fehguy** [comment]
@mohsen1 i think something in the dependency upgrades caused some breakage.  Now I get that `@options` are not set throughout the model.

Were they in a global helper or something before?

**Comment by mohsen1** [comment]
Sorry I accidentally deleted my branch. Lets fix those errors first, then I will make a PR from my branch.

**Comment by fehguy** [comment]
I think in the dependency upgrades it broke. It's not a single variable, it happens across the board

**Comment by mohsen1** [comment]
Let me try/error with reverting the dependencies I updated

**Comment by fehguy** [comment]
this commit is when it broke:

dc0a54808fcb5154cf03df4c9382286acbb6896a

Upgrade to handlebars 1.1

**Pull request closed without merging**
