### PR TITLE
Proposal: improve the xml schema to support `CDATA`(the data does not need to be escaped)

### PR DESCRIPTION
**Pull request by TheNorthMemory**
### Description

1. implement the xml schema to support `CDATA` feature, see [this](https://www.npmjs.com/package/xml#xmlobject)
2. let `additionalProperties: {}` works same as `additionalProperties: true`

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [x] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [x] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by shockey — APPROVED** [review]

**Review by shockey — DISMISSED** [review]
[XML Objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#xml-object) are not allowed to have a `CDATA` field.

If this is changed to use a field named `x-cdata` instead, I'd be open to merging it 😄

**Comment by TheNorthMemory** [comment]
@shockey I've changed CDATA insteed of x-cdata @ 50a4b4c , do I need pull requests ?

**Comment by TheNorthMemory** [comment]
@shockey the xml `cdata` feature is ready for merging

**Comment by shockey** [comment]
thanks @TheNorthMemory, I'm looking at whether this could be better suited as a plugin - stay tuned 😄

**Comment by TheNorthMemory** [comment]
@shockey ops, the xml function was already as a plugin (`src/core/plugins/samples/fn.js`), does it need another one ?

**Comment by TheNorthMemory** [comment]
the `x-cdata` feature is scoped @ [here](https://www.npmjs.com/package/@thenorthmemory/swagger-ui-dist), an  example is [here](https://thenorthmemory.github.io/wechat-swagger/#/支付∙服务商∙付款码支付/post__wxpay_pay_micropay), hopes may help somebody.

**Comment by tim-lai** [comment]
@TheNorthMemory Following up on this long outstanding PR... There has been subsequent changes to the use of `additionalProperties === true`, specifically #5072. If this feature is still needed, please update the plugin and I would be happy to re-review. Thanks!

**Comment by TheNorthMemory** [comment]
Yep, the `CDATA` data is easier readable, let me update this PR soon

**Comment by TheNorthMemory** [comment]
@tim-lai merged, on the top of this PR, it supporting the following display now. It's characters safe and easier readable both on `xml` and `json` definitions.

```xml
<foo><![CDATA[&bar]]></foo>
<bar><![CDATA[<2]]></bar>
```

**Comment by tim-lai** [comment]
@TheNorthMemory Thanks for updating! One more request, can you add some notes about usage of this feature to documentation?

**Comment by TheNorthMemory** [comment]
This was the `src/core/plugins/samples/fn.js` implementation. Tow `no break` change. Let me find a place to record those features.

**Comment by TheNorthMemory** [comment]
I've quickly check the [OAI's #1532](https://github.com/OAI/OpenAPI-Specification/issues/1532) where were discussed about the xml's `CDATA`. In my opinion, the `x-cdata` documentation shall be better to place onto OAI project. Because it's about the `yaml/json/xml` definitions. The `x-cdata` is only a `true/false` flag to point out `the data does not need to be escaped`, the default behavior(`false` or `null`) as usual. When `setter` is on `true`, means literal. That's it.

The usage examples here:

[wechatpay's micropay.request](https://github.com/TheNorthMemory/wechat-swagger/blob/c536cec78ea983667c62781e9084a36ee90933a6/src/payments/micropay.yaml#L143-L150) sample:

```yaml
    scene_info:
      xml:
        x-cdata: true
      type: string
      description: +场景信息
      example: '{"store_info" : {"id": "SZTX001","name": "腾大餐厅","area_code": "440305","address": "科技园中一路腾讯大厦" }}'
      maxLength: 256
      nullable: true
```

[wechatpay's querycombinedorder.response](https://github.com/TheNorthMemory/wechat-swagger/blob/c536cec78ea983667c62781e9084a36ee90933a6/src/payments/querycombinedorder.yaml#L134-L146) sample:

```yaml
    - type: object
      xml:
        name: xml
      required:
        - sub_order_list
      properties:
        sub_order_list:
          xml:
            x-cdata: true
          type: string
          description: +子单信息
          example: '{"order_num": 3,"order_list": [{"appid":"wx2421b1c4370ec43b","mch_id":"1230000109","openid":"oUpF8uMuAJO_M2pxb1Q9zNjWeS6o","total_fee":100,"cash_fee":100,"transaction_id":"4217752501201407033233368018","out_trade_no":"12177525012","attach":"test001","time_end":"20171030133525"},{"appid":"wx2421b1c4370ec43b","mch_id":"1230000109","openid":"oUpF8uMuAJO_M2pxb1Q9zNjWeS6o","sub_appid":"wx2421b1c437055ce","sub_mch_id":"1230000108","sub_openid":"oUp3rfMuAJO_123xb1Q9zNjWedco","trade_type":"JSAPI","total_fee":100,"cash_fee":100,"transaction_id":"4217752501201407033233368018","out_trade_no":"12177525012","attach":"test001","time_end":"20171030133525"},{"appid":"wx2421b1c4370ec43b","mch_id":"1230000109","openid":"oUpF8uMuAJO_M2pxb1Q9zNjWeS6o","trade_type":"JSAPI","total_fee":100,"fee_type":"USD","cash_fee":100,"cash_fee_type":"CNY","transaction_id":"4217752501201407033233368018","out_trade_no":"12177525012","attach":"test001","time_end":"20171030133525","rate_value":"65000000"}]}'
          maxLength: 10240
```

Another one about the `additionalProperties: {}`, that was already on [OAI's 3.0.1 spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md). This implement shall more compatible with it.

> additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema.

When it's `true`, should mean `anything`. While it is defined as `plainObject` without any properties, it should mean `anything` too.

**Comment by webron** [comment]
@TheNorthMemory Apologies for jumping in this late in the game, but I'm afraid we won't be able to accept the PR. While it's great that spec supports extensions, we have to limit our support for custom extensions in the spec. In rare cases, we may choose to add support for such extensions, if we feel that it makes sense for the general Swagger UI users.

Unfortunately, for `x-cdata` it is not the case. It's just unlikely it'll be helpful to the majority of our users. This is a good example of where plugins come in and you can customize support for such an extension for your own needs. It doesn't mean the work is lost, just that it's not going to be in the core code.

**Comment by TheNorthMemory** [comment]
I'd re-researched some projects, eg: [node-xmlrpc#71](https://github.com/baalexander/node-xmlrpc/pull/71), [savon#50](https://github.com/savonrb/savon/issues/50), those discussed about the `CDATA` features and did solved the escaping. This feature shall more clear explainations about the data exchange between the `xml` based system. In another words, in my understood, the `core` of the Swagger UI should sound something like this, `providing an easier way to read the doc and participate in those services`. Those escaped data is not easier readable at least. About the participation, there were some projects about `dubbo` and `Swagger UI` integration, for example [my project](https://github.com/TheNorthMemory/dubbo-swagger/blob/master/README_en-US.md), the developers won't need care the details about the `dubbo protocol` and `hessian serilization` anymore, they just need write and place a right `OAI` spec and then do the `Try it out` enough. This should be the key points of the Swagger UI.

Here's a Chinese proverb about that `Path is shown up only when thousands of people walk through.` I've also known this feature, `x-cdata` implementation, is not standard OAI's specification. Maybe somebody like me need this feature too. So why cannot try?

**Pull request closed without merging**
