### PR TITLE
Remove line breaks before footer.

### PR DESCRIPTION
**Pull request by aleung**
There were two hard line breaks before footer, which showed a large gap between API resources and footer with my customized CSS. It's unable to narrow the height of line break by CSS.

I removed it from template. If extra space before footer is required, margin can be added into CSS: 

``` css
.swagger-section .swagger-ui-wrap .footer {
  margin-top: 20px;
}
```

remove-br

### CODE REVIEW

**Comment by mohsen1** [comment]
LGTM. 
Please add the CSS you're suggesting and run `gulp` to recompile `dist` folder.

**Comment by webron** [comment]
@aleung - sorry for the delay, I guess this needs to be rebased again (though we can probably merge it manually as well).

**Comment by aleung** [comment]
@webron It's ready to merge now.

**Comment by fehguy** [comment]
added this logic

**Pull request closed without merging**
