### PR TITLE
Switch from cheap-module-source-map to source-map (Fixes #3263)

### LINKED ISSUE #3263: Unable to debug in production using source maps
Perhaps this is just my misunderstanding of how webpack `cheap-module-source-map` is supposed to work, but:

1. Open http://petstore.swagger.io/ in Chrome (any Chrome version will do...I'm using v61)
2. Open DevTools, and go to the Sources panel
3. In the Sources list expand `Top`, then `webpack://`, and click on `swagger-ui-bundle.js`
4. In the panel where I presume the original (source mapped) code *should* appear, it is empty (see attached pic)

image

I can open the bundle and view the minified, bundled code; but there doesn't seem to be a way to view the original (source mapped) code.

image

I've also tried Firefox & Safari, with no success.

Is this supposed to work?

### PR DESCRIPTION
**Pull request by scottohara**
This tiny PR simply changes the type of source maps that are used for the webpack config when `specialOptions.sourcemaps` is passed as `true`.

The `source-map` option generates higher fidelity source maps, and the previous `cheap-module-source-map` option wasn't displaying correctly in DevTools.

This is how the original source now appears in DevTools when the `source-map` option is used:

image

### CODE REVIEW

**Comment by shockey** [comment]
@scottohara the sourcemaps look great, but this option generates _huge_ sourcemaps:

```
                   Asset     Size  Chunks             Chunk Names
    swagger-ui-bundle.js   1.2 MB       0  [emitted]  swagger-ui-bundle
swagger-ui-bundle.js.map  8.56 MB       0  [emitted]  swagger-ui-bundle
```
```
             Asset      Size  Chunks             Chunk Names
     swagger-ui.js    266 kB       0  [emitted]  swagger-ui
 swagger-ui.js.map   1.78 MB       0  [emitted]  swagger-ui
```
```
                              Asset     Size  Chunks             Chunk Names
    swagger-ui-standalone-preset.js   280 kB       0  [emitted]  swagger-ui-standalone-preset
swagger-ui-standalone-preset.js.map  1.78 MB       0  [emitted]  swagger-ui-standalone-preset
```

 I'd like to explore moderate options here - ideally, sourcemaps would be 1:1 with the minified source size. 

Maybe `cheap-source-map` would get us there?

**Comment by scottohara** [comment]
@shockey Just tried `cheap-source-map`, but unfortunately it has the same DevTools experience as `cheap-module-source-map` did (i.e. doesn't seem to work as expected - for me at least - in DevTools).

Normally I wouldn't consider the size of sourcemaps to be a concern, as they don't affect the performance of the site/app for typical end-users.

Sourcemaps aren't downloaded by the browser unless:
(a) DevTools is open, and
(b) the `Enable JavaScript source maps` DevTools setting is enabled


That said, I will concede that _as an npm package_ the inclusion of large sourcemaps in `dist` will have an impact on `npm install` times etc.

So ultimately this becomes a question of whether an increase in the size of the distribution outweighs the benefits of a better debugging experience.

I'll leave this PR here as is (with `source-map`), and let you and the team make a call as to which way you feel is best to go.

Hopefully in the meantime, webpack and/or DevTools can resolve the issue that prevents `cheap-module-source-map` from working as expected (which would make this PR redundant).

Thanks anyway for taking the time to review.

**Comment by shockey** [comment]
Sounds good. Thanks for the work on this, @scottohara.

I'm going to circle back on this once we have Webpack 2.0 in master (there's an effort for that going on currently), maybe it will solve the problems with the smaller devtools options.

**Comment by shockey** [comment]
Going to close this as we aren't going with `source-map` due to size concerns.

Nonetheless, #3263 will remain on our radar 😄 

thanks @scottohara!

**Pull request closed without merging**
