### PR TITLE
Rebased @brentonmcs fix on latest master

### PR DESCRIPTION
**Pull request by ponelat**
Fixes an undefined error when type is defined in the schema

### CODE REVIEW

**Comment by brentonmcs** [comment]
Thanks @ponelat

**Comment by ponelat** [comment]
@brentonmcs np... we are about to put out a release, so I thought it I'd try and get this in... I'm just cleaning up the travis build :)

**Comment by ponelat** [comment]
@fehguy so here is a problem and a possible fix.
You may have noticed the builds failing in travis (they have for a couple of weeks now). 
Well, I dug deep.... too deep, and now I'm getting tired of digging.

Here is the issue, https://github.com/swagger-api/swagger-ui/issues/1773
An alternative, and a relatively cheap fix is to bump the travis build to use node.js v4.2.2 . How this affects the Buffer builtin, truly baffles me. As swagger-ui has no browserify

Thats what I did in this PR... to prove it works.

**Comment by fehguy** [comment]
well... I think the node issue is only because of the running of the headless tests.  So let's merge this!

**Pull request merged**
