### PR TITLE
Namespaces for arrays

### PR DESCRIPTION
**Pull request by bodnia**
fixes issues
https://github.com/swagger-api/swagger-ui/issues/2077
https://github.com/swagger-api/swagger-ui/issues/2191

### CODE REVIEW

**Comment by bodnia** [comment]
@webron @fehguy could you please review and merge?

**Comment by fehguy** [comment]
@webron can you please test this?

**Comment by webron** [comment]
Tested and confirmed as solving the referenced issues.

**Comment by bodnia** [comment]
@webron this may be merged if resolving conflicts in build js files?

**Comment by fehguy** [comment]
hi @bodnia yes

**Comment by bodnia** [comment]
@fehguy could you please merge?

**Pull request merged**
