### PR TITLE
fix(plugin): allow Topbar plugin to read url param on load

### LINKED ISSUE #7835: Swagger urls.primaryName not working
### Q&A (please complete the following information)
 - OS: Fedora 35
 - Browser: Chrome
 - Version: 97.0.4692.99
 - Method of installation: docker
 - Swagger-UI version: 4.5.0
 - Swagger/OpenAPI version: OpenAPI 3.0.1

### Content & configuration

Environment config:
 ```
       env:
          - name: URLS
            value: '[{url: "http://example.com/openapi.json", name: "orch"}, {url: "https://dev.example.com/openapi.json", name: "orch-DEV-master"}, {url: "http://stable.example.com/openapi.json", name: "orch-DEV-stable-next"}, {url: "http://stage.example.com/openapi.json", name: "orch-STAGE"}]'
```

```
/?urls.primaryName=orch-DEV-master
```

### Describe the bug you're encountering

The urls.primaryName parameter is ignored when accessing the page and "orch" definition is always shown.
Once the page loads, switching to different definition by the dropdown works as expected.

### To reproduce...

1. Go to '<swagger-ui-url>/?urls.primaryName=orch-DEV-master'
2. See that definition orch is selected 

### Expected behavior

The definition should be selected according to the parameter in URL.

### Screenshots

image

### LINKED ISSUE #8039: Make direct URLs with urls.primaryName query param possible without QUERY_CONFIG_ENABLED
Because of https://github.com/swagger-api/swagger-ui/security/advisories/GHSA-qrmm-w75w-3wpx you have disabled QUERY_CONFIG_ENABLED by default, but this breaks direct links to specs when working with _urls_.

The topbar itself adds _"?urls.primaryName=<name>"_ to the address bar, but when you refresh the page you end up on the first spec.

Users are now forced to enable QUERY_CONFIG_ENABLED (which has security implications), just to allow those direct URLs.

So I think you either don't add that queryParam to the address bar (because it sets the wrong expectation), or you explicitly allow that _urls.primaryName_ without having to set QUERY_CONFIG_ENABLED to true

### PR DESCRIPTION
**Pull request by chadknight-wf**
### Description
The `Topbar` plugin manipulates the querystring param, adding `urls.primaryName` to track the selected spec. If you have `queryConfigEnabled` set to true, you can use this to link directly to a specific spec (e.g. `my-swagger-ui.com/?urls.primaryName=MyChosenSpec`), and the plugin will load that named spec from your config.

If you have `queryConfigEnabled` set to false - which seems like the recommended option to prevent some security issues (https://github.com/swagger-api/swagger-ui/security/advisories/GHSA-qrmm-w75w-3wpx) - this functionality no longer works.

In this PR, I update `componentDidMount` to check the querystring directly, with a fallback to the config. I believe this is safe since the param is the name of a configured URL, not an arbitrary URL. And this allows users who don't enable query config to still benefit from the direct linking feature.

### Motivation and Context
Fixes #8039
Fixes #7835

### How Has This Been Tested?
I built this change locally, referenced the built files in a local project, and noted that the intended API spec is loaded.

I didn't find any existing unit tests for the Topbar or integration tests for this `?urls.primaryName` behavior.

### My PR contains... 
- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [x] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tim-lai** [comment]
@chadknight-wf Thanks for the PR! The change seems innocuous enough to me. Thinking about how to quickly implement a for test this fix, perhaps you could setup a Cypress test (`test/e2e-cypress/tests/features/plugins/topbar/<testName>`) where in `cy.visit()`, you intercept the `?urls.primaryName` to point to whatever the local path is. Then switch and assert among different url params.

**Comment by chadknight-wf** [comment]
Thanks @tim-lai! I've added a test setup that mirrors my use case pretty well, with a new `index.html` to interact with.

**Review by tim-lai — COMMENTED** [review]
@chadknight-wf The test setup looks good. One last minor change requested... since the static page can be used generically, and it looks like the only difference is specifying `urls` instead of `url`, let's change the path to `static/pages/multiple-urls/index.html`

**Comment by tim-lai** [comment]
@chadknight-wf PR merged! Thanks for the contribution and iteration!

**Comment by chadknight-wf** [comment]
Thanks for the guidance!

**Comment by ChristianHudonDTI** [comment]
Thank you for this. 
This will be helpful to us.

**Pull request merged**
