### PR TITLE
support pkce when using basic auth header

### LINKED ISSUE #7037: Setting useBasicAuthenticationWithAccessCodeGrant disables usePkceWithAuthorizationCodeGrant
### Q&A (please complete the following information)
 - OS: linux
 - Browser: chrome
 - Version: latest
 - Method of installation: swagger-ui-express
 - Swagger-UI version: 3.44.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
```js
initOAuth({
      usePkceWithAuthorizationCodeGrant: true,
      useBasicAuthenticationWithAccessCodeGrant: true,
})
```
### Describe the bug you're encountering
I was using
```js
initOAuth({
      usePkceWithAuthorizationCodeGrant: true,
})
```
and saw the pkce post params fine.

when I added to it `useBasicAuthenticationWithAccessCodeGrant`

It stopped sending the pkce post params

### Screenshots
image

### PR DESCRIPTION
**Pull request by hcldan**
Fixes #7037

I hope... it looks like it should but the setup I am using only seems to have minified swagger-ui code.

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by hcldan** [comment]
@mathis-m @tim-lai could one of you take a look at and possibly merge this?

**Review by mathis-m — APPROVED** [review]
As [documentation](https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/#:~:text=useBasicAuthenticationWithAccessCodeGrant,clients.%20The%20default%20is%20false) states:
`useBasicAuthenticationWithAccessCodeGrant` does execute authorization_code AND `usePkceWithAuthorizationCodeGrant` does only apply to authorizatonCode flows it should be implemented this way. Have not confirmed functionality but logic wise it looks good.

**Comment by mathis-m** [comment]
@hcldan you should probably add a test here to verify the changed logic `test/unit/core/plugins/auth/actions.js`.

**Comment by hcldan** [comment]
@mathis-m I would be more comfortable doing that if there were already a test for pkce in there...  I'm not sure what kind of mocking you guys are expecting, and I don't have a dev env for this project.  I'm coming from swagger-ui-express and noticed that the auth flow was messed up.

**Comment by mathis-m** [comment]
@hcldan i can have a look and create pr to your branch.

**Comment by hcldan** [comment]
@mathis-m thank you very much!

**Comment by mathis-m** [comment]
@hcldan have added PR https://github.com/hcldan/swagger-ui/pull/1

**Comment by tim-lai** [comment]
@hcldan @mathis-m PR merged! Thanks guys on the collaboration!

**Comment by hcldan** [comment]
@tim-lai  can you kick out a release?

**Comment by hcldan** [comment]
@mathis-m any chance of cutting a new release?

**Comment by mathis-m** [comment]
Tim has merged several pr yesterday, I guess there will be some release soon.

**Comment by tim-lai** [comment]
Yup, a new release is now availabe. 😺

**Pull request merged**
