### PR TITLE
Fix for #1113

### PR DESCRIPTION
**Pull request by mgttlinger**

### CODE REVIEW

**Comment by mohsen1** [comment]
LGTM 
Please run `gulp` to make a new build in `dist`.

**Comment by mgttlinger** [comment]
@mohsen1  Should I do this and create a new pull request?

**Comment by webron** [comment]
@mgttlinger - no need. Just do it, push it to your own fork/branch, and it'll become part of this PR.

**Comment by fehguy** [comment]
@ponelat can you please look at this?

**Comment by fehguy** [comment]
@ponelat my bad, I missed that @mohsen1 already reviewed.  Merging.

**Pull request merged**
