### PR TITLE
fix for xss issue

### PR DESCRIPTION
**Pull request by bodnia**

### CODE REVIEW

**Comment by bodnia** [comment]
@webron @fehguy could you please review?

**Comment by bodnia** [comment]
https://github.com/swagger-api/swagger-ui/issues/1617 https://github.com/swagger-api/swagger-ui/issues/1865

**Comment by fehguy** [comment]
Well done @bodnia, I'm reviewing this now.

**Comment by fehguy** [comment]
@bodnia looks like an issue with tags.  Try this spec:

```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: title
  description: description with **markdown** format
tags:
  - name: Admin
    description: tag with **markdown**
paths:
  /test:
    get:
      description: description with **markdown** format
      responses:
        200:
          description: a description with **markdown** format
          schema:
            $ref: '#/definitions/User'
    post:
      tags:
      - Admin tasks
      responses:
        200:
          description: nothing
    
definitions:
  User:
    description: also with **markdown**
    properties:
      name:
        description: prop with **markdown**
        type: string
      email:
        $ref: '#/definitions/Email'
  Email:
    type: string
    format: email
```

And note the `undefined` at each tag.  Also the description doesn't seem to appear.

image

**Comment by bodnia** [comment]
@fehguy could you please review latest commit

**Comment by fehguy** [comment]
Awesome, all tests pass for me.

**Pull request merged**
