### PR TITLE
Persist authorization: alternative aproach

### PR DESCRIPTION
**Pull request by Vanuan**
### Description
Continuation of #4852

Simpler implementation without redux-persist

### CODE REVIEW

**Comment by Vanuan** [comment]
Pushed to Docker Hub as `vanuan/swagger-ui:persist-authorization`

**Comment by smshuja** [comment]
Any plans to merge this?

**Comment by Phantas0s** [comment]
It would be really nice indeed...

**Comment by annguyen-qh** [comment]
Any update on this? This feature will be very helpful

**Comment by sagoo33** [comment]
Yes, having this merged would be great, with it remembering the token, we can hide endpoints that aren't authorized and refesh the page after authorization to show the now visible endpoints.

**Comment by waynebloss** [comment]
Is this project still being maintained?

**Comment by shockey** [comment]
@waynebloss yes 🙂 

---

I'm going to close this out — per [my change request](https://github.com/swagger-api/swagger-ui/pull/4852#issuecomment-419282071) over in #4852, we'd need a configuration flag for this behavior and tests in order to be able to accept it, which aren't present here.

To readers, and @Vanuan if you're still engaged with this project: feel free to open a successor PR that achieves this functionality and fits the requirements!

**Pull request closed without merging**
