### PR TITLE
fix: React warnings of "Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead."

### PR DESCRIPTION
**Pull request by firejune**
Remove deprecated warning that occurs in React 18.2.0.

### Description
When I am trying to use swagger-ui with react@18.2.0 I am getting this warning. The React [MR](https://github.com/facebook/react/pull/25699) to print this warning on console is here.

```
Warning: {FunctionComponentName}: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
```

### How Has This Been Tested?
I am pretty sure this is a small refactor to remove this warning and I could work on that 😄

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by char0n** [comment]
Hi @firejune,

Thanks for the PR! Can you please remove all the `./dist/*` changes from your PR? The `./dist` directory should only be modified by the release process.

**Comment by firejune** [comment]
Hi @char0n
Of course I can. I removed all changes in `./dist/*`.

**Review by char0n — APPROVED** [review]
LGTM! Thank you for contributing!

**Comment by char0n** [comment]
@firejune just FYI: react@18 has been added in https://github.com/swagger-api/swagger-ui/pull/9435

It hasn't been released yet, it will go out together with your change today/tommorow.

**Pull request merged**
