### PR TITLE
Add file download to try operation

### PR DESCRIPTION
**Pull request by mohsen1**

### CODE REVIEW

**Comment by fehguy** [comment]
@mohsen1 this will fail if there is any sort of header/key applied in fetching the file.  Can you fetch the bytes in an AJAX call with SwaggerHttp and set them in an iFrame for download?

**Comment by mohsen1** [comment]
`response.url` should have the API key in it, shouldn't it?

It's also possible to use [`Blob`](https://developer.mozilla.org/en-US/docs/Web/API/Blob) but it's IE10 plus and I feel it's redundant because setting `window.location` works perfectly if the key is in the URL.

**Comment by fehguy** [comment]
If a query param, yes.  If it's a header (which is most common), I don't know of a way to do that.

We could detect headers in the swagger.authorizations and do "something different"

**Comment by mohsen1** [comment]
I don't know any other option. I'm open to ideas

**Comment by fehguy** [comment]
Here's suggestion.  Let's use the blog support, and give an alert message if it's not supported?  We cannot support every possible version of every browser, but we can gracefully degrade when support is not there, especially for an advanced feature like this.

**Comment by mohsen1** [comment]
@fehguy added support for Blob

**Pull request merged**
