### PR TITLE
Prevent mangling of names in UMD distribution

### PR DESCRIPTION
**Pull request by fritz-c**
### Description

This will prevent UglifyJS from mangling names in UMD builds. 
This makes debugging easier in general.

### Motivation and Context

The source maps included with the current distribution are not factored in by default in build systems like create-react-app. Without the source maps, it's impossible to decipher the source of errors within the component (especially prop-types errors; see the screenshots below).

Since minimization will most likely occur during another build step inside whatever application uses the swagger-ui UMD distribution, this change will not be noticeable to most users of the library. The standalone builds still retain their original, mangling-enabled build behavior.

### Screenshots (if appropriate):
Console error before modification
before

Console error after modification
after
(This error is related to #4291, by the way)

### My PR contains... 

- [x] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by shockey** [comment]
I like this functionality, but will need to check what effect it has on the bundle size :smile:

**Comment by fritz-c** [comment]
It increases the UMD bundle size significantly.

**Comment by shockey** [comment]
Asset size diffs:
```sh
445B->445B favicon-16x16.png
1.1K->1.1K favicon-32x32.png
1.5K->1.5K index.html
2.3K->2.3K oauth2-redirect.html
1.4M->1.4M swagger-ui-bundle.js
5.3M->5.3M swagger-ui-bundle.js.map
430K->430K swagger-ui-standalone-preset.js
1.8M->1.8M swagger-ui-standalone-preset.js.map
150K->150K swagger-ui.css
91B -> 91B swagger-ui.css.map
359K->599K swagger-ui.js # changed
1.2M->1.2M swagger-ui.js.map
```

So, all things considered this increases the module (_not_ the bundle) size by 66%.

**Comment by shockey** [comment]
thanks @fritz-c!

**Pull request merged**
