### PR TITLE
Make SwaggerUi UMD compatible

### LINKED ISSUE #777: Consider re-factoring swagger-ui into a component
IMO, swagger-ui should be a drop-in component which should behave as a module and have external dependencies, but is currently structured as an application.

This causes issues with baked-in dependencies and the need to distribute the project with copies of third party libraries.

Structuring the project as a module following AMD/CommonJS paradigms and utilising a registry such as bower for third-party dependencies could make the project far easier to manage, update and integrate into other applications.

### PR DESCRIPTION
**Pull request by mohsen1**
Fixes #777

### CODE REVIEW

**Comment by fehguy** [comment]
@mohsen1 build error...

**Comment by mwcz** [comment]
Does this fix shred's overwriting of existing AMD loaders?

**Comment by mohsen1** [comment]
@mwcz Yes, shred is gone. Actually will be gone by https://github.com/swagger-api/swagger-ui/pull/1067.

**Comment by mwcz** [comment]
Nice!  @mohsen1 :+1:

**Pull request merged**
