### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by webron** [comment]
@kkirsche - Thanks for the PR, but those need to be submitted against develop_2.0. Please resubmit against that branch.

**Comment by kkirsche** [comment]
Already was there @webron

**Comment by kkirsche** [comment]
see the other pr...

**Comment by webron** [comment]
Saw it ;)

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Pull request closed without merging**
