### PR TITLE
Remove object-assign

### PR DESCRIPTION
**Pull request by ponelat**
**remove object-assign dep ( which was missing from package.json )**

**revert to older react version, may break editor**

Don't merge this until swagger-editor (insert-pr-here) is merged

### CODE REVIEW

**Comment by shockey** [comment]
Added `WIP` to title. @ponelat ping me when the corresponding editor PR is ready 😄

**Comment by ponelat** [comment]
@shockey too much effort to downgrade react across it. Went with another solution for my particular need.
Made this PR about the object-assign thing only ( renamed title, to match ). 
Should be good to merge. Not sure how this worked before... since the package.json didn't include any reference to `object-assign` package.

**Comment by shockey** [comment]
@ponelat merge conflict, please fix, i'm not able to add commits to your branch 😄

**Comment by ponelat** [comment]
hello `dist/` fol-der my friend.... 
I've come to re-compile again.

In restless issues we walked alone
Narrow streets of cobble-stone

'Neath the halo of a merge-conflict
I turned my collar to the cold and damp
When my eyes were stabbed by the flash of a notification

That split the night
And touched the sound of compiling

**Pull request merged**
